// Code generated by lib/renderers.nix renderDaemonKnobDefaultsGo from
// lib/env-schema.nix. DO NOT EDIT.
package daemon

// Regenerate with `nix run .#regen` after editing lib/env-schema.nix.

// shippedKnobDefaults is lib/env-schema.nix's default for each of the
// daemon's five tuning knobs, keyed by env var name -- the anti-vacuity
// root for backoff_test.go and breaker_test.go's shipped-default
// assertions (issue #3619).
var shippedKnobDefaults = map[string]string{
	"DAEMON_IDLE_FLOOR":        "5m",
	"DAEMON_IDLE_CAP":          "30m",
	"DAEMON_FAILURE_BACKOFF":   "1m",
	"DAEMON_BREAKER_THRESHOLD": "5",
	"DAEMON_BREAKER_WINDOW":    "15m",
}
