package registrydiscover

import (
	"fmt"
	"os"
	"strings"

	"spindrift.dev/launcher/internal/credresolver"
	"spindrift.dev/launcher/internal/registryroutes"
)

// Render serializes proposed routes as a routes file (ADR 0045 TOML).
// It hand-renders the fields instead of calling a TOML marshaller because the
// credential inline table's key is dynamic and hyphenated, a shape go-toml v2's
// Marshal has no struct tag for.
func Render(routes []Route) []byte {
	var b strings.Builder
	b.WriteString("# Registry routes file (ADR 0045). Generated by spindrift registry discover.\n")
	if anyEnvPlaceholder(routes) {
		b.WriteString("# Some routes below use a placeholder env credential -- set the named\n# environment variable, or edit the route, before relying on it.\n")
	}

	for _, r := range routes {
		b.WriteString("\n[[routes]]\n")
		fmt.Fprintf(&b, "match-host = %s\n", quoteTOMLString(r.MatchHost))
		// registryroutes owns the rule for whether a route needs an
		// upstream-origin. The migration remedies quote the same rule, so a
		// mirrored copy here that drifted would confuse an operator.
		if origin := registryroutes.UpstreamOriginFor(r.UpstreamBaseURL); origin != "" {
			fmt.Fprintf(&b, "upstream-origin = %s\n", quoteTOMLString(origin))
		}
		// Discovery probed this value, so always write it out rather than
		// leaning on registryroutes.Parse's "bearer" default, which is a
		// fallback for hand-written files.
		fmt.Fprintf(&b, "auth-scheme = %s\n", quoteTOMLString(r.AuthScheme))

		b.WriteString("credential = { ")
		fmt.Fprintf(&b, "%s = %s", r.CredentialSource, quoteTOMLString(r.CredentialValue))
		// A source with no kind (unrecognized) or no CompanionKey (such as
		// "env") renders no companion.
		if kind, ok := credresolver.KindBySourceKey(r.CredentialSource); ok && kind.CompanionKey != "" {
			companion := credresolver.Config{RegistryName: r.RegistryName, PropertyKey: r.PropertyKey}
			fmt.Fprintf(&b, ", %s = %s", kind.CompanionKey, quoteTOMLString(*kind.CompanionField(&companion)))
		}
		b.WriteString(" }\n")
	}

	return []byte(b.String())
}

// anyEnvPlaceholder reports whether any route carries the "env" placeholder
// credential, which an operator must replace before that route works.
func anyEnvPlaceholder(routes []Route) bool {
	for _, r := range routes {
		if r.CredentialSource == "env" {
			return true
		}
	}
	return false
}

// quoteTOMLString renders s as a TOML basic string, escaping control
// characters so the output stays single-line and spec-valid whatever
// discovery captured.
func quoteTOMLString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\b':
			b.WriteString(`\b`)
		case '\t':
			b.WriteString(`\t`)
		case '\n':
			b.WriteString(`\n`)
		case '\f':
			b.WriteString(`\f`)
		case '\r':
			b.WriteString(`\r`)
		default:
			if r < 0x20 || r == 0x7f {
				fmt.Fprintf(&b, `\u%04X`, r)
			} else {
				b.WriteRune(r)
			}
		}
	}
	b.WriteByte('"')
	return b.String()
}

// WriteFile renders routes to path, refusing to overwrite an existing file
// unless force is set.
func WriteFile(path string, routes []Route, force bool) error {
	rendered := Render(routes)
	if force {
		return os.WriteFile(path, rendered, 0o600)
	}

	// O_EXCL closes the TOCTOU window a separate Stat-then-WriteFile would
	// leave open between the check and the write.
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		if os.IsExist(err) {
			return fmt.Errorf("registrydiscover: routes file %q already exists; re-run with --force to overwrite", path)
		}
		return err
	}
	defer f.Close()

	if _, err := f.Write(rendered); err != nil {
		return err
	}
	return nil
}
