package registrydiscover

import (
	"fmt"
	"os"
	"strings"
)

// Render serializes proposed routes as a routes file (ADR 0045 TOML).
// Fields are hand-rendered rather than passed through a general TOML
// marshaller: the credential inline table's key is dynamic (the credential
// source name) and hyphenated ("cargo-credentials", "gradle-properties"),
// a shape go-toml v2's Marshal has no struct tag for.
func Render(routes []Route) []byte {
	var b strings.Builder
	b.WriteString("# Registry routes file (ADR 0045). Generated by spindrift registry discover.\n")
	if anyEnvPlaceholder(routes) {
		b.WriteString("# Some routes below use a placeholder env credential -- set the named\n# environment variable, or edit the route, before relying on it.\n")
	}

	for _, r := range routes {
		b.WriteString("\n[[routes]]\n")
		fmt.Fprintf(&b, "match-host = %s\n", quoteTOMLString(r.MatchHost))
		fmt.Fprintf(&b, "upstream-base-url = %s\n", quoteTOMLString(r.UpstreamBaseURL))
		// Always emitted explicitly: discovery measured this via probe, and
		// an explicit value beats relying on registryroutes.Parse's "bearer"
		// default, which is a fallback for hand-written files, not a promise
		// this writer should lean on.
		fmt.Fprintf(&b, "auth-scheme = %s\n", quoteTOMLString(r.AuthScheme))

		b.WriteString("credential = { ")
		fmt.Fprintf(&b, "%s = %s", r.CredentialSource, quoteTOMLString(r.CredentialValue))
		switch r.CredentialSource {
		case "cargo-credentials":
			fmt.Fprintf(&b, ", registry-name = %s", quoteTOMLString(r.RegistryName))
		case "gradle-properties":
			fmt.Fprintf(&b, ", key = %s", quoteTOMLString(r.PropertyKey))
		}
		b.WriteString(" }\n")
	}

	return []byte(b.String())
}

// anyEnvPlaceholder reports whether any route's credential is the "env"
// placeholder Discover proposes for a host it couldn't match to a store --
// that route needs an operator to fill in a real credential before use,
// which is worth flagging in the file's header comment.
func anyEnvPlaceholder(routes []Route) bool {
	for _, r := range routes {
		if r.CredentialSource == "env" {
			return true
		}
	}
	return false
}

// quoteTOMLString renders s as a TOML basic string: a double-quoted string
// with backslash and double-quote escaped, plus control characters escaped
// so the output stays a single-line, spec-valid basic string regardless of
// what discovery captured (a store path or an env var name, never operator
// free text, but escaped defensively all the same).
func quoteTOMLString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\b':
			b.WriteString(`\b`)
		case '\t':
			b.WriteString(`\t`)
		case '\n':
			b.WriteString(`\n`)
		case '\f':
			b.WriteString(`\f`)
		case '\r':
			b.WriteString(`\r`)
		default:
			if r < 0x20 || r == 0x7f {
				fmt.Fprintf(&b, `\u%04X`, r)
			} else {
				b.WriteRune(r)
			}
		}
	}
	b.WriteByte('"')
	return b.String()
}

// WriteFile renders routes to path. It refuses to overwrite an existing
// file unless force is set; the refusal error names path.
func WriteFile(path string, routes []Route, force bool) error {
	rendered := Render(routes)
	if force {
		return os.WriteFile(path, rendered, 0o600)
	}

	// O_EXCL makes the existence check and the write a single atomic
	// operation, closing the TOCTOU window a separate Stat-then-WriteFile
	// would leave open between the check and the write.
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		if os.IsExist(err) {
			return fmt.Errorf("registrydiscover: routes file %q already exists; re-run with --force to overwrite", path)
		}
		return err
	}
	defer f.Close()

	if _, err := f.Write(rendered); err != nil {
		return err
	}
	return nil
}
