{
  description = "A spindrift consumer — headless Claude Code agents in nix-built, disposable containers, one per GitHub issue";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-parts.url = "github:hercules-ci/flake-parts";
    spindrift.url = "github:jordansmall/spindrift";
  };

  outputs =
    inputs@{
      flake-parts,
      spindrift,
      ...
    }:
    flake-parts.lib.mkFlake { inherit inputs; } {
      systems = [
        "aarch64-darwin"
        "aarch64-linux"
        "x86_64-linux"
      ];

      imports = [ spindrift.flakeModules.default ];

      perSystem =
        { config, pkgs, ... }:
        {
          # Generated by quickstart with only the chosen options. Full
          # reference: docs/flake-options.md
          # Deliberately broken guard fixture (issue #2565): infra.runtime is
          # set to a value outside the runtime enum, so a later nix check can
          # assert this scaffold throws at eval time against the real
          # spindrift flake module. Not meant to render cleanly — no Go test
          # reads this file.
          spindrift = {
            infra.runtime = "not-a-real-runtime";
            forge.repoSlug = "jordansmall/spindrift-consumer-example";
            git.user.name = "Ada Lovelace";
            git.user.email = "ada@example.com";
            issues.tracker = "github";
          };

          devShells.default = pkgs.mkShell {
            packages = [ config.packages.spindrift ];
          };
        };
    };
}
