// Code generated by nix/regen.nix from lib/agent-paths.nix. DO NOT EDIT.
package agentpaths

// Regenerate with `nix run .#regen` after editing lib/agent-paths.nix.
//
// The 9 baked /agent/* path literals (lib/agent-paths.nix), single-sourced
// here so the Go launcher can never drift from the Nix image/preamble
// source of truth (issue #2531) -- a rename in lib/agent-paths.nix now fails
// nix/checks/schema-drift.nix's agent-paths-gen check instead of silently
// mounting onto a dead in-box path.

// CheckContractFile is the baked in-box path for CHECK_CONTRACT_FILE.
const CheckContractFile = "/agent/check-contract.md"

// CodeCommentsContractFile is the baked in-box path for CODE_COMMENTS_CONTRACT_FILE.
const CodeCommentsContractFile = "/agent/code-comments-contract.md"

// CommsContractFile is the baked in-box path for COMMS_CONTRACT_FILE.
const CommsContractFile = "/agent/comms-contract.md"

// ForbiddenMarkersRegistryFile is the baked in-box path for FORBIDDEN_MARKERS_REGISTRY_FILE.
const ForbiddenMarkersRegistryFile = "/agent/forbidden-markers-registry.json"

// OutcomeContractFile is the baked in-box path for OUTCOME_CONTRACT_FILE.
const OutcomeContractFile = "/agent/outcome-contract.md"

// PromptassemblyRegistryFile is the baked in-box path for PROMPTASSEMBLY_REGISTRY_FILE.
const PromptassemblyRegistryFile = "/agent/fragments-registry.json"

// PromptsDir is the baked in-box path for PROMPTS_DIR.
const PromptsDir = "/agent/prompts"

// PromptContractRegistryFile is the baked in-box path for PROMPT_CONTRACT_REGISTRY_FILE.
const PromptContractRegistryFile = "/agent/prompt-contract-registry.json"

// ResearchOutcomeContractFile is the baked in-box path for RESEARCH_OUTCOME_CONTRACT_FILE.
const ResearchOutcomeContractFile = "/agent/research-outcome-contract.md"
