// Code generated by nix/regen.nix from lib/chore-catalog.nix. DO NOT EDIT.
package chore

// builtinChores is the name list of the built-in Chore catalog (lib/chore-catalog.nix).
// Regenerate with `nix run .#regen` after editing lib/chore-catalog.nix.
var builtinChores = []string{"bugs", "docs-drift", "refactor"}
