# Code generated by lib/renderers.nix renderSetBoxEnvFixture from
# lib/env-schema.nix. DO NOT EDIT.
# Regenerate with `nix run .#regen` after editing lib/env-schema.nix.

# Every lib/env-schema.nix knob with boxEnv = true, exported at its schema
# default (or placeholder, for a knob with no default), so the
# entrypoint-*.bats suites exercise the same defaults the nix preamble
# bakes into the image at build time. Individual tests override any of
# these before invoking $ENTRYPOINT.
set_box_env() {
  export ANTHROPIC_API_KEY=""
  export AUTO_FORMAT=""
  export AUTO_LINT=""
  export BASE_BRANCH="main"
  export BRANCH_PREFIX="agent/issue-"
  export CLAUDE_CODE_OAUTH_TOKEN="fake-oauth"
  export CODE_FORGE="github"
  export CODE_FORGE_REMOTE_URL=""
  export COMPLETE_LABEL="agent-complete"
  export DEV_SHELL_NAME="default"
  export DEV_SHELL_PROBE_TIMEOUT=300
  export FILER_MODEL=""
  export GH_TOKEN="fake-token"
  export GIT_USER_EMAIL="bot@example.com"
  export GIT_USER_NAME="Test Bot"
  export IN_PROGRESS_LABEL="agent-in-progress"
  export ISSUE_TRACKER="github"
  export LOCAL_ISSUE_REFERENCE=""
  export MODEL="claude-sonnet-5"
  export REPO_SLUG="owner/repo"
  export REVIEW_MODEL="claude-opus-4-8"
  export SCOUT_MODEL="claude-haiku-4-5-20251001"
}
