#!/usr/bin/env bats
# The prompt is baked into the image, so `run` mounts nothing by default; it
# only bind-mounts a dir under the on-disk override (SPINDRIFT_PROMPT_DIR).
# Driven through the fake podman.

load helper

setup() {
  setup_fakes
  set_run_env
  cd "$BATS_TEST_TMPDIR"
  export FAKE_GH_ISSUES=$'1\tFirst issue'
  export FAKE_PODMAN_IMAGE_PRESENT=1
  unset SPINDRIFT_PROMPT_DIR
}

@test "run mounts no prompt dir by default (prompt is baked into the image)" {
  run "$RUN_CMD"
  [ "$status" -eq 0 ]
  ! grep -q -- ':/agent/prompts' "$PODMAN_LOG"
  [[ "$output" != *"SPINDRIFT_PROMPT_DIR"* ]]
}

@test "SPINDRIFT_PROMPT_DIR overrides the baked prompt dir with a log line" {
  local override="$BATS_TEST_TMPDIR/myprompts"
  mkdir -p "$override"
  echo "hot-override" >"$override/issue-prompt.md"
  export SPINDRIFT_PROMPT_DIR="$override"
  run "$RUN_CMD"
  [ "$status" -eq 0 ]
  [[ "$output" == *"SPINDRIFT_PROMPT_DIR"* ]]
  grep -q -- "-v $override:/agent/prompts" "$PODMAN_LOG"
  ! grep -q -- "-v $PROMPT_PATH:/agent/prompts" "$PODMAN_LOG"
}

@test "SPINDRIFT_PROMPT_DIR pointing at a missing dir uses the baked prompt (no mount)" {
  export SPINDRIFT_PROMPT_DIR="$BATS_TEST_TMPDIR/nope"
  run "$RUN_CMD"
  [ "$status" -eq 0 ]
  ! grep -q -- ':/agent/prompts' "$PODMAN_LOG"
  [[ "$output" != *"SPINDRIFT_PROMPT_DIR"* ]]
}

@test "SPINDRIFT_PROMPT_DIR mount covers all three prompt files via directory bind" {
  local override="$BATS_TEST_TMPDIR/myprompts"
  mkdir -p "$override"
  echo "hot-override" >"$override/issue-prompt.md"
  echo "custom-scout" >"$override/scout-prompt.md"
  echo "custom-review" >"$override/review-prompt.md"
  export SPINDRIFT_PROMPT_DIR="$override"
  run "$RUN_CMD"
  [ "$status" -eq 0 ]
  grep -q -- "-v $override:/agent/prompts" "$PODMAN_LOG"
}

@test "scout prompt forbids mid-turn narration between tool calls" {
  local prompts="${PROMPTS_DIR:-$BATS_TEST_DIRNAME/../templates/default/prompts}"
  local prompt="$prompts/scout-prompt.md"
  grep -qi 'between tool calls' "$prompt"
}

@test "review prompt forbids mid-turn narration between tool calls" {
  local prompts="${PROMPTS_DIR:-$BATS_TEST_DIRNAME/../templates/default/prompts}"
  local prompt="$prompts/review-prompt.md"
  grep -qi 'between tool calls' "$prompt"
}

@test "review prompt caps each finding at one line" {
  local prompts="${PROMPTS_DIR:-$BATS_TEST_DIRNAME/../templates/default/prompts}"
  local prompt="$prompts/review-prompt.md"
  grep -qi 'one line' "$prompt"
}

@test "review prompt fetches before diffing against the origin base" {
  # The implementor rebases against origin/BASE_BRANCH; the reviewer must
  # diff against the same fetched ref, not a possibly-stale local one.
  local prompts="${PROMPTS_DIR:-$BATS_TEST_DIRNAME/../templates/default/prompts}"
  local prompt="$prompts/review-prompt.md"
  grep -q 'git fetch origin' "$prompt"
  grep -qF 'git diff origin/${BASE_BRANCH}...HEAD' "$prompt"
  grep -qF 'git log origin/${BASE_BRANCH}..HEAD' "$prompt"
}

@test "conflict-resolve prompt forbids mid-turn narration between tool calls" {
  local prompts="${PROMPTS_DIR:-$BATS_TEST_DIRNAME/../templates/default/prompts}"
  local prompt="$prompts/conflict-resolve-prompt.md"
  grep -qi 'between tool calls' "$prompt"
}

@test "conflict-resolve prompt requires source-of-truth resolution and regeneration for generated files" {
  # A conflicted file that declares itself generated (DO NOT EDIT / Code
  # generated by X from Y) must never be hand-merged directly; the agent
  # must resolve the conflict in its source of truth and regenerate the
  # artifact instead. Wording must stay repo-agnostic (issue #403).
  local prompts="${PROMPTS_DIR:-$BATS_TEST_DIRNAME/../templates/default/prompts}"
  local prompt="$prompts/conflict-resolve-prompt.md"
  grep -qi 'do not edit' "$prompt"
  grep -qi 'source of truth' "$prompt"
  grep -qi 'regenerat' "$prompt"
  grep -qi 'never hand-merge' "$prompt"
}

@test "WATCH CI section uses GraphQL statusCheckRollup not gh pr checks" {
  # gh pr checks uses the check-runs REST endpoint which 403s under
  # fine-grained PATs; the prompt must use statusCheckRollup (GraphQL).
  # PROMPTS_DIR is exported by the nix check derivation; fall back to the
  # source tree when running bats locally outside the nix harness.
  local prompts="${PROMPTS_DIR:-$BATS_TEST_DIRNAME/../templates/default/prompts}"
  local prompt="$prompts/issue-prompt.md"
  ! grep -q 'until gh pr checks' "$prompt"
  grep -q 'statusCheckRollup' "$prompt"
  grep -qi 'fine-grained' "$prompt"
}

@test "COMMS section establishes machine-log voice with human-prose carve-outs" {
  # Output is a machine-parsed log, not a conversation: no pleasantries and
  # no restating subagent output, except on the surfaces that stay human
  # prose (commits, PR body, IF BLOCKED comment, outcome note=). All
  # assertions are scoped to the COMMS section itself, not just the file,
  # so the test still fails if the carve-out sentence is dropped even
  # though those surfaces are named elsewhere in the prompt too.
  local prompts="${PROMPTS_DIR:-$BATS_TEST_DIRNAME/../templates/default/prompts}"
  local prompt="$prompts/issue-prompt.md"
  local comms
  comms="$(sed -n '/^# COMMS$/,/^# [A-Z]/p' "$prompt")"
  [ -n "$comms" ]
  grep -qi 'no pleasantries' <<<"$comms"
  grep -qi 'never restate' <<<"$comms"
  grep -qi 'one terse' <<<"$comms"
  grep -qi 'reserved exclusively' <<<"$comms"
  grep -qi 'Conventional Commits' <<<"$comms"
  grep -qi 'PR title and body' <<<"$comms"
  grep -qi 'IF BLOCKED' <<<"$comms"
  grep -qi 'note=' <<<"$comms"
}

@test "CHECK section forbids backgrounding a blocking gate and requires a terminal outcome" {
  # The WATCH CI never-background rule (issue #571) must generalize to the
  # CHECK phase's long build/test gates, not just the CI-watch loop -- an
  # agent that backgrounds `nix build .#checks-inbox` and ends its turn
  # never emits SPINDRIFT_OUTCOME and the run is lost.
  local prompts="${PROMPTS_DIR:-$BATS_TEST_DIRNAME/../templates/default/prompts}"
  local prompt="$prompts/issue-prompt.md"
  local check
  check="$(sed -n '/^# CHECK$/,/^# REVIEW$/p' "$prompt")"
  [ -n "$check" ]
  grep -qi 'never background' <<<"$check"
  grep -qi 'foreground' <<<"$check"
  grep -q 'SPINDRIFT_OUTCOME' <<<"$check"
}

@test "CHECK section treats a vanished exit marker as a failure, not still-pending" {
  # issue #713: the #640 incident agent backgrounded the check build anyway
  # and polled for a NIXEXIT marker file. A SIGKILLed/OOM'd build never
  # writes that marker, so an unbounded poll for it hangs forever instead of
  # surfacing the kill as a failure. The primary rule above is "never
  # background it"; this is the defensive fallback for when an agent does
  # it anyway.
  local prompts="${PROMPTS_DIR:-$BATS_TEST_DIRNAME/../templates/default/prompts}"
  local prompt="$prompts/issue-prompt.md"
  local check
  check="$(sed -n '/^# CHECK$/,/^# REVIEW$/p' "$prompt")"
  [ -n "$check" ]
  grep -qi 'vanished' <<<"$check"
  grep -qi 'exit marker' <<<"$check"
  grep -qi 'bound the wait' <<<"$check"
}

@test "CHECK section tells the agent to git add new files before nix build" {
  # issue #714: nix flakes only evaluate git-tracked files. An agent that
  # creates a new file and runs `nix build` before staging it hits a
  # spurious "not tracked by Git" failure and burns a checks cycle. The
  # guidance must land before the flake.nix paragraph so it primes every
  # nix invocation, not just the first one.
  local prompts="${PROMPTS_DIR:-$BATS_TEST_DIRNAME/../templates/default/prompts}"
  local prompt="$prompts/issue-prompt.md"
  local check
  check="$(sed -n '/^# CHECK$/,/^# REVIEW$/p' "$prompt")"
  [ -n "$check" ]
  grep -qi 'git add' <<<"$check"
  grep -qi 'tracked' <<<"$check"
  local add_line flake_line
  add_line="$(grep -n -i 'git add' <<<"$check" | head -1 | cut -d: -f1)"
  flake_line="$(grep -n 'flake.nix' <<<"$check" | head -1 | cut -d: -f1)"
  [ -n "$add_line" ]
  [ -n "$flake_line" ]
  [ "$add_line" -lt "$flake_line" ]
}

@test "prompt branches CODE_FORGE=git to a push-only outcome, no PR/CI" {
  # CODE_FORGE=git (#330) must skip PR creation and CI-watch entirely and
  # emit a branch ref where a PR URL would go.
  local prompts="${PROMPTS_DIR:-$BATS_TEST_DIRNAME/../templates/default/prompts}"
  local prompt="$prompts/issue-prompt.md"
  grep -q 'CODE_FORGE=git' "$prompt"
  grep -q 'skip OPEN A PULL REQUEST and WATCH CI' "$prompt"
  grep -qF 'landing=${BRANCH} status=ready' "$prompt"
  grep -q 'Do NOT run `gh pr create`' "$prompt"
}
