// Code generated by nix/regen.nix from lib/backends/default.nix. DO NOT EDIT.
package backend

// GitHub is the descriptor for the "github" backend.
var GitHub = Descriptor{
	Name:               "github",
	ValidAsTracker:     true,
	ValidAsCodeForge:   true,
	TokenEnvVar:        "GH_TOKEN",
	OutboxRelayCapable: true,
}

// Git is the descriptor for the "git" backend.
var Git = Descriptor{
	Name:             "git",
	ValidAsCodeForge: true,
}

// Local is the descriptor for the "local" backend.
var Local = Descriptor{
	Name:                    "local",
	ValidAsTracker:          true,
	ValidAsCodeForge:        true,
	HostMediatedRemote:      true,
	InBoxUnreachableTracker: true,
}

// Jira is the descriptor for the "jira" backend.
var Jira = Descriptor{
	Name:            "jira",
	ValidAsTracker:  true,
	TokenEnvVar:     "JIRA_TOKEN",
	DoctorTokenHint: "JIRA_TOKEN",
	DoctorSlugHint:  "JIRA_BASE_URL / JIRA_PROJECT_KEY",
}

// Forgejo is the descriptor for the "forgejo" backend.
var Forgejo = Descriptor{
	Name:             "forgejo",
	ValidAsTracker:   true,
	ValidAsCodeForge: true,
	TokenEnvVar:      "FORGEJO_TOKEN",
	DoctorTokenHint:  "FORGEJO_TOKEN",
	DoctorSlugHint:   "FORGEJO_BASE_URL",
}

var Registry = []Descriptor{GitHub, Git, Local, Jira, Forgejo}
