// Code generated by nix/regen.nix from lib/promptassembly-boxenv.nix. DO NOT EDIT.
package promptassembly

import (
	"os"
	"strconv"
)

// EnvFromEnviron reads Env's 29 Box-env-sourced fields directly from the
// process environment (lib/promptassembly-boxenv.nix, issue #2979): fields
// driver-exec/assembleprompt_cmd.go previously populated from a
// hand-declared CLI flag that agent/entrypoint.sh forwarded 1:1 from the
// same env var, until this issue wired this function in and dropped
// those flags. Every other Env field -- the skill-baked/SkillsFound
// filesystem probes and the path-shaped CLI-flag inputs (prompt/contract
// file locations) -- is left at its zero value; assembleprompt_cmd.go
// still layers those on from flags, since they were never env reads to
// begin with.
// Regenerate with `nix run .#regen` after editing
// lib/promptassembly-boxenv.nix.
func EnvFromEnviron() Env {
	return Env{
		OrchestratorEnabled:    os.Getenv("ORCHESTRATOR_ENABLED") != "",
		AgentsJSONTemplate:     os.Getenv("AGENTS_JSON_TEMPLATE"),
		FilerEnabled:           os.Getenv("BOX_FILER_ENABLED") != "",
		WorkerProvisioned:      os.Getenv("BOX_WORKER_PROVISIONED") != "",
		ReviewLoopInline:       os.Getenv("BOX_REVIEW_LOOP_INLINE") != "",
		ReviewLoopOrchestrator: os.Getenv("BOX_REVIEW_LOOP_ORCHESTRATOR") != "",
		IssueTracker:           os.Getenv("ISSUE_TRACKER"),
		TrackerAxisRead:        os.Getenv("BOX_TRACKER_AXIS_READ"),
		TrackerAxisWrite:       os.Getenv("BOX_TRACKER_AXIS_WRITE"),
		TrackerAxisFiler:       os.Getenv("BOX_TRACKER_AXIS_FILER"),
		BoxWriteEnabled:        os.Getenv("BOX_WRITE_ENABLED") != "",
		LocalIssueReference:    os.Getenv("LOCAL_ISSUE_REFERENCE") != "",
		CodeForge:              os.Getenv("CODE_FORGE"),
		ForgeBackend:           os.Getenv("BOX_FORGE_BACKEND"),
		DispatchKind:           os.Getenv("DISPATCH_KIND"),
		SelfContained:          os.Getenv("SELF_CONTAINED") == "1",
		FixPass:                boxenvAtoi(os.Getenv("FIX_PASS")),
		ResumeAfterHold:        os.Getenv("RESUME_AFTER_HOLD") != "",
		AutoFormat:             os.Getenv("AUTO_FORMAT") != "",
		AutoLint:               os.Getenv("AUTO_LINT") != "",
		CIFailureSummary:       os.Getenv("CI_FAILURE_SUMMARY"),
		IssueNumber:            os.Getenv("ISSUE_NUMBER"),
		IssueTitle:             os.Getenv("ISSUE_TITLE"),
		Branch:                 os.Getenv("BRANCH"),
		BaseBranch:             os.Getenv("BASE_BRANCH"),
		InProgressLabel:        os.Getenv("IN_PROGRESS_LABEL"),
		CompleteLabel:          os.Getenv("COMPLETE_LABEL"),
		RunNonce:               os.Getenv("RUN_NONCE"),
		ResearchStatusEnum:     os.Getenv("RESEARCH_STATUS_ENUM"),
	}
}

// boxenvAtoi parses an int-kind Box env var, degrading to 0 on empty or
// malformed input. Unlike cmd/launcher/main.go's atoiSchema, which falls
// back to a per-key schema default (intSchemaDefault), these 29 rows are
// deliberately outside lib/env-schema.nix (see
// lib/promptassembly-boxenv.nix's header) and so have no schema default
// to degrade to.
func boxenvAtoi(s string) int {
	n, err := strconv.Atoi(s)
	if err != nil {
		return 0
	}
	return n
}
