// Code generated by nix/regen.nix from lib/runtime-values.nix. DO NOT EDIT.
package runner

// ValidValues are the operator-facing runtime values (lib/runtime-values.nix),
// the same list lib/flakeModule.nix's `runtime` option enum uses, consumed
// by the quickstart wizard and anywhere else that needs the enum.
// Regenerate with `nix run .#regen` after editing lib/runtime-values.nix.
var ValidValues = []string{"podman", "docker", "rancher", "bwrap"}
