// Code generated by nix/regen.nix from lib/env-schema.nix. DO NOT EDIT.
package inputdoc

// Regenerate with `nix run .#regen` after editing lib/env-schema.nix.

// daemonOnlyKnobs is the set of knob env names only the daemon reads
// (launcherIgnores in the schema): no child reads them, so an ambient value
// still wins over the document in the daemon's Lookup (ADR 0020).
var daemonOnlyKnobs = map[string]bool{
	"DAEMON_APP":               true,
	"DAEMON_BREAKER_THRESHOLD": true,
	"DAEMON_BREAKER_WINDOW":    true,
	"DAEMON_FAILURE_BACKOFF":   true,
	"DAEMON_IDLE_CAP":          true,
	"DAEMON_IDLE_FLOOR":        true,
	"DAEMON_PROBE_INTERVAL":    true,
	"DAEMON_SELF_APP":          true,
	"RESEARCH_RESERVATION":     true,
}
