// Code generated by nix/regen.nix from lib/env-schema.nix. DO NOT EDIT.
package inputdoc

// Regenerate with `nix run .#regen` after editing lib/env-schema.nix.

// emptyIsSetting is the set of knob env names whose empty document value is
// a real setting, not "unset".
var emptyIsSetting = map[string]bool{
	"AUTO_FORMAT":           true,
	"AUTO_LINT":             true,
	"BWRAP_UNSHARE_NET":     true,
	"CONTINUOUS_DISPATCH":   true,
	"JIRA_INCLUDE_COMMENTS": true,
	"LOCAL_ISSUE_REFERENCE": true,
	"MEMORY_LIMIT":          true,
	"PIDS_LIMIT":            true,
	"PREFLIGHT_STALE_BASE":  true,
}
