// Code generated by nix/regen.nix from lib/cli-flags.nix. DO NOT EDIT.
package main

// cliFlags is the non-schema flag table derived from lib/cli-flags.nix.
// Regenerate with `nix run .#regen` after editing lib/cli-flags.nix.
var cliFlags = []cliFlag{
	{flag: "no-build", verb: "", arg: ""},
	{flag: "yes", verb: "", arg: ""},
	{flag: "force", verb: "", arg: ""},
	{flag: "self-contained", verb: "", arg: ""},
	{flag: "verbose", verb: "doctor", arg: ""},
	{flag: "butler", verb: "doctor", arg: ""},
	{flag: "chore", verb: "butler", arg: "name"},
	{flag: "help", verb: "", arg: ""},
	{flag: "version", verb: "", arg: ""},
	{flag: "secret-cmd", verb: "", arg: "command"},
}
