// Code generated by mkHarness.nix from lib/env-schema.nix. DO NOT EDIT.
package main

// defaultEntry maps one non-secret knob's env var name to its baked-in
// default from lib/env-schema.nix (empty string when the knob has no
// default).
type defaultEntry struct {
	env  string
	dflt string
}

// schemaDefaults is the defaults table derived from lib/env-schema.nix.
// loadConfig() consults it via schemaDefault() instead of a hand-written
// literal, so the schema stays the only place a default value is written.
// Run `nix flake check` after editing lib/env-schema.nix to regenerate.
var schemaDefaults = []defaultEntry{
	{env: "AUTO_FORMAT", dflt: ""},
	{env: "AUTO_LINT", dflt: ""},
	{env: "BASE_BRANCH", dflt: "main"},
	{env: "BRANCH_PREFIX", dflt: "agent/issue-"},
	{env: "BWRAP_UNSHARE_NET", dflt: ""},
	{env: "CODE_FORGE", dflt: "github"},
	{env: "CODE_FORGE_REMOTE_URL", dflt: ""},
	{env: "COMPLETE_LABEL", dflt: "agent-complete"},
	{env: "CONTINUOUS_DISPATCH", dflt: ""},
	{env: "DEV_SHELL_NAME", dflt: "default"},
	{env: "DEV_SHELL_PROBE_TIMEOUT", dflt: "300"},
	{env: "FAILED_LABEL", dflt: "agent-failed"},
	{env: "FILER_MODEL", dflt: ""},
	{env: "GIT_USER_EMAIL", dflt: ""},
	{env: "GIT_USER_NAME", dflt: ""},
	{env: "HOLD_JITTER_SECS", dflt: "5"},
	{env: "IN_PROGRESS_LABEL", dflt: "agent-in-progress"},
	{env: "ISSUE_NUMBER", dflt: ""},
	{env: "ISSUE_TRACKER", dflt: "github"},
	{env: "JIRA_BASE_URL", dflt: ""},
	{env: "JIRA_EMAIL", dflt: ""},
	{env: "JIRA_INCLUDE_COMMENTS", dflt: ""},
	{env: "JIRA_PROJECT_KEY", dflt: ""},
	{env: "JIRA_STATUS_MAPPING", dflt: ""},
	{env: "LABEL", dflt: "ready-for-agent"},
	{env: "LOCAL_ISSUES_DIR", dflt: ".spindrift/issues"},
	{env: "MAX_FIX_ATTEMPTS", dflt: "3"},
	{env: "MAX_JOBS", dflt: "0"},
	{env: "MAX_PARALLEL", dflt: "3"},
	{env: "MAX_REBASE_ATTEMPTS", dflt: "3"},
	{env: "MEMORY_LIMIT", dflt: "5g"},
	{env: "MERGE_GUARD_PATHS", dflt: ".github/**,**/CLAUDE.md,**/AGENTS.md,.claude/**,.opencode/**"},
	{env: "MERGE_MODE", dflt: "manual"},
	{env: "MERGE_POLL_INTERVAL", dflt: "30"},
	{env: "MERGE_POLL_TIMEOUT", dflt: "1800"},
	{env: "MODEL", dflt: "claude-sonnet-5"},
	{env: "OVERLAP_GATE", dflt: "defer"},
	{env: "PIDS_LIMIT", dflt: "512"},
	{env: "PODMAN_NETWORK", dflt: ""},
	{env: "REPO_SLUG", dflt: ""},
	{env: "REVIEW_MODEL", dflt: "claude-opus-4-8"},
	{env: "SCOUT_MODEL", dflt: "claude-haiku-4-5-20251001"},
	{env: "SPINDRIFT_PROMPT_DIR", dflt: ""},
	{env: "SPINDRIFT_SKILLS_DIR", dflt: ""},
	{env: "TRANSIENT_BACKOFF_SECS", dflt: "30"},
	{env: "TRANSIENT_RETRY_MAX", dflt: "3"},
}
