// Code generated by lib/renderers.nix renderDefaultModelFixtureGo from
// lib/default-model-fixture.nix. DO NOT EDIT.
package main

// Regenerate with `nix run .#regen` after editing lib/default-model-fixture.nix.

// expectedDefaultModels mirrors lib/default-model-fixture.nix's
// schemaDefaults -- the hand-typed anti-vacuity root for every
// bump-sensitive default-model assertion (issue #2514). dogfoodPins.filer
// is deliberately NOT rendered here: it is a Nix-only concept (nix/
// dogfood-defaults.nix's roster) with no Go-side consumer.
var expectedDefaultModels = map[string]string{
	"MODEL":        "claude-sonnet-5",
	"SCOUT_MODEL":  "claude-haiku-4-5-20251001",
	"REVIEW_MODEL": "claude-opus-5",
	"FILER_MODEL":  "",
	"WORKER_MODEL": "claude-sonnet-5",
}
