package main

import (
	"fmt"
	"os"
	"strings"
)

// flagEntry maps a runtime knob to its CLI flag.
// The schemaFlags table is generated by mkHarness.nix from lib/env-schema.nix.
type flagEntry struct {
	env  string // env-var name (SCREAMING_SNAKE_CASE)
	flag string // flag name without leading dashes (kebab-case)
	kind string // "string" or "int"
}

// parseFlags scans args for --flag-name value pairs defined in schemaFlags.
// Matching pairs are injected into the process environment via os.Setenv so
// loadConfig() picks them up (flag > env > baked default precedence).
// Unrecognised --flags return an error. Non-flag args and args after "--" are
// returned as-is.
func parseFlags(args []string) ([]string, error) {
	byFlag := make(map[string]*flagEntry, len(schemaFlags))
	for i := range schemaFlags {
		byFlag["--"+schemaFlags[i].flag] = &schemaFlags[i]
	}

	remaining := make([]string, 0, len(args))
	i := 0
	for i < len(args) {
		arg := args[i]
		if arg == "--" {
			remaining = append(remaining, args[i+1:]...)
			break
		}
		if !strings.HasPrefix(arg, "--") {
			remaining = append(remaining, arg)
			i++
			continue
		}
		entry, ok := byFlag[arg]
		if !ok {
			return nil, fmt.Errorf("unknown flag: %s", arg)
		}
		i++
		if i >= len(args) {
			return nil, fmt.Errorf("flag %s requires a value", arg)
		}
		if err := os.Setenv(entry.env, args[i]); err != nil {
			return nil, err
		}
		i++
	}
	return remaining, nil
}
