package main

import (
	"fmt"
	"io"
	"os"
	"os/exec"
	"strconv"
	"strings"
)

// version and revision are injected at build time via -ldflags.
var version = "dev"
var revision = "unknown"

func printVersion(w io.Writer) {
	fmt.Fprintf(w, "spindrift %s (rev %s)\n", version, revision)
}

// dispatchIssueArg extracts the optional issue number from the positional args
// following the "dispatch" verb. Returns the issue number if the first arg is a
// valid positive integer, otherwise returns empty string.
func dispatchIssueArg(args []string) string {
	if len(args) == 0 {
		return ""
	}
	if n, err := strconv.Atoi(args[0]); err == nil && n > 0 {
		return args[0]
	}
	return ""
}

// dispatchIssueArgs extracts all numeric positional args following the "dispatch"
// verb. Returns them in order; returns nil when none are present.
func dispatchIssueArgs(args []string) []string {
	var nums []string
	for _, a := range args {
		if n, err := strconv.Atoi(a); err == nil && n > 0 {
			nums = append(nums, a)
		}
	}
	return nums
}

// dispatchNoBuildArgs extracts the --no-build flag from the args following the
// "dispatch" verb. Returns (true, filtered) when the flag is present, where
// filtered has the flag removed so dispatchIssueArg sees only the issue number.
func dispatchNoBuildArgs(args []string) (noBuild bool, remaining []string) {
	for _, a := range args {
		if a == "--no-build" {
			noBuild = true
		} else {
			remaining = append(remaining, a)
		}
	}
	return
}

// dispatchYesArgs extracts the --yes/--force flag from the args following the
// "dispatch" verb. Returns (true, filtered) when either flag is present.
func dispatchYesArgs(args []string) (yes bool, remaining []string) {
	for _, a := range args {
		if a == "--yes" || a == "--force" {
			yes = true
		} else {
			remaining = append(remaining, a)
		}
	}
	return
}

// extractInputFlag pulls "--input <path>" out of args — the nix-rendered
// wrapper's sole nix-computed argument (ADR 0020): the Launcher input
// document's store path. Not a schema knob, so it is extracted before
// parseFlags rather than routed through schemaFlags/os.Setenv. Returns path
// empty and args unchanged when --input is absent (a direct binary
// invocation with no document, e.g. tests).
func extractInputFlag(args []string) (path string, remaining []string, err error) {
	for i := 0; i < len(args); i++ {
		if args[i] != "--input" {
			remaining = append(remaining, args[i])
			continue
		}
		if i+1 >= len(args) {
			return "", nil, fmt.Errorf("flag --input requires a value")
		}
		path = args[i+1]
		i++
	}
	return path, remaining, nil
}

// flagEntry maps a runtime knob to its CLI flag.
// The schemaFlags table is generated by mkHarness.nix from lib/env-schema.nix.
type flagEntry struct {
	env          string // env-var name (SCREAMING_SNAKE_CASE)
	flag         string // flag name without leading dashes (kebab-case)
	alias        string // optional short-form alias without leading dashes; empty when absent
	kind         string // "string" or "int"
	doc          string // one-line description from env-schema.nix
	dflt         string // baked-in default as a string; empty when there is none
	group        string // category heading for the full reference (from env-schema.nix)
	settingsPath string // settings.<section>.<knob> attr path; empty for a non-flakeOption knob
}

// secretKnob is a knob excluded from the value-flag surface (secret = true in
// the schema).  It has no inline value flag; callers must supply it via the
// environment or via --<fileFlag> (which reads from a file path).
// The secretKnobs table is generated by mkHarness.nix from lib/env-schema.nix.
type secretKnob struct {
	env      string
	doc      string
	fileFlag string // flag name for --<name>-file path variant (kebab-case, no dashes prefix)
	cmdFlag  string // flag name for --<name>-cmd command variant (kebab-case, no dashes prefix)
}

// secretCmdRunner executes a secret-fetch command string (from a --<name>-cmd
// flag or a <NAME>_CMD env var) through the OS shell and returns its raw
// stdout. A package var so tests can substitute a fake instead of spawning a
// real process (mirrors gitConfigLookup in inputdoc.go).
var secretCmdRunner = func(cmd string) (string, error) {
	out, err := exec.Command("sh", "-c", cmd).Output()
	return string(out), err
}

// resolveSecretCmd runs a secret-fetch command via secretCmdRunner and
// returns its trimmed stdout. A non-zero exit or empty output is reported
// with a named, value-free error — the command's stdout/stderr, which may
// carry a partial secret or vault diagnostics, never reaches the error
// message or a log.
func resolveSecretCmd(env, cmd string) (string, error) {
	out, err := secretCmdRunner(cmd)
	if err != nil {
		return "", fmt.Errorf("%s: command failed", env)
	}
	trimmed := strings.TrimRight(out, "\r\n")
	if trimmed == "" {
		return "", fmt.Errorf("%s: command produced no output", env)
	}
	return trimmed, nil
}

// subcommandEntry is one row of the subcommand listing.
// The subcommandRegistry table is generated by nix/checks.nix from lib/subcommands.nix.
type subcommandEntry struct {
	name  string // verb name; must match a verbHandlers key exactly
	usage string // bracketed argument synopsis shown after name; empty when the verb takes none
	doc   string // one-line description from lib/subcommands.nix
}

// parseFlags scans args for --flag-name value pairs defined in schemaFlags and
// --<name>-file path pairs defined in secretKnobs.  Matching pairs are injected
// into the process environment via os.Setenv so loadConfig() picks them up
// (flag > document > schema default precedence, ADR 0020 — a flag lands in
// the same env channel as a deprecated ambient knob env var, so it wins for
// the same reason ambient env does).  File flags read the secret value
// from the given path; the value is never logged.
// Unrecognised --flags return an error. Non-flag args and args after "--" are
// returned as-is.
func parseFlags(args []string) ([]string, error) {
	byFlag := make(map[string]*flagEntry, len(schemaFlags)*2)
	for i := range schemaFlags {
		byFlag["--"+schemaFlags[i].flag] = &schemaFlags[i]
		if schemaFlags[i].alias != "" {
			byFlag["--"+schemaFlags[i].alias] = &schemaFlags[i]
		}
	}

	byFileFlag := make(map[string]*secretKnob, len(secretKnobs))
	byCmdFlag := make(map[string]*secretKnob, len(secretKnobs))
	for i := range secretKnobs {
		if secretKnobs[i].fileFlag != "" {
			byFileFlag["--"+secretKnobs[i].fileFlag] = &secretKnobs[i]
		}
		if secretKnobs[i].cmdFlag != "" {
			byCmdFlag["--"+secretKnobs[i].cmdFlag] = &secretKnobs[i]
		}
	}

	// filePaths/cmdStrings collect --<name>-file/-cmd flag arguments during
	// the scan below without acting on them yet, so a conflicting pair can
	// be rejected before either side effect (file read, command exec) runs,
	// regardless of which flag appears first on the command line.
	filePaths := make(map[string]string, len(secretKnobs))
	cmdStrings := make(map[string]string, len(secretKnobs))

	remaining := make([]string, 0, len(args))
	i := 0
	for i < len(args) {
		arg := args[i]
		if arg == "--" {
			remaining = append(remaining, args[i+1:]...)
			break
		}
		if !strings.HasPrefix(arg, "--") {
			remaining = append(remaining, arg)
			i++
			continue
		}
		// Dispatch-only boolean flags: pass through to the verb handler.
		if arg == "--no-build" || arg == "--yes" || arg == "--force" {
			remaining = append(remaining, arg)
			i++
			continue
		}
		if entry, ok := byFlag[arg]; ok {
			i++
			if i >= len(args) {
				return nil, fmt.Errorf("flag %s requires a value", arg)
			}
			if err := os.Setenv(entry.env, args[i]); err != nil {
				return nil, err
			}
			i++
			continue
		}
		if knob, ok := byFileFlag[arg]; ok {
			i++
			if i >= len(args) {
				return nil, fmt.Errorf("flag %s requires a path", arg)
			}
			filePaths[knob.env] = args[i]
			i++
			continue
		}
		if knob, ok := byCmdFlag[arg]; ok {
			i++
			if i >= len(args) {
				return nil, fmt.Errorf("flag %s requires a command", arg)
			}
			cmdStrings[knob.env] = args[i]
			i++
			continue
		}
		return nil, fmt.Errorf("unknown flag: %s", arg)
	}

	for i := range secretKnobs {
		knob := &secretKnobs[i]
		_, hasFileFlag := filePaths[knob.env]
		_, hasCmdFlag := cmdStrings[knob.env]
		if hasFileFlag && hasCmdFlag {
			return nil, fmt.Errorf("--%s and --%s are mutually exclusive", knob.cmdFlag, knob.fileFlag)
		}

		switch {
		case hasCmdFlag:
			value, err := resolveSecretCmd(knob.env, cmdStrings[knob.env])
			if err != nil {
				return nil, err
			}
			if err := os.Setenv(knob.env, value); err != nil {
				return nil, err
			}
		case os.Getenv(knob.env+"_CMD") != "":
			value, err := resolveSecretCmd(knob.env, os.Getenv(knob.env+"_CMD"))
			if err != nil {
				return nil, err
			}
			if err := os.Setenv(knob.env, value); err != nil {
				return nil, err
			}
		case hasFileFlag:
			data, err := os.ReadFile(filePaths[knob.env])
			if err != nil {
				return nil, fmt.Errorf("--%s: cannot read file %s: %w", knob.fileFlag, filePaths[knob.env], err)
			}
			if err := os.Setenv(knob.env, strings.TrimRight(string(data), "\r\n")); err != nil {
				return nil, err
			}
		}
	}

	return remaining, nil
}

// groupOrder is the display order of flag-group headings in the full reference
// (printHelpFull and the man page). Every group used in env-schema.nix must
// appear here, or its flags would silently drop out of the full listing
// (guarded by TestGroupOrder_CoversEverySchemaGroup and launcher-flag-table).
var groupOrder = []string{
	"Issue discovery",
	"Lifecycle labels",
	"Branches & merge",
	"Concurrency & dependency waves",
	"Models",
	"Self-healing & retries",
	"Sandbox & resources",
	"Repository & identity",
	"Prompt & skill iteration",
}

// printSubcommands writes the shared subcommand listing used by both help
// modes, rendered from subcommandRegistry (lib/subcommands.nix) so the
// listing can never hand-drift from the other renderings of the same
// registry (completions, man page).
func printSubcommands(w io.Writer) {
	fmt.Fprintln(w, "Subcommands:")
	for _, e := range subcommandRegistry {
		left := e.name
		if e.usage != "" {
			left += " " + e.usage
		}
		// 42 = len("dispatch [--no-build] [--yes] [issue...]"), the widest
		// name+usage in subcommandRegistry, plus a 2-space gap before doc.
		// TestPrintSubcommands_ExactOutput pins the result; widen this if a
		// future entry's name+usage exceeds that length.
		fmt.Fprintf(w, "  %-42s%s\n", left, e.doc)
	}
}

// printHelp writes the concise usage summary: the tagline, synopsis,
// subcommands, a handful of common flags, and pointers to the full reference
// (man spindrift / --help --all). The exhaustive knob list lives in
// printHelpFull so the default --help stays scannable.
func printHelp(w io.Writer) {
	fmt.Fprintln(w, "spindrift — launch waves of headless Claude Code agents across GitHub issues")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Usage: spindrift [flags] <subcommand> [args]")
	fmt.Fprintln(w)
	printSubcommands(w)
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Common flags:")
	fmt.Fprintln(w, "  --repo-slug owner/repo   target GitHub repository (required unless CODE_FORGE and ISSUE_TRACKER are both local)")
	fmt.Fprintln(w, "  --model NAME             primary implementor model")
	fmt.Fprintln(w, "  --max-parallel N         maximum concurrent agent containers")
	fmt.Fprintln(w, "  --merge-mode MODE        post-green merge policy: immediate | auto | manual")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Full reference (all flags, env vars, and secrets):")
	fmt.Fprintln(w, "  man spindrift            complete manual page")
	fmt.Fprintln(w, "  spindrift --help --all   the same reference in the terminal")
	fmt.Fprintln(w, "  spindrift --version      print version and revision")
}

// printHelpFull writes the exhaustive reference: subcommands, dispatch flags,
// every knob grouped by category (flag > flake setting > default precedence,
// ADR 0020), and the secret env-only / file-flag surface. Reached via
// `spindrift --help --all`.
func printHelpFull(w io.Writer) {
	fmt.Fprintln(w, "spindrift — launch waves of headless Claude Code agents across GitHub issues")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Usage: spindrift [flags] <subcommand> [args]")
	fmt.Fprintln(w)
	printSubcommands(w)
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Dispatch flags:")
	fmt.Fprintln(w, "  --no-build  fail fast if the image is absent instead of building; pair with 'spindrift build' for split build/run flows")
	fmt.Fprintln(w, "  --yes       skip confirmation prompt when dispatching unlabeled issues (alias: --force)")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Flags (flag > flake setting > default precedence; a knob env var still")
	fmt.Fprintln(w, "wins this release but is deprecated and warns — ADR 0020):")

	byGroup := make(map[string][]flagEntry, len(groupOrder))
	for _, e := range schemaFlags {
		byGroup[e.group] = append(byGroup[e.group], e)
	}
	for _, g := range groupOrder {
		entries := byGroup[g]
		if len(entries) == 0 {
			continue
		}
		fmt.Fprintf(w, "\n  %s:\n", g)
		for _, e := range entries {
			dflt := e.dflt
			if dflt == "" {
				dflt = "(none)"
			}
			flagCol := e.flag
			if e.alias != "" {
				flagCol = e.flag + ", --" + e.alias
			}
			fmt.Fprintf(w, "    --%-30s  %-6s  default=%-20s  %s\n",
				flagCol, e.kind, dflt, e.doc)
		}
	}
	if len(secretKnobs) > 0 {
		fmt.Fprintln(w)
		fmt.Fprintln(w, "Env-only (secret; never a value flag):")
		for _, s := range secretKnobs {
			fmt.Fprintf(w, "  %-32s  env-only  %s\n", s.env, s.doc)
		}
		fmt.Fprintln(w)
		fmt.Fprintln(w, "Secret file flags (read value from file; takes precedence over env):")
		for _, s := range secretKnobs {
			if s.fileFlag != "" {
				fmt.Fprintf(w, "  --%-30s  path  %s\n", s.fileFlag, s.doc)
			}
		}
		fmt.Fprintln(w)
		fmt.Fprintln(w, "Secret command flags (fetch value from a command's stdout; sibling <NAME>_CMD")
		fmt.Fprintln(w, "env var; highest precedence — preferred for external-vault sourcing):")
		for _, s := range secretKnobs {
			if s.cmdFlag != "" {
				fmt.Fprintf(w, "  --%-30s  cmd   %s\n", s.cmdFlag, s.doc)
			}
		}
	}
}
