package main

import (
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"
)

// version and revision are injected at build time via -ldflags.
var version = "dev"
var revision = "unknown"

func printVersion(w io.Writer) {
	fmt.Fprintf(w, "spindrift %s (rev %s)\n", version, revision)
}

// dispatchIssueArg extracts the optional issue number from the positional args
// following the "dispatch" verb. Returns the issue number if the first arg is a
// valid positive integer, otherwise returns empty string.
func dispatchIssueArg(args []string) string {
	if len(args) == 0 {
		return ""
	}
	if n, err := strconv.Atoi(args[0]); err == nil && n > 0 {
		return args[0]
	}
	return ""
}

// dispatchIssueArgs extracts all numeric positional args following the "dispatch"
// verb. Returns them in order; returns nil when none are present.
func dispatchIssueArgs(args []string) []string {
	var nums []string
	for _, a := range args {
		if n, err := strconv.Atoi(a); err == nil && n > 0 {
			nums = append(nums, a)
		}
	}
	return nums
}

// dispatchNoBuildArgs extracts the --no-build flag from the args following the
// "dispatch" verb. Returns (true, filtered) when the flag is present, where
// filtered has the flag removed so dispatchIssueArg sees only the issue number.
func dispatchNoBuildArgs(args []string) (noBuild bool, remaining []string) {
	for _, a := range args {
		if a == "--no-build" {
			noBuild = true
		} else {
			remaining = append(remaining, a)
		}
	}
	return
}

// dispatchYesArgs extracts the --yes/--force flag from the args following the
// "dispatch" verb. Returns (true, filtered) when either flag is present.
func dispatchYesArgs(args []string) (yes bool, remaining []string) {
	for _, a := range args {
		if a == "--yes" || a == "--force" {
			yes = true
		} else {
			remaining = append(remaining, a)
		}
	}
	return
}

// flagEntry maps a runtime knob to its CLI flag.
// The schemaFlags table is generated by mkHarness.nix from lib/env-schema.nix.
type flagEntry struct {
	env   string // env-var name (SCREAMING_SNAKE_CASE)
	flag  string // flag name without leading dashes (kebab-case)
	alias string // optional short-form alias without leading dashes; empty when absent
	kind  string // "string" or "int"
	doc   string // one-line description from env-schema.nix
	dflt  string // baked-in default as a string; empty when there is none
	group string // category heading for the full reference (from env-schema.nix)
}

// secretKnob is a knob excluded from the value-flag surface (secret = true in
// the schema).  It has no inline value flag; callers must supply it via the
// environment or via --<fileFlag> (which reads from a file path).
// The secretKnobs table is generated by mkHarness.nix from lib/env-schema.nix.
type secretKnob struct {
	env      string
	doc      string
	fileFlag string // flag name for --<name>-file path variant (kebab-case, no dashes prefix)
}

// parseFlags scans args for --flag-name value pairs defined in schemaFlags and
// --<name>-file path pairs defined in secretKnobs.  Matching pairs are injected
// into the process environment via os.Setenv so loadConfig() picks them up
// (flag > env > baked default precedence).  File flags read the secret value
// from the given path; the value is never logged.
// Unrecognised --flags return an error. Non-flag args and args after "--" are
// returned as-is.
func parseFlags(args []string) ([]string, error) {
	byFlag := make(map[string]*flagEntry, len(schemaFlags)*2)
	for i := range schemaFlags {
		byFlag["--"+schemaFlags[i].flag] = &schemaFlags[i]
		if schemaFlags[i].alias != "" {
			byFlag["--"+schemaFlags[i].alias] = &schemaFlags[i]
		}
	}

	byFileFlag := make(map[string]*secretKnob, len(secretKnobs))
	for i := range secretKnobs {
		if secretKnobs[i].fileFlag != "" {
			byFileFlag["--"+secretKnobs[i].fileFlag] = &secretKnobs[i]
		}
	}

	remaining := make([]string, 0, len(args))
	i := 0
	for i < len(args) {
		arg := args[i]
		if arg == "--" {
			remaining = append(remaining, args[i+1:]...)
			break
		}
		if !strings.HasPrefix(arg, "--") {
			remaining = append(remaining, arg)
			i++
			continue
		}
		// Dispatch-only boolean flags: pass through to the verb handler.
		if arg == "--no-build" || arg == "--yes" || arg == "--force" {
			remaining = append(remaining, arg)
			i++
			continue
		}
		if entry, ok := byFlag[arg]; ok {
			i++
			if i >= len(args) {
				return nil, fmt.Errorf("flag %s requires a value", arg)
			}
			if err := os.Setenv(entry.env, args[i]); err != nil {
				return nil, err
			}
			i++
			continue
		}
		if knob, ok := byFileFlag[arg]; ok {
			i++
			if i >= len(args) {
				return nil, fmt.Errorf("flag %s requires a path", arg)
			}
			path := args[i]
			data, err := os.ReadFile(path)
			if err != nil {
				return nil, fmt.Errorf("%s: cannot read file %s: %w", arg, path, err)
			}
			if err := os.Setenv(knob.env, strings.TrimRight(string(data), "\r\n")); err != nil {
				return nil, err
			}
			i++
			continue
		}
		return nil, fmt.Errorf("unknown flag: %s", arg)
	}
	return remaining, nil
}

// groupOrder is the display order of flag-group headings in the full reference
// (printHelpFull and the man page). Every group used in env-schema.nix must
// appear here, or its flags would silently drop out of the full listing
// (guarded by TestGroupOrder_CoversEverySchemaGroup and launcher-flag-table).
var groupOrder = []string{
	"Issue discovery",
	"Lifecycle labels",
	"Branches & merge",
	"Concurrency & dependency waves",
	"Models",
	"Self-healing & retries",
	"Sandbox & resources",
	"Repository & identity",
	"Prompt & skill iteration",
}

// printSubcommands writes the shared subcommand listing used by both help modes.
func printSubcommands(w io.Writer) {
	fmt.Fprintln(w, "Subcommands:")
	fmt.Fprintln(w, "  dispatch [--no-build] [--yes] [issue...]  fan out agents; an issue list dispatches exactly those (bypasses label/barrier gates)")
	fmt.Fprintln(w, "  preview [issue...]                        dry-run: show what dispatch would pick up, in order")
	fmt.Fprintln(w, "  build                                     realise the agent image without running any agent")
	fmt.Fprintln(w, "  recover <issue>                           run the merge gate for a single issue")
}

// printHelp writes the concise usage summary: the tagline, synopsis,
// subcommands, a handful of common flags, and pointers to the full reference
// (man spindrift / --help --all). The exhaustive knob list lives in
// printHelpFull so the default --help stays scannable.
func printHelp(w io.Writer) {
	fmt.Fprintln(w, "spindrift — fan out headless Claude Code agents across GitHub issues")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Usage: spindrift [flags] <subcommand> [args]")
	fmt.Fprintln(w)
	printSubcommands(w)
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Common flags:")
	fmt.Fprintln(w, "  --repo-slug owner/repo   target GitHub repository (required)")
	fmt.Fprintln(w, "  --model NAME             primary implementor model")
	fmt.Fprintln(w, "  --max-parallel N         maximum concurrent agent containers")
	fmt.Fprintln(w, "  --merge-mode MODE        post-green merge policy: immediate | auto | manual")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Full reference (all flags, env vars, and secrets):")
	fmt.Fprintln(w, "  man spindrift            complete manual page")
	fmt.Fprintln(w, "  spindrift --help --all   the same reference in the terminal")
	fmt.Fprintln(w, "  spindrift --version      print version and revision")
}

// printHelpFull writes the exhaustive reference: subcommands, dispatch flags,
// every knob grouped by category (flag > env > default precedence), and the
// secret env-only / file-flag surface. Reached via `spindrift --help --all`.
func printHelpFull(w io.Writer) {
	fmt.Fprintln(w, "spindrift — fan out headless Claude Code agents across GitHub issues")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Usage: spindrift [flags] <subcommand> [args]")
	fmt.Fprintln(w)
	printSubcommands(w)
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Dispatch flags:")
	fmt.Fprintln(w, "  --no-build  fail fast if the image is absent instead of building; pair with 'spindrift build' for split build/run flows")
	fmt.Fprintln(w, "  --yes       skip confirmation prompt when dispatching unlabeled issues (alias: --force)")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Flags (flag > env > default precedence):")

	byGroup := make(map[string][]flagEntry, len(groupOrder))
	for _, e := range schemaFlags {
		byGroup[e.group] = append(byGroup[e.group], e)
	}
	for _, g := range groupOrder {
		entries := byGroup[g]
		if len(entries) == 0 {
			continue
		}
		fmt.Fprintf(w, "\n  %s:\n", g)
		for _, e := range entries {
			dflt := e.dflt
			if dflt == "" {
				dflt = "(none)"
			}
			flagCol := e.flag
			if e.alias != "" {
				flagCol = e.flag + ", --" + e.alias
			}
			fmt.Fprintf(w, "    --%-30s  %-6s  default=%-20s  %s\n",
				flagCol, e.kind, dflt, e.doc)
		}
	}
	if len(secretKnobs) > 0 {
		fmt.Fprintln(w)
		fmt.Fprintln(w, "Env-only (secret; never a value flag):")
		for _, s := range secretKnobs {
			fmt.Fprintf(w, "  %-32s  env-only  %s\n", s.env, s.doc)
		}
		fmt.Fprintln(w)
		fmt.Fprintln(w, "Secret file flags (read value from file; takes precedence over env):")
		for _, s := range secretKnobs {
			if s.fileFlag != "" {
				fmt.Fprintf(w, "  --%-30s  path  %s\n", s.fileFlag, s.doc)
			}
		}
	}
}
