// Code generated by mkHarness.nix from lib/env-schema.nix. DO NOT EDIT.
package main

// schemaFlags is the flag table derived from lib/env-schema.nix.
// Secret knobs are excluded from schemaFlags; see secretKnobs below.
// Run `nix flake check` after editing lib/env-schema.nix to regenerate.
var schemaFlags = []flagEntry{
	{env: "AUTO_FORMAT", flag: "auto-format", group: "Prompt & skill iteration", kind: "string", doc: "when non-empty, the implementor auto-detects and runs the project's formatter on changed files before each commit; skips silently when no formatter is found", dflt: ""},
	{env: "AUTO_LINT", flag: "auto-lint", group: "Prompt & skill iteration", kind: "string", doc: "when non-empty, the implementor auto-detects and runs the project's linter on changed files before each commit, applying auto-fix then resolving remaining findings; skips silently when no linter is found", dflt: ""},
	{env: "BASE_BRANCH", flag: "base-branch", group: "Branches & merge", kind: "string", doc: "default branch agent PRs merge into", dflt: "main"},
	{env: "BRANCH_PREFIX", flag: "branch-prefix", group: "Branches & merge", kind: "string", doc: "prefix for agent-cut branches", dflt: "agent/issue-"},
	{env: "BWRAP_UNSHARE_NET", flag: "bwrap-unshare-net", group: "Sandbox & resources", kind: "string", doc: "when non-empty, adds --unshare-net to bwrap; requires slirp/pasta for DNS; by default bwrap shares the host network namespace (host-loopback reachable)", dflt: ""},
	{env: "CODE_FORGE", flag: "code-forge", group: "Repository & identity", kind: "string", doc: "code-landing backend: github (open PR, watch CI, merge) or git (push-only to CODE_FORGE_REMOTE_URL; no PR, CI-watch, or merge gate)", dflt: "github"},
	{env: "CODE_FORGE_REMOTE_URL", flag: "code-forge-remote-url", group: "Repository & identity", kind: "string", doc: "plain git remote URL to clone from and push to (self-hosted git, gitea, GitLab-without-MRs, a bare server repo); required when CODE_FORGE=git, unused otherwise", dflt: ""},
	{env: "COMPLETE_LABEL", flag: "complete-label", group: "Lifecycle labels", kind: "string", doc: "label the launcher swaps on when CI reaches green (agent is done; merge is separate)", dflt: "agent-complete"},
	{env: "CONTINUOUS_DISPATCH", flag: "continuous-dispatch", group: "Concurrency & dependency waves", kind: "string", doc: "when non-empty, dispatch runs as a long-running slot-refill loop instead of a single wave (#527): as each Box finishes, the launcher re-discovers the queue and refills the freed slot when the image-freshness probe (#526) reports fresh; a rebuild-needed result stops refilling, lets in-flight Boxes finish, and exits with the new documented code (see README's exit-code table). Off by default; applies to queue discovery only — ISSUE_NUMBER-claimed and selective dispatch ignore it", dflt: ""},
	{env: "DEV_SHELL_NAME", flag: "dev-shell-name", group: "Sandbox & resources", kind: "string", doc: "which devShell to enter; lets a Target expose a lean headless ci shell distinct from a heavy interactive default", dflt: "default"},
	{env: "DEV_SHELL_PROBE_TIMEOUT", flag: "dev-shell-probe-timeout", group: "Sandbox & resources", kind: "int", doc: "seconds before the devShell probe is abandoned and the baked toolchain is used", dflt: "300"},
	{env: "FAILED_LABEL", flag: "failed-label", group: "Lifecycle labels", kind: "string", doc: "label swapped on when the agent box exits non-zero", dflt: "agent-failed"},
	{env: "FILER_MODEL", flag: "filer-model", group: "Models", kind: "string", doc: "filer subagent model tier; empty (default) omits the filer entry from --agents and means the filer is not provisioned at all — setting a model is the opt-in (recommended: claude-haiku-4-5-20251001)", dflt: ""},
	{env: "GIT_USER_EMAIL", flag: "git-user-email", group: "Repository & identity", kind: "string", doc: "commit identity email; falls back to host git config user.email", dflt: ""},
	{env: "GIT_USER_NAME", flag: "git-user-name", group: "Repository & identity", kind: "string", doc: "commit identity name; falls back to host git config user.name", dflt: ""},
	{env: "HOLD_JITTER_SECS", flag: "hold-jitter-secs", group: "Self-healing & retries", kind: "int", doc: "jitter seconds added to 429 hold duration to spread re-dispatch", dflt: "5"},
	{env: "IN_PROGRESS_LABEL", flag: "in-progress-label", group: "Lifecycle labels", kind: "string", doc: "label swapped on from LABEL when an issue enters the queue", dflt: "agent-in-progress"},
	{env: "ISSUE_NUMBER", flag: "issue-number", group: "Issue discovery", alias: "issue", kind: "string", doc: "dispatch only this issue number, bypassing the LABEL query; empty discovers by LABEL", dflt: ""},
	{env: "ISSUE_TRACKER", flag: "issue-tracker", group: "Issue discovery", kind: "string", doc: "IssueTracker backend (ADR 0013): github (gh-exec, default), local (private Markdown + YAML frontmatter files; see LOCAL_ISSUES_DIR), or jira (see JIRA_BASE_URL/JIRA_PROJECT_KEY/JIRA_TOKEN); the Code Forge (PR/CI/merge) stays github regardless", dflt: "github"},
	{env: "JIRA_BASE_URL", flag: "jira-base-url", group: "Repository & identity", kind: "string", doc: "Jira site base URL (e.g. https://yourcompany.atlassian.net); required when ISSUE_TRACKER=jira", dflt: ""},
	{env: "JIRA_EMAIL", flag: "jira-email", group: "Repository & identity", kind: "string", doc: "Jira Cloud account email, paired with JIRA_TOKEN for Basic auth; leave empty for Bearer-token auth (Jira Server/Data Center PATs)", dflt: ""},
	{env: "JIRA_INCLUDE_COMMENTS", flag: "jira-include-comments", group: "Issue discovery", kind: "string", doc: "when non-empty, the Jira adapter appends the issue's comment thread to the description it returns; empty (default) keeps the prompt-injection surface tight", dflt: ""},
	{env: "JIRA_PROJECT_KEY", flag: "jira-project-key", group: "Repository & identity", kind: "string", doc: "Jira project key issues are read from (e.g. ENG); required when ISSUE_TRACKER=jira", dflt: ""},
	{env: "JIRA_STATUS_MAPPING", flag: "jira-status-mapping", group: "Lifecycle labels", kind: "string", doc: "JSON object mapping dispatch states (dispatchable, inProgress, complete, failed) to native Jira status names, e.g. {'inProgress':'In Progress'}; TransitionState performs the matching workflow transition, falling back to swapping the matching lifecycle label when a state is unmapped or its transition is blocked by the project's workflow", dflt: ""},
	{env: "LABEL", flag: "label", group: "Issue discovery", kind: "string", doc: "issues carrying this label are dispatchable (the launch button)", dflt: "ready-for-agent"},
	{env: "LOCAL_ISSUES_DIR", flag: "local-issues-dir", group: "Issue discovery", kind: "string", doc: "directory scanned for issue files when ISSUE_TRACKER=local; keep it git-ignored so breakout issues stay private", dflt: ".spindrift/issues"},
	{env: "MAX_FIX_ATTEMPTS", flag: "max-fix-attempts", group: "Self-healing & retries", kind: "int", doc: "fix-agent passes when CI is genuinely red before marking agent-failed; 0 disables self-healing", dflt: "3"},
	{env: "MAX_JOBS", flag: "max-jobs", group: "Concurrency & dependency waves", kind: "int", doc: "caps the wave size; 0 means uncapped", dflt: "0"},
	{env: "MAX_PARALLEL", flag: "max-parallel", group: "Concurrency & dependency waves", kind: "int", doc: "maximum concurrent agent containers", dflt: "3"},
	{env: "MAX_REBASE_ATTEMPTS", flag: "max-rebase-attempts", group: "Self-healing & retries", kind: "int", doc: "rebase-and-retry passes when a green PR conflicts with the base after a sibling merge; 0 disables rebase retries", dflt: "3"},
	{env: "MEMORY_LIMIT", flag: "memory-limit", group: "Sandbox & resources", kind: "string", doc: "max memory per agent container (--memory); empty string disables the limit", dflt: "5g"},
	{env: "MERGE_GUARD_PATHS", flag: "merge-guard-paths", group: "Branches & merge", kind: "string", doc: "comma-separated globs matched against every changed path (added, modified, deleted); a hit downgrades the merge to manual regardless of MERGE_MODE and posts a PR comment naming the match; empty disables the guard (github Code Forge merge path only)", dflt: ".github/**,**/CLAUDE.md,**/AGENTS.md,.claude/**,.opencode/**"},
	{env: "MERGE_MODE", flag: "merge-mode", group: "Branches & merge", kind: "string", doc: "post-green merge policy: immediate (merge on green), auto (enqueue GitHub native auto-merge; repo must have Allow auto-merge enabled), manual (leave PR open for human approval)", dflt: "manual"},
	{env: "MERGE_POLL_INTERVAL", flag: "merge-poll-interval", group: "Branches & merge", kind: "int", doc: "seconds between merge-gate poll iterations", dflt: "30"},
	{env: "MERGE_POLL_TIMEOUT", flag: "merge-poll-timeout", group: "Branches & merge", kind: "int", doc: "total seconds to wait for CI green before abandoning the merge attempt", dflt: "1800"},
	{env: "MODEL", flag: "model", group: "Models", kind: "string", doc: "primary (implementor) Claude model for the agent (zero-rebuild runtime switch)", dflt: "claude-sonnet-5"},
	{env: "OVERLAP_GATE", flag: "overlap-gate", group: "Concurrency & dependency waves", kind: "string", doc: "declared ## Touches overlap policy: defer (hold a Dispatchable issue whose declared touch-set intersects an InProgress issue's, retrying once the collider completes), off (disable the check)", dflt: "defer"},
	{env: "PIDS_LIMIT", flag: "pids-limit", group: "Sandbox & resources", kind: "string", doc: "max processes per agent container (--pids-limit); empty string disables the limit", dflt: "512"},
	{env: "PODMAN_NETWORK", flag: "podman-network", group: "Sandbox & resources", kind: "string", doc: "--network value for podman run; empty applies no flag (podman NAT default); set to 'pasta' to restrict egress", dflt: ""},
	{env: "REPO_SLUG", flag: "repo-slug", group: "Repository & identity", kind: "string", doc: "target GitHub repository the agents work on", dflt: ""},
	{env: "REVIEW_MODEL", flag: "review-model", group: "Models", kind: "string", doc: "reviewer subagent model tier; empty omits the reviewer entry from --agents; the flag itself is omitted only when no subagent model is set", dflt: "claude-opus-4-8"},
	{env: "SCOUT_MODEL", flag: "scout-model", group: "Models", kind: "string", doc: "scout subagent model tier; empty omits the scout entry from --agents; the flag itself is omitted only when no subagent model is set", dflt: "claude-haiku-4-5-20251001"},
	{env: "SPINDRIFT_PROMPT_DIR", flag: "spindrift-prompt-dir", group: "Prompt & skill iteration", kind: "string", doc: "host directory mounted over /agent/prompts for zero-rebuild prompt iteration", dflt: ""},
	{env: "SPINDRIFT_SKILLS_DIR", flag: "spindrift-skills-dir", group: "Prompt & skill iteration", kind: "string", doc: "host directory mounted read-only over /home/agent/.claude/skills so the headless agent can load operator-provided skills", dflt: ""},
	{env: "TRANSIENT_BACKOFF_SECS", flag: "transient-backoff-secs", group: "Self-healing & retries", kind: "int", doc: "base backoff seconds per retry for 529/overloaded and network transients", dflt: "30"},
	{env: "TRANSIENT_RETRY_MAX", flag: "transient-retry-max", group: "Self-healing & retries", kind: "int", doc: "max retries for transient exits (529/network backoff; consecutive 429 holds)", dflt: "3"},
}

// secretKnobs lists secret knobs that have no value flag.
// Callers must supply these via the environment or via --<fileFlag> path flag.
var secretKnobs = []secretKnob{
	{env: "ANTHROPIC_API_KEY", doc: "Anthropic API key; set this or CLAUDE_CODE_OAUTH_TOKEN", fileFlag: "anthropic-api-key-file"},
	{env: "CLAUDE_CODE_OAUTH_TOKEN", doc: "Claude Code OAuth token (run 'claude setup-token'); set this or ANTHROPIC_API_KEY", fileFlag: "claude-code-oauth-token-file"},
	{env: "GH_TOKEN", doc: "fine-grained PAT scoped to the target repo — Contents/PR/Issues/Metadata RW", fileFlag: "gh-token-file"},
	{env: "JIRA_TOKEN", doc: "Jira API token (Cloud: paired with JIRA_EMAIL for Basic auth; Server/Data Center: used alone as a Bearer PAT); required when ISSUE_TRACKER=jira", fileFlag: "jira-token-file"},
}
