// Code generated by mkHarness.nix from lib/env-schema.nix. DO NOT EDIT.
package main

// schemaFlags is the flag table derived from lib/env-schema.nix.
// Secret knobs are excluded from schemaFlags; see secretKnobs below.
// Run `nix flake check` after editing lib/env-schema.nix to regenerate.
var schemaFlags = []flagEntry{
	{env: "BASE_BRANCH", flag: "base-branch", group: "Branches & merge", kind: "string", doc: "default branch agent PRs merge into", dflt: "main"},
	{env: "BRANCH_PREFIX", flag: "branch-prefix", group: "Branches & merge", kind: "string", doc: "prefix for agent-cut branches", dflt: "agent/issue-"},
	{env: "BWRAP_UNSHARE_NET", flag: "bwrap-unshare-net", group: "Sandbox & resources", kind: "string", doc: "when non-empty, adds --unshare-net to bwrap; requires slirp/pasta for DNS; by default bwrap shares the host network namespace (host-loopback reachable)", dflt: ""},
	{env: "COMPLETE_LABEL", flag: "complete-label", group: "Lifecycle labels", kind: "string", doc: "label the launcher swaps on when CI reaches green (agent is done; merge is separate)", dflt: "agent-complete"},
	{env: "DEPS_POLL_SECS", flag: "deps-poll-secs", group: "Concurrency & dependency waves", kind: "int", doc: "seconds between dependency-wave poll iterations", dflt: "30"},
	{env: "DEPS_WAIT_SECS", flag: "deps-wait-secs", group: "Concurrency & dependency waves", kind: "int", doc: "total seconds to wait for dependency-wave completion before aborting", dflt: "7200"},
	{env: "DEV_SHELL_PROBE_TIMEOUT", flag: "dev-shell-probe-timeout", group: "Sandbox & resources", kind: "int", doc: "seconds before the devShell probe is abandoned and the baked toolchain is used", dflt: "300"},
	{env: "FAILED_LABEL", flag: "failed-label", group: "Lifecycle labels", kind: "string", doc: "label swapped on when the agent box exits non-zero", dflt: "agent-failed"},
	{env: "GIT_USER_EMAIL", flag: "git-user-email", group: "Repository & identity", kind: "string", doc: "commit identity email; falls back to host git config user.email", dflt: ""},
	{env: "GIT_USER_NAME", flag: "git-user-name", group: "Repository & identity", kind: "string", doc: "commit identity name; falls back to host git config user.name", dflt: ""},
	{env: "HOLD_JITTER_SECS", flag: "hold-jitter-secs", group: "Self-healing & retries", kind: "int", doc: "jitter seconds added to 429 hold duration to spread re-dispatch", dflt: "5"},
	{env: "IN_PROGRESS_LABEL", flag: "in-progress-label", group: "Lifecycle labels", kind: "string", doc: "label swapped on from LABEL when an issue enters the queue", dflt: "agent-in-progress"},
	{env: "ISSUE_NUMBER", flag: "issue-number", group: "Issue discovery", alias: "issue", kind: "string", doc: "dispatch only this issue number, bypassing the LABEL query; empty discovers by LABEL", dflt: ""},
	{env: "LABEL", flag: "label", group: "Issue discovery", kind: "string", doc: "issues carrying this label are dispatchable (the launch button)", dflt: "ready-for-agent"},
	{env: "MAX_FIX_ATTEMPTS", flag: "max-fix-attempts", group: "Self-healing & retries", kind: "int", doc: "fix-agent passes when CI is genuinely red before marking agent-failed; 0 disables self-healing", dflt: "3"},
	{env: "MAX_JOBS", flag: "max-jobs", group: "Concurrency & dependency waves", kind: "int", doc: "dependency-wave concurrency cap; 0 means unlimited", dflt: "0"},
	{env: "MAX_PARALLEL", flag: "max-parallel", group: "Concurrency & dependency waves", kind: "int", doc: "maximum concurrent agent containers", dflt: "3"},
	{env: "MAX_REBASE_ATTEMPTS", flag: "max-rebase-attempts", group: "Self-healing & retries", kind: "int", doc: "rebase-and-retry passes when a green PR conflicts with the base after a sibling merge; 0 disables rebase retries", dflt: "3"},
	{env: "MEMORY_LIMIT", flag: "memory-limit", group: "Sandbox & resources", kind: "string", doc: "max memory per agent container (--memory); empty string disables the limit", dflt: "4g"},
	{env: "MERGE_MODE", flag: "merge-mode", group: "Branches & merge", kind: "string", doc: "post-green merge policy: immediate (merge on green), auto (enqueue GitHub native auto-merge; repo must have Allow auto-merge enabled), manual (leave PR open for human approval)", dflt: "manual"},
	{env: "MERGE_POLL_INTERVAL", flag: "merge-poll-interval", group: "Branches & merge", kind: "int", doc: "seconds between merge-gate poll iterations", dflt: "30"},
	{env: "MERGE_POLL_TIMEOUT", flag: "merge-poll-timeout", group: "Branches & merge", kind: "int", doc: "total seconds to wait for CI green before abandoning the merge attempt", dflt: "1800"},
	{env: "MODEL", flag: "model", group: "Models", kind: "string", doc: "primary (implementor) Claude model for the agent (zero-rebuild runtime switch)", dflt: "claude-sonnet-4-6"},
	{env: "PIDS_LIMIT", flag: "pids-limit", group: "Sandbox & resources", kind: "string", doc: "max processes per agent container (--pids-limit); empty string disables the limit", dflt: "512"},
	{env: "PODMAN_NETWORK", flag: "podman-network", group: "Sandbox & resources", kind: "string", doc: "--network value for podman run; empty applies no flag (podman NAT default); set to 'pasta' to restrict egress", dflt: ""},
	{env: "REPO_SLUG", flag: "repo-slug", group: "Repository & identity", kind: "string", doc: "target GitHub repository the agents work on", dflt: ""},
	{env: "REVIEW_MODEL", flag: "review-model", group: "Models", kind: "string", doc: "reviewer subagent model tier; empty omits the scout/reviewer --agents from the claude invocation", dflt: "claude-opus-4-8"},
	{env: "SCOUT_MODEL", flag: "scout-model", group: "Models", kind: "string", doc: "scout subagent model tier; empty omits the scout/reviewer --agents from the claude invocation", dflt: "claude-haiku-4-5-20251001"},
	{env: "SPINDRIFT_PROMPT_DIR", flag: "spindrift-prompt-dir", group: "Prompt & skill iteration", kind: "string", doc: "host directory mounted over /agent/prompts for zero-rebuild prompt iteration", dflt: ""},
	{env: "SPINDRIFT_SKILLS_DIR", flag: "spindrift-skills-dir", group: "Prompt & skill iteration", kind: "string", doc: "host directory mounted read-only over /home/agent/.claude/skills so the headless agent can load operator-provided skills", dflt: ""},
	{env: "TRANSIENT_BACKOFF_SECS", flag: "transient-backoff-secs", group: "Self-healing & retries", kind: "int", doc: "base backoff seconds per retry for 529/overloaded and network transients", dflt: "30"},
	{env: "TRANSIENT_RETRY_MAX", flag: "transient-retry-max", group: "Self-healing & retries", kind: "int", doc: "max retries for transient exits (529/network backoff; consecutive 429 holds)", dflt: "3"},
}

// secretKnobs lists secret knobs that have no value flag.
// Callers must supply these via the environment or via --<fileFlag> path flag.
var secretKnobs = []secretKnob{
	{env: "ANTHROPIC_API_KEY", doc: "Anthropic API key; set this or CLAUDE_CODE_OAUTH_TOKEN", fileFlag: "anthropic-api-key-file"},
	{env: "CLAUDE_CODE_OAUTH_TOKEN", doc: "Claude Code OAuth token (run 'claude setup-token'); set this or ANTHROPIC_API_KEY", fileFlag: "claude-code-oauth-token-file"},
	{env: "GH_TOKEN", doc: "fine-grained PAT scoped to the target repo — Contents/PR/Issues/Metadata RW", fileFlag: "gh-token-file"},
}
