// Code generated by mkHarness.nix from lib/env-schema.nix. DO NOT EDIT.
package main

// schemaFlags is the flag table derived from lib/env-schema.nix.
// Secret knobs (GH_TOKEN, CLAUDE_CODE_OAUTH_TOKEN, ANTHROPIC_API_KEY) are excluded.
// Run `nix flake check` after editing lib/env-schema.nix to regenerate.
var schemaFlags = []flagEntry{
	{env: "BARRIER_LABEL", flag: "barrier-label", kind: "string"},
	{env: "BASE_BRANCH", flag: "base-branch", kind: "string"},
	{env: "BRANCH_PREFIX", flag: "branch-prefix", kind: "string"},
	{env: "BWRAP_UNSHARE_NET", flag: "bwrap-unshare-net", kind: "string"},
	{env: "COMPLETE_LABEL", flag: "complete-label", kind: "string"},
	{env: "DEPS_POLL_SECS", flag: "deps-poll-secs", kind: "int"},
	{env: "DEPS_WAIT_SECS", flag: "deps-wait-secs", kind: "int"},
	{env: "DEV_SHELL_PROBE_TIMEOUT", flag: "dev-shell-probe-timeout", kind: "int"},
	{env: "FAILED_LABEL", flag: "failed-label", kind: "string"},
	{env: "GIT_USER_EMAIL", flag: "git-user-email", kind: "string"},
	{env: "GIT_USER_NAME", flag: "git-user-name", kind: "string"},
	{env: "HOLD_JITTER_SECS", flag: "hold-jitter-secs", kind: "int"},
	{env: "IN_PROGRESS_LABEL", flag: "in-progress-label", kind: "string"},
	{env: "ISSUE_NUMBER", flag: "issue-number", kind: "string"},
	{env: "LABEL", flag: "label", kind: "string"},
	{env: "MAX_FIX_ATTEMPTS", flag: "max-fix-attempts", kind: "int"},
	{env: "MAX_JOBS", flag: "max-jobs", kind: "int"},
	{env: "MAX_PARALLEL", flag: "max-parallel", kind: "int"},
	{env: "MAX_REBASE_ATTEMPTS", flag: "max-rebase-attempts", kind: "int"},
	{env: "MEMORY_LIMIT", flag: "memory-limit", kind: "string"},
	{env: "MERGE_POLL_INTERVAL", flag: "merge-poll-interval", kind: "int"},
	{env: "MERGE_POLL_TIMEOUT", flag: "merge-poll-timeout", kind: "int"},
	{env: "MODEL", flag: "model", kind: "string"},
	{env: "PIDS_LIMIT", flag: "pids-limit", kind: "string"},
	{env: "PODMAN_NETWORK", flag: "podman-network", kind: "string"},
	{env: "REPO_SLUG", flag: "repo-slug", kind: "string"},
	{env: "REVIEW_MODEL", flag: "review-model", kind: "string"},
	{env: "SCOUT_MODEL", flag: "scout-model", kind: "string"},
	{env: "SPINDRIFT_PROMPT_DIR", flag: "spindrift-prompt-dir", kind: "string"},
	{env: "SPINDRIFT_SKILLS_DIR", flag: "spindrift-skills-dir", kind: "string"},
	{env: "TRANSIENT_BACKOFF_SECS", flag: "transient-backoff-secs", kind: "int"},
	{env: "TRANSIENT_RETRY_MAX", flag: "transient-retry-max", kind: "int"},
}
