package main

import (
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// ast.IsGenerated (and the gopls/linter tooling built on it) only recognizes a
// file as generated when one line matches exactly `^// Code generated .* DO
// NOT EDIT\.$` -- a header split across two lines never matches, silently
// opting the file out of that tooling. Every *_gen.go file must pass; a
// *_gen_test.go file only when it carries a "Code generated" marker, since some
// are hand-written tests that merely pin a sibling generated file's output,
// not generated files themselves, and never claim to be one.
func TestGeneratedFilesAreRecognizedByAstIsGenerated(t *testing.T) {
	err := filepath.WalkDir(".", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		name := d.Name()
		if !strings.HasSuffix(name, "_gen.go") && !strings.HasSuffix(name, "_gen_test.go") {
			return nil
		}
		src, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if strings.HasSuffix(name, "_gen_test.go") && !strings.Contains(string(src), "Code generated") {
			return nil
		}
		fset := token.NewFileSet()
		f, err := parser.ParseFile(fset, path, src, parser.ParseComments|parser.PackageClauseOnly)
		if err != nil {
			t.Errorf("%s: parse: %v", path, err)
			return nil
		}
		if !ast.IsGenerated(f) {
			t.Errorf("%s: not recognized as generated by ast.IsGenerated (header must be a single `// Code generated ... DO NOT EDIT.` line)", path)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk: %v", err)
	}
}
