// Code generated by nix/regen.nix from lib/env-schema.nix. DO NOT EDIT.
package main

import "os"

// schemaConfig is the generated counterpart to config's schema-derived
// members (issue #2364, #2365): one field per host-config schema member
// (lib/env-schema.nix — not secret and not boxEnvOnly, or hostConfig
// overridden). Embedded by value in config so a copy-and-mutate helper
// like applyDispatchKind can never alias the caller's config through
// this struct.
type schemaConfig struct {
	anthropicAPIKey              string
	baseBranch                   string
	boxForgeAndIssueAccess       string
	branchPrefix                 string
	bwrapUnshareNet              bool
	claudeOAuthToken             string
	codeForge                    string
	codeForgeAccumulationRepoDir string
	codeForgeRemoteURL           string
	completeLabel                string
	continuousDispatch           bool
	failedLabel                  string
	forgejoBaseURL               string
	forgejoToken                 string
	ghToken                      string
	ghTokenRefreshFile           string
	gitUserEmail                 string
	gitUserName                  string
	holdJitterSecs               int
	inProgressLabel              string
	issueNumber                  string
	issueTracker                 string
	jiraBaseURL                  string
	jiraEmail                    string
	jiraIncludeComments          bool
	jiraProjectKey               string
	jiraStatusMapping            string
	jiraToken                    string
	label                        string
	localIssuesDir               string
	maxBudgetTokens              int
	maxBudgetUSD                 float64
	maxFixAttempts               int
	maxJobs                      int
	maxParallel                  int
	maxRebaseAttempts            int
	memoryLimit                  string
	mergeGuardPaths              string
	mergeMethod                  string
	mergeMode                    string
	mergePollInterval            int
	mergePollTimeout             int
	model                        string
	opencodeAuthContent          string
	overlapGate                  string
	pidsLimit                    string
	podmanNetwork                string
	preflightStaleBase           bool
	repoSlug                     string
	researchVerdicts             string
	spindriftPromptDir           string
	spindriftSkillsDir           string
	syncMethod                   string
	transientBackoffSecs         int
	transientRetryMax            int
}

// loadSchemaConfig reads schemaConfig's fields from the environment.
// hostDerived members get a struct field above but no loader line here
// — their loader is hand-written elsewhere (e.g. gitIdentityField).
// Secret members read the environment directly, never through the
// schema-default helper (a document-first path would open a
// Launcher-input secret-injection channel that does not exist today).
// Regenerate with `nix run .#regen` after editing lib/env-schema.nix.
func loadSchemaConfig() schemaConfig {
	return schemaConfig{
		anthropicAPIKey:        os.Getenv("ANTHROPIC_API_KEY"),
		baseBranch:             getenvSchema("BASE_BRANCH"),
		boxForgeAndIssueAccess: getenvSchema("BOX_FORGE_AND_ISSUE_ACCESS"),
		branchPrefix:           getenvSchema("BRANCH_PREFIX"),
		bwrapUnshareNet:        getenvSchema("BWRAP_UNSHARE_NET") != "",
		claudeOAuthToken:       os.Getenv("CLAUDE_CODE_OAUTH_TOKEN"),
		codeForge:              getenvSchema("CODE_FORGE"),
		codeForgeRemoteURL:     getenvSchema("CODE_FORGE_REMOTE_URL"),
		completeLabel:          getenvSchema("COMPLETE_LABEL"),
		continuousDispatch:     getenvSchema("CONTINUOUS_DISPATCH") != "",
		failedLabel:            getenvSchema("FAILED_LABEL"),
		forgejoBaseURL:         getenvSchema("FORGEJO_BASE_URL"),
		forgejoToken:           os.Getenv("FORGEJO_TOKEN"),
		ghToken:                os.Getenv("GH_TOKEN"),
		ghTokenRefreshFile:     getenvSchema("GH_TOKEN_REFRESH_FILE"),
		holdJitterSecs:         atoiNonnegSchema("HOLD_JITTER_SECS"),
		inProgressLabel:        getenvSchema("IN_PROGRESS_LABEL"),
		issueNumber:            getenvSchema("ISSUE_NUMBER"),
		issueTracker:           getenvSchema("ISSUE_TRACKER"),
		jiraBaseURL:            getenvSchema("JIRA_BASE_URL"),
		jiraEmail:              getenvSchema("JIRA_EMAIL"),
		jiraIncludeComments:    getenvSchema("JIRA_INCLUDE_COMMENTS") != "",
		jiraProjectKey:         getenvSchema("JIRA_PROJECT_KEY"),
		jiraStatusMapping:      getenvSchema("JIRA_STATUS_MAPPING"),
		jiraToken:              os.Getenv("JIRA_TOKEN"),
		label:                  getenvSchema("LABEL"),
		localIssuesDir:         getenvSchema("LOCAL_ISSUES_DIR"),
		maxBudgetTokens:        atoiNonnegSchema("MAX_BUDGET_TOKENS"),
		maxBudgetUSD:           floatNonnegSchema("MAX_BUDGET_USD"),
		maxFixAttempts:         atoiNonnegSchema("MAX_FIX_ATTEMPTS"),
		maxJobs:                atoiNonnegSchema("MAX_JOBS"),
		maxParallel:            atoiSchema("MAX_PARALLEL"),
		maxRebaseAttempts:      atoiNonnegSchema("MAX_REBASE_ATTEMPTS"),
		memoryLimit:            getenvSchema("MEMORY_LIMIT"),
		mergeGuardPaths:        getenvSchema("MERGE_GUARD_PATHS"),
		mergeMethod:            getenvSchema("MERGE_METHOD"),
		mergeMode:              getenvSchema("MERGE_MODE"),
		mergePollInterval:      atoiNonnegSchema("MERGE_POLL_INTERVAL"),
		mergePollTimeout:       atoiNonnegSchema("MERGE_POLL_TIMEOUT"),
		model:                  getenvSchema("MODEL"),
		opencodeAuthContent:    os.Getenv("OPENCODE_AUTH_CONTENT"),
		overlapGate:            getenvSchema("OVERLAP_GATE"),
		pidsLimit:              getenvSchema("PIDS_LIMIT"),
		podmanNetwork:          getenvSchema("PODMAN_NETWORK"),
		preflightStaleBase:     getenvSchema("PREFLIGHT_STALE_BASE") != "",
		repoSlug:               getenvSchema("REPO_SLUG"),
		researchVerdicts:       getenvSchema("RESEARCH_VERDICTS"),
		spindriftPromptDir:     getenvSchema("SPINDRIFT_PROMPT_DIR"),
		spindriftSkillsDir:     getenvSchema("SPINDRIFT_SKILLS_DIR"),
		syncMethod:             getenvSchema("SYNC_METHOD"),
		transientBackoffSecs:   atoiSchema("TRANSIENT_BACKOFF_SECS"),
		transientRetryMax:      atoiSchema("TRANSIENT_RETRY_MAX"),
	}
}
