// Code generated by nix/regen.nix from lib/subcommands.nix. DO NOT EDIT.
package main

// subcommandRegistry is the subcommand table derived from lib/subcommands.nix.
// Regenerate with `nix run .#regen` after editing lib/subcommands.nix.
var subcommandRegistry = []subcommandEntry{
	{name: "console", usage: "", doc: "browse the open backlog interactively (read-only)"},
	{name: "dispatch", usage: "[--no-build] [--yes] [issue...]", doc: "dispatch agents in waves; an issue list dispatches exactly those (bypasses label/barrier gates)"},
	{name: "research", usage: "[--no-build] [--yes] [issue...]", doc: "advise-only research dispatch: drains agent-research (or an issue list) and posts a verdict comment; never merges, never promotes"},
	{name: "preview", usage: "[issue...]", doc: "dry-run: show what dispatch would pick up, in order"},
	{name: "build", usage: "", doc: "realize the agent image without running any agent"},
	{name: "recover", usage: "<issue>", doc: "run the merge gate for a single issue"},
	{name: "doctor", usage: "", doc: "check forge credentials, repository connectivity, and label presence (triage fatal, research advisory)"},
	{name: "reconcile", usage: "", doc: "local-tracker bookkeeping sweep: close issues whose recorded landing PR merged (no-op on github/jira)"},
}
