# The one marker-splice and drift-comparison implementation for every check
# that compares a committed file's BEGIN/END-marker-delimited span against
# generated Nix source of truth (issue #2949). nix/checks/schema-drift.nix,
# nix/checks/baked-skills.nix, and nix/regen.nix import this instead of
# hand-mirroring three copies that could drift apart.

# Marker convention (matches lib/documented-facts.nix and
# lib/documented-fact-shape.nix): beginMarker carries its own trailing "\n",
# endMarker carries none.
{ pkgs }:
rec {
  # Isolates the text strictly between a literal begin/end marker line pair
  # inside docSrc, else throws naming docPath and blockName. escapeRegex is
  # required because builtins.split reads its pattern as a POSIX extended
  # regex: a marker holding ".", "(", or "*" would otherwise mis-split
  # instead of matching itself literally (issue #2948).
  splitMarkedBlock =
    {
      blockName,
      beginMarker,
      endMarker,
      docSrc,
      docPath,
    }:
    let
      inherit (pkgs.lib) escapeRegex;
      afterBegin =
        let
          parts = builtins.split (escapeRegex beginMarker) docSrc;
        in
        if builtins.length parts >= 3 then
          builtins.elemAt parts 2
        else
          throw "${docPath}: BEGIN GENERATED ${blockName} marker not found";
      committed =
        let
          parts = builtins.split (escapeRegex endMarker) afterBegin;
        in
        if builtins.length parts >= 3 then
          builtins.elemAt parts 0
        else
          throw "${docPath}: END GENERATED ${blockName} marker not found";
    in
    committed;

  assertMarkedBlockOk =
    {
      blockName,
      sourceDesc,
      beginMarker,
      endMarker,
      docSrc,
      generated,
      docPath,
    }:
    let
      inherit (pkgs.lib) assertMsg;
      committed = splitMarkedBlock {
        inherit
          blockName
          beginMarker
          endMarker
          docSrc
          docPath
          ;
      };
    in
    assert assertMsg (committed == generated) ''
      ${docPath} generated ${blockName} sub-block is out of sync with ${sourceDesc} — regenerate it with `nix run .#regen`
        got:  ${committed}
        want: ${generated}'';
    docSrc;

  # The awk keeps both marker lines and replaces only the text between them.
  spliceShellFn = ''
    splice() {
      local committed="$1" beginMarker="$2" endMarker="$3" rawfile="$4" outfile="$5"
      awk -v begin="$beginMarker" -v end="$endMarker" -v rawfile="$rawfile" '
        BEGIN { while ((getline line < rawfile) > 0) content = content line "\n" }
        $0 == begin { print; printf "%s", content; skip=1; next }
        $0 == end { skip=0 }
        skip { next }
        { print }
      ' "$committed" > "$outfile"
    }
  '';

  # Diffs a spliced reconstruction rather than the raw generated string: a
  # formatter may reflow the whole surrounding construct (gofmt aligning a Go
  # const block), so the committed span never matches generated byte for byte.
  assertSplicedSpanOk =
    {
      name,
      file,
      blockName,
      sourceDesc,
      beginMarker,
      endMarker,
      generated,
      # When true, runs `gofmt -w` over the reconstruction and folds pkgs.go
      # into nativeBuildInputs, since every call site that needs one wants both.
      gofmt ? false,
      nativeBuildInputs ? [ ],
      # Inverts the final diff: the build passes only when the reconstruction
      # does NOT match the committed file. Lets documented-fact-guard drive
      # this function's real rejection path against a synthetic drift instead
      # of only its happy path (issue #2949 review finding).
      expectMismatch ? false,
    }:
    let
      inherit (pkgs.lib) removeSuffix;
      raw = pkgs.writeText "${name}.raw" generated;
      beginLine = removeSuffix "\n" beginMarker;
      markersPresent = splitMarkedBlock {
        inherit blockName beginMarker endMarker;
        docSrc = builtins.readFile file;
        docPath = toString file;
      };
      postProcessStep = if gofmt then "gofmt -w reconstructed" else "";
      effectiveNativeBuildInputs = nativeBuildInputs ++ (if gofmt then [ pkgs.go ] else [ ]);
      diffStep =
        if expectMismatch then
          ''
            if diff reconstructed "$committed" >/dev/null; then
              echo "${name}: expected the reconstructed span to differ from the committed file (synthetic drift), but it matched -- assertSplicedSpanOk's rejection path is not actually catching drift" >&2
              exit 1
            else
              touch $out
            fi
          ''
        else
          ''
            diff reconstructed "$committed" \
              || { echo "${toString file} generated ${blockName} span is out of sync with ${sourceDesc} -- regenerate it with \`nix run .#regen\`" >&2; exit 1; }
            touch $out
          '';
    in
    # Forcing markersPresent fails a missing marker at eval time. Otherwise the
    # awk splice falls through silently and the diff below reports no drift.
    builtins.seq markersPresent (
      pkgs.runCommand name
        {
          nativeBuildInputs = effectiveNativeBuildInputs;
          committed = file;
          inherit raw;
          beginMarker = beginLine;
          inherit endMarker;
        }
        ''
          ${spliceShellFn}
          splice "$committed" "$beginMarker" "$endMarker" "$raw" reconstructed
          ${postProcessStep}
          ${diffStep}
        ''
    );
}
