# The engine. A pure function a Consumer flake calls with its own locked
# `nixpkgs` input and `system`; returns the agent image plus nix-built `build`
# and `run` commands (as both `packages.*` and `apps.*`).
#
# Takes the locked *input* rather than a pre-built `pkgs` so it can map a darwin
# `system` to its Linux twin and re-instantiate for the OCI image, keeping the
# agent's toolchain and the Consumer's dev shell from one pin (ADR 0002). The
# image is target-agnostic: REPO_SLUG, auth, and commit identity stay runtime
# env, never Nix options (ADR 0001).
{
  nixpkgs,
  system,
  overlays ? [ ],
  config ? { },
  # Project-specific tools baked into the image on top of the harness plumbing,
  # as a function of the (Linux) pkgs. This is the language-toolchain surface:
  # the Consumer supplies its own compiler and build tools here.
  packages ? (_pkgs: [ ]),
  # Optional shell snippet the entrypoint runs after cloning, to warm any
  # caches the toolchain wants (e.g. a fetch of pinned dependencies). Baked
  # into the image; default is a no-op.
  prefetch ? "",
  # The agent prompt template, a Consumer-owned artifact (it is mutated per
  # project). Rendered to a store path and mounted into the container at
  # runtime — NOT baked into the image — so it can be re-pointed via
  # SPINDRIFT_PROMPT_DIR with zero rebuilds (see scripts/run.sh). The default
  # is the scaffolded issue-prompt.md, a working starting point out of the box.
  # The entrypoint substitutes the per-issue variables into it at run time.
  prompt ? builtins.readFile ../templates/default/prompts/issue-prompt.md,
  # Non-secret run configuration baked into the generated `run` command as its
  # built-in defaults. A matching env var (LABEL/BASE_BRANCH/MAX_PARALLEL/
  # BRANCH_PREFIX) still wins at runtime, so one built command can be
  # re-pointed without a rebuild.
  defaults ? { },
  # Container runtime the launcher commands drive: "podman" (default) or
  # "docker". Baked in — it selects which binary `build`/`run` invoke for image
  # existence checks, load, and run.
  runtime ? "podman",
  # The Nix container image `build` uses as a fallback Linux builder when the
  # host can't realise the Linux image itself (the stock-mac case). Fully
  # qualified so podman resolves it without a default-registry assumption.
  nixBuilderImage ? "docker.io/nixos/nix:latest",
}:
let
  # OCI images are Linux-only. Map the Consumer's (possibly darwin) system to
  # its Linux twin for the image.
  linuxSystem =
    {
      "aarch64-darwin" = "aarch64-linux";
      "x86_64-darwin" = "x86_64-linux";
      "aarch64-linux" = "aarch64-linux";
      "x86_64-linux" = "x86_64-linux";
    }
    .${system};

  mergedConfig = {
    allowUnfree = true;
  }
  // config;

  # Image toolset: the Consumer's locked nixpkgs, re-instantiated for Linux.
  pkgs = import nixpkgs {
    system = linuxSystem;
    inherit overlays;
    config = mergedConfig;
  };

  # Host toolset: the launcher commands run on the Consumer's own system. Takes
  # the same overlays as the image so the tools pinned into the launchers
  # (gh/git/coreutils via runtimeInputs) can be overridden consistently.
  hostPkgs = import nixpkgs {
    inherit system overlays;
    config = mergedConfig;
  };

  inherit (pkgs) lib;

  # Drop a leading `#!...` line so a complete, standalone-runnable script can be
  # fed to writeShellApplication as its body (it supplies its own shebang).
  stripShebang =
    text:
    let
      lines = lib.splitString "\n" text;
    in
    if lines != [ ] && lib.hasPrefix "#!" (builtins.head lines) then
      lib.concatStringsSep "\n" (builtins.tail lines)
    else
      text;

  # Built-in run defaults; the Consumer's `defaults` override them per key, and a
  # matching env var overrides those again at runtime (see scripts/run.sh).
  mergedDefaults = {
    label = "ready-for-agent";
    baseBranch = "main";
    maxParallel = 3;
    branchPrefix = "agent/issue-";
  }
  // defaults;

  # Plumbing every agent needs regardless of language: a shell, the VCS + GitHub
  # CLIs, Claude Code, CA certs, and the unix tools the entrypoint relies on.
  harnessPackages = with pkgs; [
    bashInteractive
    coreutils
    gnugrep
    gnused
    findutils
    gettext # envsubst, used by agent/entrypoint.sh
    git
    gh
    claude-code
    cacert
  ];

  agentEnv = pkgs.buildEnv {
    name = "agent-env";
    paths = harnessPackages ++ packages pkgs;
    pathsToLink = [
      "/bin"
      "/lib"
      "/etc"
      "/share"
      "/include"
    ];
  };

  # The in-container entrypoint, generated by writeShellApplication so shellcheck
  # runs at build time and the host tools it calls are pinned into the image.
  # Built for Linux (it runs inside the Box). The source stays a complete,
  # standalone script — the bats suite exercises it raw — so its shebang is
  # stripped before it becomes this derivation's body.
  entrypoint = pkgs.writeShellApplication {
    name = "entrypoint";
    runtimeInputs = with pkgs; [
      git
      gh
      claude-code
      gettext # envsubst
      coreutils
    ];
    text = stripShebang (builtins.readFile ../agent/entrypoint.sh);
  };

  # Baked into the image at /agent — there is no working tree to bind-mount from
  # once spindrift is a store path. The prompt is deliberately NOT baked here:
  # it is a runtime mount (see promptDir + scripts/run.sh) so it can be tuned
  # per project and hot-overridden without rebuilding the image.
  agentFiles = pkgs.runCommand "spindrift-agent-files" { } ''
    mkdir -p $out/agent
    cp ${entrypoint}/bin/entrypoint $out/agent/entrypoint.sh
    chmod +x $out/agent/entrypoint.sh
  '';

  # The rendered prompt as a host store-path directory (native-buildable on
  # darwin, so it needs no Linux builder). The `run` command bakes this path in
  # and bind-mounts it at /agent/prompts, where the entrypoint reads
  # issue-prompt.md and substitutes the per-issue variables.
  promptDir = hostPkgs.writeTextDir "issue-prompt.md" prompt;

  image = pkgs.dockerTools.buildLayeredImage {
    name = "spindrift";
    tag = "latest";
    contents = [
      agentEnv
      agentFiles
    ];
    extraCommands = ''
      mkdir -p tmp home/agent work
      chmod 1777 tmp
    '';
    config = {
      Entrypoint = [ "/bin/bash" ];
      WorkingDir = "/";
      Env = [
        "PATH=/bin"
        "HOME=/home/agent"
        "SSL_CERT_FILE=${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt"
        "GIT_SSL_CAINFO=${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt"
        "PKG_CONFIG_PATH=/lib/pkgconfig"
        # Consumer-supplied cache warm-up snippet; the entrypoint runs it after
        # cloning. Empty by default (no-op).
        "PREFETCH=${prefetch}"
      ];
    };
  };

  # The image's store path as PLAIN TEXT (context discarded), so the launcher
  # commands embed the exact Linux image path WITHOUT taking a build-time
  # dependency on it. That lets `build`/`run` — and `nix flake check` — build
  # natively on darwin, while realising the image stays an explicit, Linux-only
  # `nix build .#spindrift`.
  imagePath = builtins.unsafeDiscardStringContext (toString image);

  # The image's `.drv` path, also context-discarded. `build` realises this with
  # `nix build "<drv>^*"` before loading, so a fresh machine builds the image
  # instead of failing on an unrealised path — while discarding the context
  # keeps `nix flake check` and the launcher builds off any Linux build. Reading
  # `.drvPath` instantiates the derivation at eval time, so the .drv exists in
  # the store by the time `build` runs; only realising it needs a Linux builder.
  imageDrv = builtins.unsafeDiscardStringContext image.drvPath;

  # Nix-rendered shell preamble: the baked config the launchers consume, in place
  # of the old @placeholder@/--replace-fail lists. Every value is interpolated
  # straight into shell and gets shellcheck'd as part of the generated script.
  #
  # IMAGE_ARCHIVE + RUNTIME are shared by both launchers. RUNTIME names the
  # container runtime but is deliberately NOT a runtimeInput — it stays a checked
  # host install (see the `command -v "$RUNTIME"` guard in the scripts).
  imagePreamble = ''
    IMAGE_ARCHIVE="${imagePath}"
    RUNTIME="${runtime}"
  '';

  # Build-only config, layered on top of imagePreamble for the `build` launcher.
  # IMAGE_DRV is the derivation `build` realises; NIX_BUILDER_IMAGE/NIX_VOLUME
  # drive the ephemeral-container fallback (a named /nix volume keeps it
  # incremental); FLAKE_IMAGE_ATTR is the Linux image attribute that fallback
  # builds from the Consumer flake in $PWD.
  buildPreamble = ''
    IMAGE_DRV="${imageDrv}"
    NIX_BUILDER_IMAGE="${nixBuilderImage}"
    NIX_VOLUME="spindrift-nix"
    FLAKE_IMAGE_ATTR=".#packages.${linuxSystem}.spindrift"
  '';

  # Each run default renders as `NAME="''${NAME:-<baked>}"`, derived from the
  # merged defaults attrset, so a matching env var (or harness.env, sourced by
  # the script) still wins at runtime.
  runDefaultsPreamble = lib.concatStrings (
    lib.mapAttrsToList (envName: value: ''
      ${envName}="''${${envName}:-${toString value}}"
    '')
      {
        LABEL = mergedDefaults.label;
        BASE_BRANCH = mergedDefaults.baseBranch;
        MAX_PARALLEL = mergedDefaults.maxParallel;
        BRANCH_PREFIX = mergedDefaults.branchPrefix;
      }
  );

  # The launcher commands: a nix-rendered preamble + the script body, wrapped by
  # writeShellApplication (shebang, `set -euo pipefail`, a shellcheck at build
  # time, and a runtimeInputs PATH that pins the host tools they call). `gh`,
  # `git`, and coreutils are pinned; the container runtime is not (host install).
  build = hostPkgs.writeShellApplication {
    name = "build";
    runtimeInputs = [ hostPkgs.coreutils ];
    text = imagePreamble + buildPreamble + builtins.readFile ./scripts/build.sh;
  };

  run = hostPkgs.writeShellApplication {
    name = "run";
    runtimeInputs = with hostPkgs; [
      gh
      git
      coreutils
    ];
    text =
      imagePreamble
      + runDefaultsPreamble
      # Baked with string context so `nix build .#run` realises the prompt dir
      # into the store; SPINDRIFT_PROMPT_DIR can still override it at run time.
      + ''
        PROMPT_DIR="${promptDir}"
      ''
      + builtins.readFile ./scripts/run.sh;
  };

  # Realising the Linux image on darwin needs a Linux builder, so only offer it
  # as a package where it can actually build; the launcher commands (which merely
  # reference its path) are always available. `nix flake check` on darwin thus
  # never forces a Linux build.
  isLinux = system == linuxSystem;
in
{
  inherit
    image
    agentEnv
    build
    run
    imagePath
    promptDir
    ;

  packages = {
    inherit build run;
  }
  // lib.optionalAttrs isLinux { spindrift = image; };

  apps = {
    build = {
      type = "app";
      program = "${build}/bin/build";
    };
    run = {
      type = "app";
      program = "${run}/bin/run";
    };
  };
}
