# Shared render functions for the artifacts generated from lib/env-schema.nix.
# nix/checks.nix (drift guards) and nix/regen.nix (the one-shot regenerator,
# `nix run .#regen`) both call these — one renderer per artifact — so the
# guard and the regenerator can never drift from each other (issue #402).
#
# Pure builtins only (no `pkgs.lib`): keeps this file evaluable and unit-
# testable with a bare `nix eval`, without needing a locked nixpkgs.
let
  mapAttrsToList = f: attrs: map (n: f n attrs.${n}) (builtins.attrNames attrs);
  filterAttrs =
    pred: attrs:
    builtins.listToAttrs (
      map (n: {
        name = n;
        value = attrs.${n};
      }) (builtins.filter (n: pred n attrs.${n}) (builtins.attrNames attrs))
    );
  concatStrings = builtins.concatStringsSep "";
  # ASCII-only; every caller here feeds it a SCREAMING_SNAKE_CASE env var name.
  chars = s: builtins.genList (i: builtins.substring i 1 s) (builtins.stringLength s);
  toLower = builtins.replaceStrings (chars "ABCDEFGHIJKLMNOPQRSTUVWXYZ") (chars "abcdefghijklmnopqrstuvwxyz");
  toKebab = env: toLower (builtins.replaceStrings [ "_" ] [ "-" ] env);
in
rec {
  # Display order for the full flag reference (man page OPTIONS groups,
  # flake-options.md sections); must match groupOrder in cmd/launcher/flags.go
  # and lib/mkHarness.nix's manpageRoff.
  groupOrder = [
    "Issue discovery"
    "Lifecycle labels"
    "Branches & merge"
    "Concurrency & dependency waves"
    "Models"
    "Self-healing & retries"
    "Sandbox & resources"
    "Repository & identity"
    "Prompt & skill iteration"
  ];

  # Must match lib/flakeModule.nix groupToAttr.
  groupToAttr = {
    "Issue discovery" = "issueDiscovery";
    "Lifecycle labels" = "lifecycleLabels";
    "Branches & merge" = "branches";
    "Concurrency & dependency waves" = "concurrency";
    "Models" = "models";
    "Self-healing & retries" = "selfHealing";
    "Sandbox & resources" = "sandbox";
    "Repository & identity" = "repository";
    "Prompt & skill iteration" = "promptSkillIteration";
  };

  # templates/default/harness.env.example content.
  renderHarnessEnvExample =
    schema:
    let
      # Render one entry: required/secret → uncommented; optional → commented.
      renderEntry =
        _key: entry:
        let
          active = (entry.required or false) || (entry.secret or false);
          value =
            if (entry.required or false) && !(entry.secret or false) then
              entry.placeholder or ""
            else
              toString (entry.default or "");
          prefix = if active then "" else "# ";
        in
        "# ${entry.doc}\n${prefix}${entry.env}=${value}\n\n";
    in
    "# Copy to harness.env (gitignored) and fill in — or export these in your shell.\n\n"
    + concatStrings (mapAttrsToList renderEntry schema);

  # cmd/launcher/flagtable_gen.go content.
  renderFlagTableGo =
    schema:
    let
      nonSecretSchema = filterAttrs (_: e: !(e.secret or false)) schema;
      secretSchema = filterAttrs (_: e: (e.secret or false)) schema;
      flagKind = e: if builtins.isInt (e.default or null) then "int" else "string";
      flagDflt =
        e:
        if e ? default then
          (if builtins.isInt e.default then builtins.toString e.default else e.default)
        else
          "";
      flagAlias = e: if e ? alias then ", alias: \"${e.alias}\"" else "";
      # Every non-secret knob must declare a group so the full reference groups
      # it under a heading; a missing group is a schema error, not a silent "".
      ungrouped = mapAttrsToList (k: _: k) (filterAttrs (_: e: !(e ? group)) nonSecretSchema);
      rows =
        if ungrouped != [ ] then
          throw "env-schema.nix: non-secret knob(s) missing `group`: ${builtins.concatStringsSep ", " ungrouped}"
        else
          concatStrings (
            mapAttrsToList (
              _: e:
              "\t{env: \"${e.env}\", flag: \"${toKebab e.env}\", group: \"${e.group}\"${flagAlias e}, kind: \"${flagKind e}\", doc: \"${e.doc}\", dflt: \"${flagDflt e}\"},\n"
            ) nonSecretSchema
          );
      secretRows = concatStrings (
        mapAttrsToList (
          _: e: "\t{env: \"${e.env}\", doc: \"${e.doc}\", fileFlag: \"${toKebab e.env}-file\"},\n"
        ) secretSchema
      );
    in
    "// Code generated by mkHarness.nix from lib/env-schema.nix. DO NOT EDIT.\n"
    + "package main\n"
    + "\n"
    + "// schemaFlags is the flag table derived from lib/env-schema.nix.\n"
    + "// Secret knobs are excluded from schemaFlags; see secretKnobs below.\n"
    + "// Run `nix flake check` after editing lib/env-schema.nix to regenerate.\n"
    + "var schemaFlags = []flagEntry{\n"
    + rows
    + "}\n"
    + "\n"
    + "// secretKnobs lists secret knobs that have no value flag.\n"
    + "// Callers must supply these via the environment or via --<fileFlag> path flag.\n"
    + "var secretKnobs = []secretKnob{\n"
    + secretRows
    + "}\n";

  # docs/flake-options.md content.
  renderFlakeOptionsDoc =
    schema:
    let
      flakeOptionEntries = filterAttrs (_: e: e.flakeOption or false) schema;
      groupKnobs = group: filterAttrs (_: e: (e.group or null) == group) flakeOptionEntries;
      renderDefault = entry: if entry ? default then "`${toString entry.default}`" else "—";
      renderRow =
        knobName: entry: sectionAttr:
        "| `settings.${sectionAttr}.${knobName}` | `${entry.env}` | ${renderDefault entry} | ${entry.doc} |\n";
      renderSection =
        group:
        let
          sectionAttr = groupToAttr.${group};
          knobs = groupKnobs group;
        in
        if knobs == { } then
          ""
        else
          "## ${group} (`settings.${sectionAttr}`)\n\n"
          + "| attr path | env var | default | description |\n"
          + "|---|---|---|---|\n"
          + concatStrings (mapAttrsToList (knobName: entry: renderRow knobName entry sectionAttr) knobs)
          + "\n";
    in
    "<!-- Code generated by nix/checks.nix from lib/env-schema.nix. DO NOT EDIT. -->\n"
    + "<!-- Regenerate: nix flake check -->\n"
    + "\n"
    + "# Flake options reference\n"
    + "\n"
    + "Consumer-tunable knobs available under `perSystem.spindrift.settings`.\n"
    + "Grouped by section (matching `spindrift --help --all`); sections with no\n"
    + "consumer-tunable knobs are omitted.\n"
    + "\n"
    + "A matching env var wins at runtime: CLI flag > env > flake setting > baked default.\n"
    + "See [`docs/reference.md`](reference.md) for the full option surface and runtime vars.\n"
    + "\n"
    + concatStrings (map renderSection groupOrder);
}
