# Shared render functions for the artifacts generated from lib/env-schema.nix,
# and the owner of the flag-group section taxonomy (groupOrder/groupToAttr).
# nix/checks/schema-drift.nix (drift guards) and nix/regen.nix (the one-shot
# regenerator, `nix run .#regen`) call these — one renderer per artifact — so
# the guard and the regenerator can never drift from each other (issue #402).
# lib/mkHarness.nix and lib/flakeModule.nix import this file for the taxonomy
# and the man-page renderer, for the same reason (issue #461).
#
# Pure builtins only (no `pkgs.lib`): keeps this file evaluable and unit-
# testable with a bare `nix eval`, without needing a locked nixpkgs.
let
  mapAttrsToList = f: attrs: map (n: f n attrs.${n}) (builtins.attrNames attrs);
  filterAttrs =
    pred: attrs:
    builtins.listToAttrs (
      map (n: {
        name = n;
        value = attrs.${n};
      }) (builtins.filter (n: pred n attrs.${n}) (builtins.attrNames attrs))
    );
  concatStrings = builtins.concatStringsSep "";
  # ASCII-only; every caller here feeds it a SCREAMING_SNAKE_CASE env var name.
  chars = s: builtins.genList (i: builtins.substring i 1 s) (builtins.stringLength s);
  toLower = builtins.replaceStrings (chars "ABCDEFGHIJKLMNOPQRSTUVWXYZ") (
    chars "abcdefghijklmnopqrstuvwxyz"
  );
in
rec {
  # Env var name -> flag name (e.g. MAX_PARALLEL -> max-parallel). Shared by
  # every renderer and check that prints or greps for a flag name.
  toKebab = env: toLower (builtins.replaceStrings [ "_" ] [ "-" ] env);

  # Schema entry -> the type token the flag table and man page print.
  flagKind = e: if builtins.isInt (e.default or null) then "int" else "string";

  # Schema entry -> its default rendered as a string, or "" if it has none.
  flagDflt = e: if e ? default then builtins.toString e.default else "";

  # Display order for the full flag reference (man page OPTIONS groups,
  # flake-options.md sections). cmd/launcher/flags.go carries its own copy
  # (Go stays hand-written per issue #105); nix/checks/schema-drift.nix's
  # launcher-grouporder check pins it against this list.
  groupOrder = [
    "Issue discovery"
    "Lifecycle labels"
    "Branches & merge"
    "Concurrency & dependency waves"
    "Models"
    "Self-healing & retries"
    "Sandbox & resources"
    "Repository & identity"
    "Prompt & skill iteration"
  ];

  groupToAttr = {
    "Issue discovery" = "issueDiscovery";
    "Lifecycle labels" = "lifecycleLabels";
    "Branches & merge" = "branches";
    "Concurrency & dependency waves" = "concurrency";
    "Models" = "models";
    "Self-healing & retries" = "selfHealing";
    "Sandbox & resources" = "sandbox";
    "Repository & identity" = "repository";
    "Prompt & skill iteration" = "promptSkillIteration";
  };

  # Env vars main.go reads that are Nix-computed build/eval artifacts, not
  # user-tunable knobs — they have no lib/env-schema.nix entry (that registry
  # is scoped to runtime knobs, per its own header comment) and never gain
  # one when a knob is added, so they live here rather than as a per-entry
  # schema field. nix/checks/schema-drift.nix's launcher-env-coverage check
  # excludes these from the schema<->main.go coverage comparison.
  nixBakedEnvVars = [
    "IMAGE_ARCHIVE"
    "IMAGE_TAG"
    "IMAGE_DRV"
    "NIX_BUILDER_IMAGE"
    "NIX_VOLUME"
    "FLAKE_IMAGE_ATTR"
    "AGENT_FILES"
    "AGENT_ENV"
    "AGENT_FILES_DRV"
    "AGENT_ENV_DRV"
    "BAKED_PREFETCH"
    "RUNTIME"
    "DRIVER"
    "DRIVER_SKILLS_DIR"
    "DRIVER_SESSION_CACHE_DIR"
    "IMAGE"
    "BOX_ENV_VARS"
  ];

  # tests/box_env_gen.bash content: a set_box_env bash function exporting
  # every boxEnv = true schema knob at its schema default, or its placeholder
  # when it has no default, so the entrypoint-*.bats suites exercise the same
  # defaults the nix preamble bakes into the image at build time.
  renderSetBoxEnvFixture =
    schema:
    let
      boxEnvSchema = filterAttrs (_: e: e.boxEnv or false) schema;
      renderExport =
        _key: e:
        let
          hasDefault = e ? default;
          value = if hasDefault then flagDflt e else (e.placeholder or "");
          rendered = if hasDefault && flagKind e == "int" then value else "\"${value}\"";
        in
        "  export ${e.env}=${rendered}\n";
    in
    "# Code generated by lib/renderers.nix renderSetBoxEnvFixture from\n"
    + "# lib/env-schema.nix. DO NOT EDIT.\n"
    + "# Regenerate with `nix run .#regen` after editing lib/env-schema.nix.\n"
    + "\n"
    + "# Every lib/env-schema.nix knob with boxEnv = true, exported at its schema\n"
    + "# default (or placeholder, for a knob with no default), so the\n"
    + "# entrypoint-*.bats suites exercise the same defaults the nix preamble\n"
    + "# bakes into the image at build time. Individual tests override any of\n"
    + "# these before invoking $ENTRYPOINT.\n"
    + "set_box_env() {\n"
    + concatStrings (mapAttrsToList renderExport boxEnvSchema)
    + "}\n";

  # The generated portion of templates/default/flake.nix's commented settings
  # example, between its BEGIN/END GENERATED SETTINGS EXAMPLE markers:
  # every flakeOption knob, grouped by section, with its doc string, so a new
  # knob is discoverable in the template without a hand-edit (issue #520).
  renderTemplateSettingsBlock =
    schema:
    let
      ind = "            # ";
      flakeOptionEntries = filterAttrs (_: e: e.flakeOption or false) schema;
      # Mirrors renderHarnessEnvExample's value rule (placeholder only for a
      # required knob) so a knob whose placeholder exists solely for the
      # bats fixture (e.g. gitUserName's "Test Bot") renders as "" here, not
      # as a fake identity in consumer-facing documentation.
      nixLiteral =
        e:
        if e ? default then
          if builtins.isBool e.default then
            (if e.default then "true" else "false")
          else if builtins.isInt e.default then
            toString e.default
          else
            "\"${toString e.default}\""
        else if e.required or false then
          "\"${e.placeholder or ""}\""
        else
          "\"\"";
      renderKnob = key: e: "${ind}  # ${e.doc}\n" + "${ind}  ${key} = ${nixLiteral e};\n";
      renderSection =
        group:
        let
          sectionAttr = groupToAttr.${group};
          knobs = filterAttrs (_: e: (e.group or null) == group) flakeOptionEntries;
        in
        if knobs == { } then
          ""
        else
          "${ind}${sectionAttr} = {\n" + concatStrings (mapAttrsToList renderKnob knobs) + "${ind}};\n";
    in
    "${ind}settings = {\n" + concatStrings (map renderSection groupOrder) + "${ind}};\n";

  # templates/default/harness.env.example content.
  renderHarnessEnvExample =
    schema:
    let
      # Render one entry: required/secret → uncommented; optional → commented.
      renderEntry =
        _key: entry:
        let
          active = (entry.required or false) || (entry.secret or false);
          value =
            if (entry.required or false) && !(entry.secret or false) then
              entry.placeholder or ""
            else
              toString (entry.default or "");
          prefix = if active then "" else "# ";
        in
        "# ${entry.doc}\n${prefix}${entry.env}=${value}\n\n";
    in
    "# Copy to harness.env (gitignored) and fill in — or export these in your shell.\n\n"
    + concatStrings (mapAttrsToList renderEntry schema);

  # cmd/launcher/internal/driver/drivernames_gen.go content.
  renderDriverNamesGo =
    driverRegistry:
    let
      names = builtins.sort builtins.lessThan (builtins.attrNames driverRegistry);
      quotedNames = map (n: "\"${n}\"") names;
      namesList = builtins.concatStringsSep ", " quotedNames;
    in
    "// Code generated by nix/checks.nix from lib/drivers/default.nix. DO NOT EDIT.\n"
    + "package driver\n"
    + "\n"
    + "// nixDriverNames is the key list of the Nix Driver registry (lib/drivers/default.nix).\n"
    + "// Regenerate with `nix run .#regen` after editing lib/drivers/default.nix.\n"
    + "var nixDriverNames = []string{"
    + namesList
    + "}\n";

  # cmd/launcher/flagtable_gen.go content.
  renderFlagTableGo =
    schema:
    let
      nonSecretSchema = filterAttrs (_: e: !(e.secret or false)) schema;
      secretSchema = filterAttrs (_: e: (e.secret or false)) schema;
      flagAlias = e: if e ? alias then ", alias: \"${e.alias}\"" else "";
      # Every non-secret knob must declare a group so the full reference groups
      # it under a heading; a missing group is a schema error, not a silent "".
      ungrouped = mapAttrsToList (k: _: k) (filterAttrs (_: e: !(e ? group)) nonSecretSchema);
      rows =
        if ungrouped != [ ] then
          throw "env-schema.nix: non-secret knob(s) missing `group`: ${builtins.concatStringsSep ", " ungrouped}"
        else
          concatStrings (
            mapAttrsToList (
              _: e:
              "\t{env: \"${e.env}\", flag: \"${toKebab e.env}\", group: \"${e.group}\"${flagAlias e}, kind: \"${flagKind e}\", doc: \"${e.doc}\", dflt: \"${flagDflt e}\"},\n"
            ) nonSecretSchema
          );
      secretRows = concatStrings (
        mapAttrsToList (
          _: e: "\t{env: \"${e.env}\", doc: \"${e.doc}\", fileFlag: \"${toKebab e.env}-file\"},\n"
        ) secretSchema
      );
    in
    "// Code generated by mkHarness.nix from lib/env-schema.nix. DO NOT EDIT.\n"
    + "package main\n"
    + "\n"
    + "// schemaFlags is the flag table derived from lib/env-schema.nix.\n"
    + "// Secret knobs are excluded from schemaFlags; see secretKnobs below.\n"
    + "// Run `nix flake check` after editing lib/env-schema.nix to regenerate.\n"
    + "var schemaFlags = []flagEntry{\n"
    + rows
    + "}\n"
    + "\n"
    + "// secretKnobs lists secret knobs that have no value flag.\n"
    + "// Callers must supply these via the environment or via --<fileFlag> path flag.\n"
    + "var secretKnobs = []secretKnob{\n"
    + secretRows
    + "}\n";

  # cmd/launcher/defaults_gen.go content: the sole source of truth for every
  # non-secret knob's baked-in default, so loadConfig() in cmd/launcher/main.go
  # holds no default literal of its own (issue #621). Secret knobs have no
  # baked default (callers must always supply them), so they are excluded,
  # matching renderFlagTableGo's schemaFlags. A []defaultEntry slice (one
  # composite literal per line), not a map[string]string: gofmt column-aligns
  # a map literal's values, which this generator would then have to replicate
  # to stay golden-diff clean; a struct-literal-per-line slice sidesteps that
  # (same shape renderFlagTableGo already uses for schemaFlags).
  renderDefaultsTableGo =
    schema:
    let
      nonSecretSchema = filterAttrs (_: e: !(e.secret or false)) schema;
      rows = concatStrings (
        mapAttrsToList (_: e: "\t{env: \"${e.env}\", dflt: \"${flagDflt e}\"},\n") nonSecretSchema
      );
    in
    "// Code generated by mkHarness.nix from lib/env-schema.nix. DO NOT EDIT.\n"
    + "package main\n"
    + "\n"
    + "// defaultEntry maps one non-secret knob's env var name to its baked-in\n"
    + "// default from lib/env-schema.nix (empty string when the knob has no\n"
    + "// default).\n"
    + "type defaultEntry struct {\n"
    + "\tenv  string\n"
    + "\tdflt string\n"
    + "}\n"
    + "\n"
    + "// schemaDefaults is the defaults table derived from lib/env-schema.nix.\n"
    + "// loadConfig() consults it via schemaDefault() instead of a hand-written\n"
    + "// literal, so the schema stays the only place a default value is written.\n"
    + "// Run `nix flake check` after editing lib/env-schema.nix to regenerate.\n"
    + "var schemaDefaults = []defaultEntry{\n"
    + rows
    + "}\n";

  # docs/flake-options.md content.
  renderFlakeOptionsDoc =
    schema:
    let
      flakeOptionEntries = filterAttrs (_: e: e.flakeOption or false) schema;
      groupKnobs = group: filterAttrs (_: e: (e.group or null) == group) flakeOptionEntries;
      renderDefault = entry: if entry ? default then "`${toString entry.default}`" else "—";
      renderRow =
        knobName: entry: sectionAttr:
        "| `settings.${sectionAttr}.${knobName}` | `${entry.env}` | ${renderDefault entry} | ${entry.doc} |\n";
      renderSection =
        group:
        let
          sectionAttr = groupToAttr.${group};
          knobs = groupKnobs group;
        in
        if knobs == { } then
          ""
        else
          "## ${group} (`settings.${sectionAttr}`)\n\n"
          + "| attr path | env var | default | description |\n"
          + "|---|---|---|---|\n"
          + concatStrings (mapAttrsToList (knobName: entry: renderRow knobName entry sectionAttr) knobs)
          + "\n";
    in
    "<!-- Code generated by nix/checks.nix from lib/env-schema.nix. DO NOT EDIT. -->\n"
    + "<!-- Regenerate: nix flake check -->\n"
    + "\n"
    + "# Flake options reference\n"
    + "\n"
    + "Consumer-tunable knobs available under `perSystem.spindrift.settings`.\n"
    + "Grouped by section (matching `spindrift --help --all`); sections with no\n"
    + "consumer-tunable knobs are omitted.\n"
    + "\n"
    + "A matching env var wins at runtime: CLI flag > env > flake setting > baked default.\n"
    + "See [`docs/reference.md`](reference.md) for the full option surface and runtime vars.\n"
    + "\n"
    + concatStrings (map renderSection groupOrder);

  # share/bash-completion/completions/spindrift content: subcommand
  # completion for the first word, flag completion (incl. the --issue alias
  # and secret --*-file flags) anywhere after it, and filename completion for
  # a --*-file flag's argument. Tracer-bullet slice (issue #551); zsh/fish
  # crib this structure. Rendered fresh at build time, no committed copy —
  # same as renderManpageRoff below.
  renderBashCompletion =
    schema:
    let
      nonSecret = builtins.filter (e: !(e.secret or false)) (builtins.attrValues schema);
      secretEntries = builtins.filter (e: e.secret or false) (builtins.attrValues schema);
      subcommands = [
        "dispatch"
        "research"
        "preview"
        "build"
        "recover"
        "doctor"
      ];
      # Hardcoded like renderManpageRoff's DISPATCH FLAGS / SYNOPSIS sections:
      # dispatch's boolean flags and the top-level flags aren't schema entries.
      extraFlags = [
        "--no-build"
        "--yes"
        "--force"
        "--help"
        "--version"
      ];
      knobFlags = map (e: "--" + toKebab e.env) nonSecret;
      aliasFlags = map (e: "--" + e.alias) (builtins.filter (e: e ? alias) nonSecret);
      fileFlags = map (e: "--" + toKebab e.env + "-file") secretEntries;
      allFlags = builtins.concatStringsSep " " (knobFlags ++ aliasFlags ++ fileFlags ++ extraFlags);
      allSubcommands = builtins.concatStringsSep " " subcommands;
      # A `case "$prev" in ) ... esac` (empty pattern) is a syntax error, so
      # the file-flag branch is omitted entirely if the schema ever has no
      # secret knobs.
      fileFlagBranch =
        if fileFlags == [ ] then
          ""
        else
          ''
            case "$prev" in
              ${builtins.concatStringsSep "|" fileFlags})
                # shellcheck disable=SC2207 # COMPREPLY split-on-space is the standard completion idiom; mapfile needs bash 4+
                COMPREPLY=($(compgen -f -- "$cur"))
                return 0
                ;;
            esac

          '';
    in
    ''
      # Code generated by lib/renderers.nix renderBashCompletion from
      # lib/env-schema.nix. DO NOT EDIT.
      # Rendered fresh at build time (lib/mkHarness.nix); no committed copy —
      # regenerate by rebuilding, not `nix run .#regen`.
      _spindrift() {
        local cur prev
        COMPREPLY=()
        cur="''${COMP_WORDS[COMP_CWORD]}"
        prev="''${COMP_WORDS[COMP_CWORD - 1]}"

        ${fileFlagBranch}if [[ "$cur" == -* ]]; then
          # shellcheck disable=SC2207 # COMPREPLY split-on-space is the standard completion idiom; mapfile needs bash 4+
          COMPREPLY=($(compgen -W "${allFlags}" -- "$cur"))
          return 0
        fi

        if [[ $COMP_CWORD -eq 1 ]]; then
          # shellcheck disable=SC2207 # COMPREPLY split-on-space is the standard completion idiom; mapfile needs bash 4+
          COMPREPLY=($(compgen -W "${allSubcommands}" -- "$cur"))
        fi
      }
      complete -F _spindrift spindrift
    '';

  # share/fish/vendor_completions.d/spindrift.fish content: same coverage as
  # renderBashCompletion above (subcommands as the first word, every flag
  # incl. --issue alias and secret --*-file flags, file completion for a
  # --*-file flag's argument) using fish's `complete -c` syntax, with each
  # flag's schema doc string as its `-d` description. Rendered fresh at build
  # time, no committed copy — same as renderBashCompletion.
  renderFishCompletion =
    schema:
    let
      nonSecret = builtins.filter (e: !(e.secret or false)) (builtins.attrValues schema);
      secretEntries = builtins.filter (e: e.secret or false) (builtins.attrValues schema);
      subcommands = [
        "dispatch"
        "research"
        "preview"
        "build"
        "recover"
        "doctor"
      ];
      extraFlags = [
        {
          flag = "no-build";
          doc = "fail fast if the image is absent instead of building; pair with 'spindrift build' for split build/run flows";
        }
        {
          flag = "yes";
          doc = "skip confirmation prompt when dispatching unlabeled issues (alias: --force)";
        }
        {
          flag = "force";
          doc = "skip confirmation prompt when dispatching unlabeled issues (alias: --yes)";
        }
        {
          flag = "help";
          doc = "show usage and exit";
        }
        {
          flag = "version";
          doc = "show version and exit";
        }
      ];
      subcommandCompletions = builtins.concatStringsSep "\n" (
        map (s: "complete -c spindrift -n '__fish_use_subcommand' -f -a '${s}'") subcommands
      );
      knobCompletions = builtins.concatStringsSep "\n" (
        map (e: "complete -c spindrift -l ${toKebab e.env} -d \"${e.doc}\"") nonSecret
      );
      aliasCompletions = builtins.concatStringsSep "\n" (
        map (e: "complete -c spindrift -l ${e.alias} -d \"${e.doc}\"") (
          builtins.filter (e: e ? alias) nonSecret
        )
      );
      fileCompletions = builtins.concatStringsSep "\n" (
        map (e: "complete -c spindrift -l ${toKebab e.env}-file -r -F -d \"${e.doc}\"") secretEntries
      );
      extraCompletions = builtins.concatStringsSep "\n" (
        map (e: "complete -c spindrift -l ${e.flag} -d \"${e.doc}\"") extraFlags
      );
    in
    ''
      # Code generated by lib/renderers.nix renderFishCompletion from
      # lib/env-schema.nix. DO NOT EDIT.
      # Rendered fresh at build time (lib/mkHarness.nix); no committed copy —
      # regenerate by rebuilding, not `nix run .#regen`.
      ${subcommandCompletions}
      ${knobCompletions}
      ${aliasCompletions}
      ${fileCompletions}
      ${extraCompletions}
    '';

  # share/zsh/site-functions/_spindrift content: same coverage as
  # renderBashCompletion (subcommand completion for the first word, flag
  # completion incl. the --issue alias and secret --*-file flags anywhere
  # after it, filename completion for a --*-file flag's argument), plus a
  # per-candidate description — zsh completion carries them, bash's
  # compgen -W doesn't — sourced from each flag's schema `doc` string (the
  # same text `--help --all` prints). Rendered fresh at build time, no
  # committed copy — same as renderBashCompletion/renderManpageRoff.
  renderZshCompletion =
    schema:
    let
      nonSecret = builtins.filter (e: !(e.secret or false)) (builtins.attrValues schema);
      secretEntries = builtins.filter (e: e.secret or false) (builtins.attrValues schema);
      subcommands = [
        {
          name = "dispatch";
          doc = "dispatch agents in waves; an issue list dispatches exactly those (bypasses label/barrier gates)";
        }
        {
          name = "research";
          doc = "advise-only research dispatch: post a verdict comment per issue; never merges, never promotes";
        }
        {
          name = "preview";
          doc = "dry-run: show what dispatch would pick up, in order";
        }
        {
          name = "build";
          doc = "realize the agent image without running any agent";
        }
        {
          name = "recover";
          doc = "run the merge gate for a single issue";
        }
        {
          name = "doctor";
          doc = "check forge credentials, repository connectivity, and triage label presence";
        }
      ];
      # A `_describe` array entry is 'completion:description' (colon-split
      # on the first colon, same convention the subcommands array above
      # uses); the only character that needs escaping to survive the
      # surrounding single-quoted zsh string literal is an embedded "'"
      # itself (and a literal '\', so the quote-escape this function
      # inserts is never re-escaped — hence backslash first).
      zshEsc = s: builtins.replaceStrings [ "\\" "'" ] [ "\\\\" "'\\''" ] s;
      subcommandSpecs = map (s: "    '${s.name}:${zshEsc s.doc}'\n") subcommands;
      knobSpec = e: "    '--${toKebab e.env}:${zshEsc e.doc}'\n";
      aliasSpec = e: "    '--${e.alias}:${zshEsc e.doc}'\n";
      fileSpec = e: "    '--${toKebab e.env}-file:${zshEsc e.doc}'\n";
      fileFlags = map (e: "--" + toKebab e.env + "-file") secretEntries;
      extraFlagSpecs = [
        "    '--no-build:fail fast if the image is absent instead of building it'\n"
        "    '--yes:skip the confirmation prompt when dispatching unlabeled issues'\n"
        "    '--force:alias for --yes'\n"
        "    '--help:show usage'\n"
        "    '--version:show version'\n"
      ];
      allFlagSpecs = concatStrings (
        map knobSpec nonSecret
        ++ map aliasSpec (builtins.filter (e: e ? alias) nonSecret)
        ++ map fileSpec secretEntries
        ++ extraFlagSpecs
      );
      allSubcommandSpecs = concatStrings subcommandSpecs;
      # A `case "$prev" in ) ... esac` (empty pattern) is a syntax error, so
      # the file-flag branch is omitted entirely if the schema ever has no
      # secret knobs. Mirrors renderBashCompletion's fileFlagBranch.
      fileFlagBranch =
        if fileFlags == [ ] then
          ""
        else
          ''
            case "$prev" in
              ${builtins.concatStringsSep "|" fileFlags})
                _files
                return
                ;;
            esac

          '';
    in
    ''
      #compdef spindrift
      # Code generated by lib/renderers.nix renderZshCompletion from
      # lib/env-schema.nix. DO NOT EDIT.
      # Rendered fresh at build time (lib/mkHarness.nix); no committed copy —
      # regenerate by rebuilding, not `nix run .#regen`.
      _spindrift() {
        local -a subcommands
        subcommands=(
      ${allSubcommandSpecs}  )

        local -a flags
        flags=(
      ${allFlagSpecs}  )

        local cur="''${words[CURRENT]}" prev="''${words[CURRENT-1]}"

        ${fileFlagBranch}if [[ "$cur" == -* ]]; then
          _describe -t options 'spindrift flag' flags
          return
        fi

        if (( CURRENT == 2 )); then
          _describe -t subcommands 'spindrift subcommand' subcommands
        fi
      }
    '';

  # `man spindrift` roff content: the full flag reference that keeps
  # `spindrift --help` (cmd/launcher/flags.go printHelp) concise.
  renderManpageRoff =
    schema: spindriftVersion:
    let
      nonSecret = builtins.filter (e: !(e.secret or false)) (builtins.attrValues schema);
      secretEntries = builtins.filter (e: e.secret or false) (builtins.attrValues schema);
      esc = builtins.replaceStrings [ "\\" ] [ "\\\\" ]; # neutralise stray backslashes
      escFlag = f: builtins.replaceStrings [ "-" ] [ "\\-" ] f; # roff renders \- as a minus
      unknownGroups = builtins.filter (g: !(builtins.elem g groupOrder)) (
        map (e: e.group or "") nonSecret
      );
      optionBlock =
        e:
        let
          names =
            "\\-\\-" + escFlag (toKebab e.env) + (if e ? alias then ", \\-\\-" + escFlag e.alias else "");
          dflt = flagDflt e;
          dfltSentence = if dflt == "" then "No default." else "Default: " + esc dflt + ".";
        in
        ".TP\n.B ${names} \\fI${flagKind e}\\fR\n\\&${esc e.doc}. ${dfltSentence}\n";
      groupSection =
        g:
        let
          entries = builtins.sort (a: b: a.env < b.env) (builtins.filter (e: (e.group or "") == g) nonSecret);
        in
        if entries == [ ] then "" else ".SS ${g}\n" + concatStrings (map optionBlock entries);
      secretBlock =
        e:
        ".TP\n.B ${e.env}\n\\&${esc e.doc}. Supply via the environment or \\-\\-${toKebab e.env}\\-file (reads the value from a file path; takes precedence over the environment).\n";
    in
    if unknownGroups != [ ] then
      throw "renderManpageRoff: knob group(s) absent from groupOrder: ${builtins.concatStringsSep ", " unknownGroups}"
    else
      ''
        .TH SPINDRIFT 1 "${spindriftVersion}" "spindrift ${spindriftVersion}" "Spindrift Manual"
        .SH NAME
        spindrift \- launch waves of headless Claude Code agents across GitHub issues
        .SH SYNOPSIS
        .B spindrift
        [\fIflags\fR] \fIsubcommand\fR [\fIargs\fR]
        .SH DESCRIPTION
        .B spindrift
        dispatches one disposable, nix-built container per GitHub issue, runs a
        headless Claude Code agent inside it, and drives each resulting pull request
        through a merge gate. Every runtime knob is set by flag, environment
        variable, or baked default, in that precedence order. Non-secret knobs also
        read from a gitignored
        .I harness.env
        in the working directory.
        .SH SUBCOMMANDS
        .TP
        .B dispatch [\-\-no-build] [\-\-yes] [issue...]
        Fan out agents. With no issue list, discover dispatchable issues by label;
        an explicit issue list dispatches exactly those, bypassing the label and
        barrier gates.
        .TP
        .B research [\-\-no-build] [\-\-yes] [issue...]
        Advise-only research dispatch: same selective semantics as
        .BR dispatch ,
        but drains the
        .I agent-research
        label instead and posts a verdict comment per issue rather than landing
        code.
        .TP
        .B preview [issue...]
        Dry run: show what dispatch would pick up, in order, without launching any
        agent.
        .TP
        .B build
        Realize the agent image (or store closures) without running any agent.
        .TP
        .B recover <issue>
        Run the merge gate for a single issue whose agent already finished.
        .SH "DISPATCH FLAGS"
        .TP
        .B \-\-no-build
        Fail fast if the image is absent instead of building it; pair with
        .B spindrift build
        for split build/run flows.
        .TP
        .B \-\-yes
        Skip the confirmation prompt when dispatching unlabeled issues. Alias:
        .BR \-\-force .
        .SH OPTIONS
        Flags take precedence over environment variables, which take precedence over
        baked defaults.
        ${concatStrings (map groupSection groupOrder)}.SH ENVIRONMENT
        Secret knobs are never exposed as value flags; they are read from the
        environment or from a file via their
        .B \-\-<name>-file
        flag.
        ${concatStrings (map secretBlock secretEntries)}.SH FILES
        .TP
        .I harness.env
        Gitignored per-checkout config and secrets, sourced from the working
        directory at dispatch time.
        .SH EXAMPLES
        .TP
        Dispatch every ready issue, three containers at a time:
        .B spindrift dispatch \-\-max-parallel 3
        .TP
        Dispatch a single issue, skipping the image build:
        .B spindrift dispatch \-\-no-build 42
        .TP
        Preview the queue without launching anything:
        .B spindrift preview
        .TP
        Print the full flag reference in the terminal:
        .B spindrift \-\-help \-\-all
        .SH "SEE ALSO"
        .BR git (1),
        .BR gh (1)
      '';
}
