#!/usr/bin/env bash
# Shared control flow sourced by the stub-agent fakes (tests/fakes/claude,
# tests/fakes/opencode). It never calls a real LLM. Each caller sources it
# after its own argument parsing and before its own transcript-shape emission,
# with `set -euo pipefail`, DRIVER_LOG, and $model/$prompt already in place.

{
  printf 'driver invoked for issue #%s model=%s\n' "${ISSUE_NUMBER:-?}" "${model:-}"

  # Real claude reads this from its own process environment (issue #2011), so
  # the fake logs whatever it inherited and a test can assert the var arrives
  # whichever in-box binary spawned this process.
  printf 'env: CLAUDE_CODE_DISABLE_BACKGROUND_TASKS=%s\n' "${CLAUDE_CODE_DISABLE_BACKGROUND_TASKS:-}"

  # Same proof for the registry-proxy Binding's npm_config_registry override
  # (issue #2854): it reaches this Driver process, not just the entrypoint
  # shell that exported it.
  printf 'env: npm_config_registry=%s\n' "${npm_config_registry:-}"

  # Same proof for the pnpm Binding (issue #2855): pnpm no longer honors the
  # generic npm_config_registry var, only its own pnpm_config_registry form.
  printf 'env: pnpm_config_registry=%s\n' "${pnpm_config_registry:-}"

  # Same proof for yarn berry's own env-var override (issue #2856).
  printf 'env: YARN_NPM_REGISTRY_SERVER=%s\n' "${YARN_NPM_REGISTRY_SERVER:-}"

  # Same proof for the cargo credential-provider placeholder tokens (ADR 0044's
  # issue #3053 amendment, re-keyed to the proxy source name by issue #3201).
  # The proxy source name is minted per route and per registry, so there is no
  # fixed var to hardcode: enumerate whatever CARGO_REGISTRIES_* vars arrived
  # and let each asserting test name the one its own fixture mints.
  env | sed -n 's/^CARGO_REGISTRIES_/env: CARGO_REGISTRIES_/p'
} >>"$DRIVER_LOG"

# Real claude -p discovers a skill only as a directory holding a SKILL.md
# ($HOME/.claude/skills/<name>/SKILL.md), never a flat <name>.md file, and
# this fake mirrors that so tests assert real discovery without a live LLM.
if [ -d "${HOME:-}/.claude/skills" ]; then
  for _skill in "${HOME}/.claude/skills/"*/SKILL.md; do
    [ -f "$_skill" ] && printf 'skill discovered: %s\n' "$(basename "$(dirname "$_skill")")" >>"$DRIVER_LOG"
  done
fi

# This block simulates an agent that resolves rebase conflicts.
# FAKE_DRIVER_RESOLVE_CONFLICT stays exported for the whole entrypoint run, so
# gating the early exit on an in-progress rebase, not just the flag, lets the
# later calls (including the resume-once recovery pass, issue #1607) fall
# through to the ordinary stream-json path instead of exiting with no output.
if [ "${FAKE_DRIVER_RESOLVE_CONFLICT:-0}" = "1" ] && { [ -d ".git/rebase-merge" ] || [ -d ".git/rebase-apply" ]; }; then
  # A file declaring itself generated ("DO NOT EDIT") is resolved per the
  # conflict-resolve prompt (issue #403): merge both sides in its source, then
  # regenerate the artifact with the command named in its own header, never
  # hand-merge the artifact's conflict markers.
  while IFS= read -r _f; do
    if grep -qi 'do not edit' "$_f" 2>/dev/null; then
      _header="$(grep -i 'code generated by' "$_f" | head -1)"
      _cmd="$(printf '%s' "$_header" | sed -E 's/.*[Cc]ode generated by ([^ ]+) from.*/\1/')"
      _src="$(printf '%s' "$_header" | sed -E 's/.*from ([^ ]+) DO NOT EDIT.*/\1/;s/\.$//')"
      grep -vE '^(<<<<<<<|=======|>>>>>>>)' "$_src" >"$_src.merged"
      mv "$_src.merged" "$_src"
      git add "$_src"
      bash "$_cmd"
      git add "$_f"
    fi
  done < <(git diff --name-only --diff-filter=U)
  # Whatever is still unmerged is an ordinary file, and during a rebase
  # --theirs is the branch being rebased.
  while IFS= read -r _f; do
    git checkout --theirs "$_f"
    git add "$_f"
  done < <(git diff --name-only --diff-filter=U)
  GIT_EDITOR=true git rebase --continue
  exit 0
fi

if [ "${FAKE_DRIVER_COMMIT:-0}" = "1" ]; then
  branch="$(git rev-parse --abbrev-ref HEAD)"
  printf 'stub agent change for issue #%s\n' "${ISSUE_NUMBER:-0}" >agent-change.txt
  git add -A
fi
# This block simulates a driver that staged real work but never committed
# (issue #2012's #1998 dogfood shape). The missing `git commit` is deliberate,
# unlike FAKE_DRIVER_COMMIT above, so the outcome backstop's own commit/push
# salvage is what's under test.
if [ "${FAKE_DRIVER_STAGE_ONLY:-0}" = "1" ]; then
  printf 'stub agent change for issue #%s (staged only)\n' "${ISSUE_NUMBER:-0}" >agent-change.txt
  git add -A
fi
# A resume call (issue #1607's recovery pass) re-invokes this fake against a
# tree the first call already committed, so the identical fixture content
# leaves an empty index and `git commit` would error.
if [ "${FAKE_DRIVER_COMMIT:-0}" = "1" ] && ! git diff --cached --quiet; then
  git commit -m "feat: stub agent commit for #${ISSUE_NUMBER:-0}" >/dev/null
  # A read-only Box (BOX_WRITE_ENABLED unset) holds no push-capable token, so
  # a driver-initiated push would fail authenticating there, while this fake's
  # rewritten `origin` would always accept it (issue #2094). Gate on the same
  # signal the entrypoint gates its own pushes on, so a read-only fixture's
  # commit lands only in this Box's clone.
  if [ -n "${BOX_WRITE_ENABLED:-}" ]; then
    git push origin "$branch" >/dev/null 2>&1
    gh pr create \
      --base "${BASE_BRANCH:-main}" \
      --head "$branch" \
      --title "feat: resolve issue #${ISSUE_NUMBER:-0}" \
      --body "Closes #${ISSUE_NUMBER:-0}"
  fi
fi
