# Eval-level pins for lib/jira-status-mapping.nix (issue #2539): the
# build-time half of the JIRA_STATUS_MAPPING knob. One assertion per
# behavior -- empty-string no-op, valid-mapping parse, and the unknown-key
# rejection path, all of which must mirror
# cmd/launcher/internal/forge/jira/jira.go's ParseStatusMapping.
#
# No malformed-JSON rejection check here (unlike the unknown-key check
# below): `builtins.fromJSON`'s own parse-error is a builtin type error, not
# a `throw`/`assert` failure, and per the Nix manual `builtins.tryEval`
# "will only prevent errors created by throw or assert from being thrown...
# [not] type errors generated by builtins" -- confirmed empirically here
# (`nix eval --impure --expr 'builtins.tryEval (builtins.fromJSON "{not
# valid")'` still aborts the whole evaluation, `success` is never reached).
# lib/jira-status-mapping.nix's `parse` deliberately doesn't rewrap that
# error (matching lib/research-verdicts.nix's `parse`, which has no such
# check either for the same reason), so a check here that forces it would
# abort this whole checks-inbox aggregate, not just fail its own assert.
{ pkgs, ... }:
let
  jsm = import ../../lib/jira-status-mapping.nix;
  inherit (pkgs.lib) assertMsg;
in
{
  # The empty knob (schema default) yields an empty mapping, mirroring
  # ParseStatusMapping's no-op on an empty string.
  jira-status-mapping-parse-empty-is-noop =
    let
      out = jsm.parse "";
    in
    assert assertMsg (out == { }) "parse \"\" must return an empty attrset";
    pkgs.runCommand "jira-status-mapping-parse-empty-is-noop" { } "touch $out";

  # A JSON object with valid keys parses into the same shape, values
  # unchanged.
  jira-status-mapping-parse-valid =
    let
      json = builtins.toJSON {
        inProgress = "In Progress";
        complete = "Done";
      };
      out = jsm.parse json;
    in
    assert assertMsg (
      out == {
        inProgress = "In Progress";
        complete = "Done";
      }
    ) "parse must return the expected attrset with both keys, values unchanged";
    pkgs.runCommand "jira-status-mapping-parse-valid" { } "touch $out";

  # An unknown key must be rejected (mirrors ParseStatusMapping's "unknown
  # key" config error). tryEval exposes only success/failure, never the
  # thrown message text (see nix/checks/drivers.nix's
  # drivers-assert-shape-missing-attribute-throws for the same limitation),
  # so this can't also pin that the message names the four valid states.
  jira-status-mapping-parse-rejects-unknown-key =
    let
      badJSON = builtins.toJSON { bogus = "x"; };
      result = builtins.tryEval (jsm.parse badJSON);
    in
    assert assertMsg (!result.success) "parse must throw on an unknown key";
    pkgs.runCommand "jira-status-mapping-parse-rejects-unknown-key" { } "touch $out";

  # A JSON object using all four canonical keys parses into the same shape,
  # values unchanged.
  jira-status-mapping-parse-valid-all-keys =
    let
      mapping = {
        dispatchable = "To Do";
        inProgress = "In Progress";
        complete = "Done";
        failed = "Failed";
      };
      out = jsm.parse (builtins.toJSON mapping);
    in
    assert assertMsg (out == mapping) "parse must return all four keys unchanged";
    pkgs.runCommand "jira-status-mapping-parse-valid-all-keys" { } "touch $out";

  # JSON `null` mirrors json.Unmarshal of "null" into Go's map[string]string:
  # the map stays nil with no error, so ParseStatusMapping("null") returns an
  # empty mapping rather than erroring.
  jira-status-mapping-parse-null-is-noop =
    let
      out = jsm.parse "null";
    in
    assert assertMsg (out == { }) "parse \"null\" must return an empty attrset";
    pkgs.runCommand "jira-status-mapping-parse-null-is-noop" { } "touch $out";

  # A non-object, non-null JSON payload (array or bare string) must be
  # rejected rather than hitting builtins.attrNames's uncatchable type error.
  jira-status-mapping-parse-rejects-non-object =
    let
      arrayResult = builtins.tryEval (
        jsm.parse (
          builtins.toJSON [
            1
            2
          ]
        )
      );
      stringResult = builtins.tryEval (jsm.parse (builtins.toJSON "hi"));
    in
    assert assertMsg (!arrayResult.success) "parse must throw on a JSON array";
    assert assertMsg (!stringResult.success) "parse must throw on a bare JSON string";
    pkgs.runCommand "jira-status-mapping-parse-rejects-non-object" { } "touch $out";

  # Known divergence from the Go side (see lib/jira-status-mapping.nix's
  # header): validate only checks keys, not value types, so a non-string
  # value survives here even though Go's map[string]string unmarshal would
  # reject it. Pinned so a future key-type check doesn't silently change
  # this without updating the header's caveat too.
  jira-status-mapping-parse-allows-non-string-value =
    let
      out = jsm.parse (builtins.toJSON { complete = 5; });
    in
    assert assertMsg (
      out == { complete = 5; }
    ) "parse must pass a non-string value through unchanged (known Go divergence)";
    pkgs.runCommand "jira-status-mapping-parse-allows-non-string-value" { } "touch $out";
}
