# Eval-level pins for lib/jira-status-mapping.nix (issue #2539): the
# build-time half of the JIRA_STATUS_MAPPING knob. One assertion per
# behavior -- empty-string no-op, valid-mapping parse, and the unknown-key
# rejection path, all of which must mirror
# cmd/launcher/internal/forge/jira/jira.go's ParseStatusMapping.
#
# No malformed-JSON rejection check here (unlike the unknown-key check
# below): `builtins.fromJSON`'s own parse-error is a builtin type error, not
# a `throw`/`assert` failure, and per the Nix manual `builtins.tryEval`
# "will only prevent errors created by throw or assert from being thrown...
# [not] type errors generated by builtins" -- confirmed empirically here
# (`nix eval --impure --expr 'builtins.tryEval (builtins.fromJSON "{not
# valid")'` still aborts the whole evaluation, `success` is never reached).
# lib/jira-status-mapping.nix's `parse` deliberately doesn't rewrap that
# error (matching lib/research-verdicts.nix's `parse`, which has no such
# check either for the same reason), so a check here that forces it would
# abort this whole checks-inbox aggregate, not just fail its own assert.
{ pkgs, ... }:
let
  jsm = import ../../lib/jira-status-mapping.nix;
  inherit (pkgs.lib) assertMsg;
in
{
  # The empty knob (schema default) yields an empty mapping, mirroring
  # ParseStatusMapping's no-op on an empty string.
  jira-status-mapping-parse-empty-is-noop =
    let
      out = jsm.parse "";
    in
    assert assertMsg (out == { }) "parse \"\" must return an empty attrset";
    pkgs.runCommand "jira-status-mapping-parse-empty-is-noop" { } "touch $out";

  # A JSON object with valid keys parses into the same shape, values
  # unchanged.
  jira-status-mapping-parse-valid =
    let
      json = builtins.toJSON {
        inProgress = "In Progress";
        complete = "Done";
      };
      out = jsm.parse json;
    in
    assert assertMsg (
      out == {
        inProgress = "In Progress";
        complete = "Done";
      }
    ) "parse must return the expected attrset with both keys, values unchanged";
    pkgs.runCommand "jira-status-mapping-parse-valid" { } "touch $out";

  # An unknown key must be rejected (mirrors ParseStatusMapping's "unknown
  # key" config error).
  jira-status-mapping-parse-rejects-unknown-key =
    let
      badJSON = builtins.toJSON { bogus = "x"; };
      result = builtins.tryEval (jsm.parse badJSON);
    in
    assert assertMsg (!result.success) "parse must throw on an unknown key";
    pkgs.runCommand "jira-status-mapping-parse-rejects-unknown-key" { } "touch $out";
}
