// Code generated by nix/regen.nix from lib/prompt-contract.nix. DO NOT EDIT.
package outcome

// Regenerate with `nix run .#regen` after editing lib/prompt-contract.nix's
// markerChannels.
//
// One row per marker channel (issue #2974, parent #2972): outcome, comment,
// pr-intent, issue-intent, review-verdict. Each channel's defense
// (structural / nonce / fold) and carrier are recorded in that Nix
// registry, the citable home for the trust model; only the token itself is
// rendered into Go.
const (
	markerChannelOutcomeToken       = "SPINDRIFT_OUTCOME"
	markerChannelCommentToken       = "SPINDRIFT_COMMENT"
	markerChannelPRIntentToken      = "SPINDRIFT_PR_INTENT"
	markerChannelIssueIntentToken   = "SPINDRIFT_ISSUE_INTENT"
	markerChannelReviewVerdictToken = "VERDICT:"
)

// MarkerChannelTokens is the ordered list of every lib/prompt-contract.nix
// markerChannels registry token, iterated by the caveman marker-exemption
// parity test instead of a hand-listed subset.
var MarkerChannelTokens = []string{
	markerChannelOutcomeToken,
	markerChannelCommentToken,
	markerChannelPRIntentToken,
	markerChannelIssueIntentToken,
	markerChannelReviewVerdictToken,
}
