// Package outcome owns the SPINDRIFT_OUTCOME grammar, parsing, and log scan.
// It is the single source of truth for the per-Box result contract between
// the Agent and the Harness (see CONTEXT.md — Outcome line).
package outcome

import (
	"encoding/base64"
	"errors"
	"fmt"
	"os"
	"strings"

	"spindrift.dev/launcher/internal/logscan"
)

// The marker literals below all come from markerchannels_gen.go, rendered
// from lib/prompt-contract.nix's markerChannels registry -- the single
// source of truth. They are exported so the marker-contract parity guard
// (orchestrator's TestPromptMarkersMatchScanner) and other packages pin
// against these consts rather than hand-typed strings of their own.
// Rewording a marker on one side of the contract without the other silently
// breaks the channel it names.

// Token is the SPINDRIFT_OUTCOME marker (ADR 0035). The orchestrator's
// scanPassLog greps rendered pass logs for it; losing the match collapses
// the multi-pass loop to single-pass on ORCHESTRATOR_ENABLED runs.
const Token = markerChannelOutcomeToken

// PRIntentToken is the SPINDRIFT_PR_INTENT marker: a read-only Box's
// draft-PR title/body hand-off, scanned host-side by LastPRIntentInLog and,
// in-box, by the required-marker-gate row that resumes the session once
// when it never showed up on a status=ready run.
const PRIntentToken = markerChannelPRIntentToken

// CommentToken is the SPINDRIFT_COMMENT marker: the mid-run comment-relay
// channel LastCommentLineInLog scans for.
const CommentToken = markerChannelCommentToken

// IssueIntentToken is the SPINDRIFT_ISSUE_INTENT marker: the file-an-issue
// relay channel AllIssueIntentLinesInLog scans for.
const IssueIntentToken = markerChannelIssueIntentToken

// ReviewVerdictToken is the bare review-verdict channel token, distinct from
// the full "VERDICT: APPROVE"/"VERDICT: BLOCK" values orchestrator composes
// from it.
const ReviewVerdictToken = markerChannelReviewVerdictToken

// Outcome is the machine-readable result written by a Box as its final line.
// Grammar: SPINDRIFT_OUTCOME issue=<num> landing=<landing-ref> status=<status> note=<text>
// Note may contain spaces and '='; all other fields are space-delimited tokens.
type Outcome struct {
	Issue string
	// Landing is the landing reference: a PR URL under CODE_FORGE=github, a
	// branch ref (e.g. "agent/issue-42") under the push-only CODE_FORGE=git,
	// or a verdict-comment URL for the research dispatch kind.
	Landing string
	Status  string // ready | blocked | failed | merged | …
	// Synthetic flags a line generated by the outcome backstop (ADR 0036)
	// rather than authored by the driver — set only on the synthetic
	// backstop line (issue #2223).
	Synthetic bool
	Note      string // free text; may contain spaces and '='
}

// ErrNearMiss marks a Parse error where the SPINDRIFT_OUTCOME token is
// present in the line but the line still fails to parse — required fields
// missing or malformed, or the token embedded mid-sentence rather than
// leading a standalone line. Separable from the token being entirely absent
// so callers (e.g. a resume nudge) can react to "almost got it" differently
// from "never tried".
var ErrNearMiss = errors.New("outcome: near-miss")

// IsNearMiss reports whether err was returned because a SPINDRIFT_OUTCOME
// token was present but the line did not parse, as opposed to the token
// being entirely absent.
func IsNearMiss(err error) bool {
	return errors.Is(err, ErrNearMiss)
}

// Parse parses a single SPINDRIFT_OUTCOME line.
// Returns an error if the line lacks the required prefix or is missing the
// landing or status fields. The latter case, and a line where the token
// appears but not as a standalone-line prefix, are wrapped in ErrNearMiss
// (see IsNearMiss). That leading-token requirement belongs to lastInLog,
// which scans whole logs and only ever treats a leading-token line as a
// candidate, so a bare mention in prose never reaches Parse from that path;
// a caller handing Parse a single already-selected line makes that
// leading-token decision itself.
func Parse(line string) (Outcome, error) {
	line = strings.TrimSpace(line)
	rest, ok := stripToken(line, Token)
	if !ok {
		if containsToken(line, Token) {
			return Outcome{}, fmt.Errorf("%w: line contains %q but does not match the standalone-line grammar", ErrNearMiss, Token)
		}
		return Outcome{}, fmt.Errorf("outcome: line missing %q prefix", Token+" ")
	}
	o := Outcome{
		Issue:     tokenField(rest, "issue"),
		Landing:   tokenField(rest, "landing"),
		Status:    tokenField(rest, "status"),
		Synthetic: tokenField(rest, "synthetic") == "true",
		Note:      noteField(rest),
	}
	if o.Landing == "" {
		return Outcome{}, fmt.Errorf("%w: missing landing field", ErrNearMiss)
	}
	if o.Status == "" {
		return Outcome{}, fmt.Errorf("%w: missing or empty status field", ErrNearMiss)
	}
	return o, nil
}

// ReadyBeforeNote reports whether line leads with the outcome token and
// carries "status=ready" among the fields before the first " note=". For
// callers (markergate.ShouldNudgePRIntent) that need "is this line claiming
// ready" without Parse's full validity contract -- Parse rejects an empty
// landing as a near-miss; this does not care. Bounding at " note=" keeps a
// "status=ready" mention inside the note itself from counting.
func ReadyBeforeNote(line string) bool {
	line = strings.TrimSpace(line)
	rest, ok := stripToken(line, Token)
	if !ok {
		return false
	}
	before, _, _ := strings.Cut(rest, " note=")
	for _, tok := range strings.Fields(before) {
		if tok == "status=ready" {
			return true
		}
	}
	return false
}

// hasField reports whether line (already stripped of its leading token)
// carries key= as a space-delimited field. Unlike tokenField, which returns
// "" for both "absent" and "present but empty", this answers presence alone
// -- the distinction markergate's outcome-nudge gate needs.
func hasField(line, key string) bool {
	prefix := key + "="
	for _, tok := range strings.Fields(line) {
		if strings.HasPrefix(tok, prefix) {
			return true
		}
	}
	return false
}

// hasOutcomeFields reports whether rest carries both a landing= and a
// status= marker, any value included -- presence only, deliberately looser
// than Parse's full-grammar validity. See LastFieldedOutcomeLine.
func hasOutcomeFields(rest string) bool {
	return hasField(rest, "landing") && hasField(rest, "status")
}

// LastFieldedOutcomeLine scans path for the last token-leading line
// satisfying hasOutcomeFields. It filters to fielded lines BEFORE taking the
// last, unlike lastInLog/lastSelfReportInLog, which take the last
// token-leading line and only then classify it. Both differences matter to
// markergate.ShouldNudgeOutcome: consulting Parse instead spuriously nudges
// on an empty-landing fielded line, and taking the unconditional last line
// lets a later non-fielded paraphrase shadow an earlier genuine one.
//
// Returns ("", false, nil) when no fielded line is present, or the file does
// not exist; ("", false, err) only on a genuine I/O error.
func LastFieldedOutcomeLine(path string) (line string, found bool, err error) {
	var last string
	scanErr := logscan.ForEachLine(path, logscan.SkipOversized, func(l string) {
		trimmed := strings.TrimSpace(l)
		rest, ok := stripToken(trimmed, Token)
		if !ok || !hasOutcomeFields(rest) {
			return
		}
		last = trimmed
	})
	if scanErr != nil {
		if errors.Is(scanErr, os.ErrNotExist) {
			return "", false, nil
		}
		return "", false, scanErr
	}
	if last == "" {
		return "", false, nil
	}
	return last, true, nil
}

// LastNearMissOutcomeLine scans path for the last token-leading line that
// does NOT satisfy hasOutcomeFields -- the complement LastFieldedOutcomeLine
// filters out, used to quote the offending line in a corrective resume
// prompt.
//
// Returns ("", false, nil) when no such line is present, or the file does
// not exist; ("", false, err) only on a genuine I/O error.
func LastNearMissOutcomeLine(path string) (line string, found bool, err error) {
	var last string
	scanErr := logscan.ForEachLine(path, logscan.SkipOversized, func(l string) {
		trimmed := strings.TrimSpace(l)
		rest, ok := stripToken(trimmed, Token)
		if !ok || hasOutcomeFields(rest) {
			return
		}
		last = trimmed
	})
	if scanErr != nil {
		if errors.Is(scanErr, os.ErrNotExist) {
			return "", false, nil
		}
		return "", false, scanErr
	}
	if last == "" {
		return "", false, nil
	}
	return last, true, nil
}

// Line returns the canonical SPINDRIFT_OUTCOME representation of o.
// Parse(o.Line()) == o for all valid Outcomes.
func (o Outcome) Line() string {
	if o.Synthetic {
		return fmt.Sprintf("%s issue=%s landing=%s status=%s synthetic=true note=%s",
			Token, o.Issue, o.Landing, o.Status, o.Note)
	}
	return fmt.Sprintf("%s issue=%s landing=%s status=%s note=%s",
		Token, o.Issue, o.Landing, o.Status, o.Note)
}

// ParseAnywhere finds the token anywhere in line, not only as a leading
// prefix, and parses from there. For callers scanning already-rendered
// transcript text rather than a raw box log: RenderTranscript prefixes every
// line with a "[role] " tag, so Parse alone would always report ErrNearMiss.
// Returns (Outcome{}, false) when the token is absent or the text from that
// point fails to parse.
func ParseAnywhere(line string) (Outcome, bool) {
	idx := tokenIndex(line, Token)
	if idx < 0 {
		return Outcome{}, false
	}
	o, err := Parse(line[idx:])
	if err != nil {
		return Outcome{}, false
	}
	return o, true
}

// lastInLog scans the file at path for the SPINDRIFT_OUTCOME token and
// parses the result via Parse, so the same colon/whitespace tolerance and
// near-miss classification apply. Only the last line that leads with the
// token (a genuine attempt at the grammar, however it fares in Parse) is a
// candidate; a line that merely carries the token mid-sentence or mid-JSON
// — e.g. a tool_result echo of issue/comment text — is not, no matter how
// many field markers (issue=/landing=/status=/note=) it happens to carry.
// Lines larger than the 4 MiB scan buffer are skipped rather than aborting
// the scan.
//
// Returns (Outcome{}, false, nil) when no leading-token line is present, or
// the file does not exist. Returns (Outcome{}, false, err) when the chosen
// candidate line fails to parse — err satisfies IsNearMiss in that case —
// or on an I/O error other than file-not-found or oversized lines.
//
// lastInLog applies no nonce gate (ADR 0047): unlike the mid-run signal
// channels, the outcome line is read only after the Box has exited, so there
// is no later window for an untrusted echoed line to race ahead of.
func lastInLog(path string) (o Outcome, found bool, err error) {
	var lastLeading string
	scanErr := logscan.ForEachLine(path, logscan.SkipOversized, func(line string) {
		if _, ok := stripToken(strings.TrimSpace(line), Token); ok {
			lastLeading = line
		}
	})
	if scanErr != nil {
		if errors.Is(scanErr, os.ErrNotExist) {
			return Outcome{}, false, nil
		}
		return Outcome{}, false, scanErr
	}

	if lastLeading == "" {
		return Outcome{}, false, nil
	}
	o, err = Parse(lastLeading)
	if err != nil {
		return Outcome{}, false, err
	}
	return o, true, nil
}

// SelfReport is the driver's last genuine (non-synthetic) leading-token
// self-report, surfaced distinctly from the authoritative parsed outcome so
// a synthetic backstop line (ADR 0036) can never shadow it via
// last-line-wins. Read-only: it changes no dispatch, PR, or label behaviour
// on its own.
//
// Status is the status= value when the line parses the full grammar,
// otherwise the bare word following the token delimiter, for a paraphrase
// like `SPINDRIFT_OUTCOME: success`.
//
// The report is unauthenticated and advisory -- a paraphrasing model drops
// every field, nonce included -- so a consumer that acts on it owns weighing
// that trust.
type SelfReport struct {
	Raw     string  // the raw driver-authored leading-token line
	Status  string  // best-effort self-reported status (field value or bare word)
	Outcome Outcome // populated only when Parsed
	Parsed  bool    // whether Raw parsed the full SPINDRIFT_OUTCOME grammar
}

// lastSelfReportInLog returns the driver's last genuine (non-synthetic)
// leading-token SPINDRIFT_OUTCOME self-report from the log at path. It scans
// for the last line that leads with the token (stripToken tolerance: `TOKEN `
// or `TOKEN:`) and is NOT flagged synthetic=true, so the backstop's own
// appended synthetic line — which wins lastInLog's last-line-wins — is
// skipped here and the driver's real signal survives. See SelfReport for the
// trust caveat.
//
// Returns (SelfReport{}, false, nil) when no non-synthetic leading-token line
// exists, or the file does not exist. Returns (SelfReport{}, false, err) only
// on an I/O error other than file-not-found or an oversized skipped line.
func lastSelfReportInLog(path string) (report SelfReport, found bool, err error) {
	var last string
	scanErr := logscan.ForEachLine(path, logscan.SkipOversized, func(line string) {
		trimmed := strings.TrimSpace(line)
		if _, ok := stripToken(trimmed, Token); !ok {
			return
		}
		if tokenField(trimmed, "synthetic") == "true" {
			return
		}
		last = trimmed
	})
	if scanErr != nil {
		if errors.Is(scanErr, os.ErrNotExist) {
			return SelfReport{}, false, nil
		}
		return SelfReport{}, false, scanErr
	}
	if last == "" {
		return SelfReport{}, false, nil
	}
	return selfReportFromLine(last), true, nil
}

// LastSelfReport exposes the self-report tier on its own, for callers that
// want this signal unconditionally and alongside a possibly-also-present
// genuine outcome -- not only as Resolve's last-resort fallback. It always
// returns the self-report, never adjudicating it against a genuine or
// synthetic outcome the way Resolve's tier walk does, so it cannot diverge
// from that precedence.
//
// Returns (SelfReport{}, false, nil) when no non-synthetic leading-token line
// exists, or the file does not exist; ("", false, err) only on an I/O error.
func LastSelfReport(path string) (report SelfReport, found bool, err error) {
	return lastSelfReportInLog(path)
}

// selfReportFromLine builds a SelfReport from a leading-token line: a full
// parse when the grammar holds, otherwise a best-effort bare status word
// (the first whitespace-delimited field after the token delimiter that is
// not itself a key=value field).
func selfReportFromLine(line string) SelfReport {
	r := SelfReport{Raw: line}
	if o, perr := Parse(line); perr == nil {
		r.Outcome = o
		r.Parsed = true
		r.Status = o.Status
		return r
	}
	if rest, ok := stripToken(line, Token); ok {
		fields := strings.Fields(rest)
		if len(fields) > 0 && !strings.Contains(fields[0], "=") {
			r.Status = fields[0]
		}
	}
	return r
}

// Provenance identifies which tier of the SPINDRIFT_OUTCOME selection policy
// produced a Resolved value: an authored line the driver itself emitted
// (ProvenanceGenuine), the outcome backstop's own appended line when the
// driver never emitted one (ProvenanceSynthetic, ADR 0036), or the driver's
// unauthenticated self-report fallback (ProvenanceSelfReport) — the last
// resort Resolve falls back to only when no nonce-gated outcome line was
// found at all.
type Provenance string

const (
	// ProvenanceGenuine is a driver-authored, non-synthetic outcome line.
	ProvenanceGenuine Provenance = "genuine"
	// ProvenanceSynthetic is the outcome backstop's appended line (ADR 0036,
	// issue #2223) — the driver itself never emitted an outcome.
	ProvenanceSynthetic Provenance = "synthetic"
	// ProvenanceSelfReport is the driver's unauthenticated self-report
	// fallback (see SelfReport) — not yet produced by Resolve.
	ProvenanceSelfReport Provenance = "self-report"
)

// PassLog names one pass's log file for Resolve to scan, in the order the
// passes ran. It mirrors dispatch.PassLog's {Label, Path} shape: outcome
// cannot import dispatch (that would cycle back through outcome), so this is
// its own copy of that shape and a dispatch caller converts its own
// []dispatch.PassLog to []outcome.PassLog, field for field, at the call
// site.
type PassLog struct {
	Label string
	Path  string
}

// Resolved is the result of Resolve: the outcome Resolve selected, which
// tier of the selection policy produced it, and the normalized dispatch
// kind the caller asked about.
type Resolved struct {
	Outcome    Outcome
	Provenance Provenance
	// Kind is the normalized dispatch kind ("" input becomes "work"). It is
	// carried through unchanged and does not affect selection: ADR 0022
	// rejected a kind-specific outcome grammar, so Resolve is kind-agnostic
	// by design.
	Kind  string
	Found bool
	// SelfReport carries the driver's unauthenticated self-report alongside
	// whichever tier won Outcome above. Populated on every Resolved with
	// Found true, not only when the self-report tier itself won, so a caller
	// can weigh both signals: a late synthetic backstop can win Outcome while
	// an earlier driver-authored line stays visible here.
	SelfReport      SelfReport
	SelfReportFound bool
	// SelfReportError is the last I/O error hit while scanning for the
	// self-report. Purely observability -- the walk never aborts on it and
	// keeps trying later logs, so it does not change what lands on
	// SelfReport. Distinct from Resolve's returned error, which reflects only
	// the genuine/synthetic tier.
	SelfReportError error
}

// IsGenuineOrSynthetic reports whether r settled on the genuine or synthetic
// tier — never the self-report fallback. A caller deciding whether to settle
// on r's Outcome must exclude ProvenanceSelfReport: that tier is Resolve's
// last-resort, unauthenticated fallback (see ProvenanceSelfReport), and a
// self-report-only match must fall through to the caller's own
// classification instead of being treated as a resolved outcome.
func (r Resolved) IsGenuineOrSynthetic() bool {
	return r.Provenance == ProvenanceGenuine || r.Provenance == ProvenanceSynthetic
}

// Resolve is the single seam picking among the outcome selection tiers — a
// genuine driver-authored line, the backstop's synthetic line, and as a last
// resort the driver's unauthenticated self-report — returning the winner as
// Resolved.Provenance. It exists so no caller reimplements, or diverges
// from, that precedence.
//
// Both the genuine/synthetic and self-report walks run over logs in order,
// last match wins. Neither applies a nonce gate (ADR 0047): the freshness
// boundary is structural. A near-miss on the chosen genuine candidate
// propagates as Resolve's error. The self-report walk runs unconditionally,
// so Resolved always carries that signal alongside whichever tier won —
// including next to a near-miss error, so a caller that only wants the
// self-report never loses it just because the authoritative tier could not
// settle.
//
// Only when the genuine/synthetic tier finds no leading-token line at all
// does the self-report become the winning tier. Then Resolved.Outcome is the
// full report.Outcome when report.Parsed, otherwise Status alone — Issue,
// Landing and Note stay zero, so a caller must not assume they are
// meaningful under ProvenanceSelfReport.
//
// When neither tier yields anything, Resolve returns Resolved{Found: false}
// with no error, per this package's not-found-is-not-an-error convention.
// kind is normalized ("" becomes "work") and never affects selection.
func Resolve(logs []PassLog, kind string) (Resolved, error) {
	if kind == "" {
		kind = "work"
	}

	var (
		winner  Outcome
		found   bool
		lastErr error
	)
	for _, log := range logs {
		o, ok, err := lastInLog(log.Path)
		switch {
		case err != nil:
			// A later log's near-miss candidate (issue-shaped line present,
			// but unparseable) overrides an earlier log's successful match,
			// same as a later log's successful match would — last pass wins
			// applies to a failed attempt too, not only a clean one.
			lastErr = err
			found = false
		case ok:
			winner = o
			found = true
			lastErr = nil
		}
		// Neither case: this log had no candidate at all, so it leaves the
		// running state from prior logs untouched.
	}
	report, reportFound, reportErr := lastSelfReportAcrossLogs(logs)

	if lastErr != nil {
		return Resolved{Kind: kind, SelfReport: report, SelfReportFound: reportFound, SelfReportError: reportErr}, lastErr
	}

	if found {
		provenance := ProvenanceGenuine
		if winner.Synthetic {
			provenance = ProvenanceSynthetic
		}
		return Resolved{
			Outcome:         winner,
			Provenance:      provenance,
			Kind:            kind,
			Found:           true,
			SelfReport:      report,
			SelfReportFound: reportFound,
			SelfReportError: reportErr,
		}, nil
	}

	if !reportFound {
		return Resolved{Kind: kind, SelfReportError: reportErr}, nil
	}
	if report.Parsed {
		return Resolved{
			Outcome:         report.Outcome,
			Provenance:      ProvenanceSelfReport,
			Kind:            kind,
			Found:           true,
			SelfReport:      report,
			SelfReportFound: true,
			SelfReportError: reportErr,
		}, nil
	}
	return Resolved{
		Outcome:         Outcome{Status: report.Status},
		Provenance:      ProvenanceSelfReport,
		Kind:            kind,
		Found:           true,
		SelfReport:      report,
		SelfReportFound: true,
		SelfReportError: reportErr,
	}, nil
}

// lastSelfReportAcrossLogs walks logs in order, last match wins. An
// unreadable log is skipped rather than aborting the selection — this is the
// last-resort tier — but the last I/O error seen is returned so it stays
// observable rather than being discarded.
func lastSelfReportAcrossLogs(logs []PassLog) (SelfReport, bool, error) {
	var (
		winner  SelfReport
		found   bool
		lastErr error
	)
	for _, log := range logs {
		report, ok, err := lastSelfReportInLog(log.Path)
		if err != nil {
			lastErr = err
		}
		if err != nil || !ok {
			continue
		}
		winner = report
		found = true
	}
	return winner, found, lastErr
}

// LastCommentLineInLog scans the file at path for the last line carrying the
// SPINDRIFT_COMMENT token and decodes its single-line grammar: SPINDRIFT_COMMENT
// <nonce> <base64-encoded-body> (issue #1940). See lastVerifiedSignalInLog for
// the verify-then-prefer selection semantics, which differ from lastInLog's
// always-take-the-last-line behavior for SPINDRIFT_OUTCOME.
//
// A stream-json JSONL box log collapses a printed line's trailing newline
// into a literal `\n` escape butted directly against the base64 payload with
// no whitespace in between; the payload is taken as the longest run of valid
// base64 characters after the nonce field, so that trailing JSON escaping
// never reaches the decoder.
//
// Returns ("", false, 0, nil) when no line carries the token, or the file
// does not exist — there was never a comment to relay. Returns ("", false,
// rejectedCount, err) only when every token-bearing line fails to verify — a
// spoof attempt or corruption, for the caller to log, never treated as
// no-comment. Otherwise returns the last verifying line's body; rejectedCount
// still counts non-verifying lines, but a successful relay wins over
// reporting them, since one return cannot carry both.
func LastCommentLineInLog(path, expectedNonce string) (string, bool, int, error) {
	return lastVerifiedSignalInLog(path, CommentToken, expectedNonce,
		"comment line found but did not verify: nonce mismatch or malformed payload")
}

// base64AlphabetPrefix returns the longest prefix of s consisting solely of
// standard-base64 alphabet characters (A-Z, a-z, 0-9, '+', '/', '=') — the
// boundary a JSON-escaped trailing `\n` (a literal backslash followed by
// 'n', neither a base64 character) or other JSON syntax never crosses.
func base64AlphabetPrefix(s string) string {
	for i := 0; i < len(s); i++ {
		if !isBase64Char(s[i]) {
			return s[:i]
		}
	}
	return s
}

func isBase64Char(b byte) bool {
	return ('A' <= b && b <= 'Z') || ('a' <= b && b <= 'z') || ('0' <= b && b <= '9') || b == '+' || b == '/' || b == '='
}

// LastPRIntentInLog scans the file at path for the last line carrying the
// SPINDRIFT_PR_INTENT token and decodes its single-line grammar:
// SPINDRIFT_PR_INTENT <nonce> <base64-payload> (issue #1938) — the draft-PR
// title and body a read-only Box hands the launcher in place of its own
// `gh pr create` (issue #1919), replacing the retired
// SPINDRIFT_PR_INTENT_BEGIN/END block the same way LastCommentLineInLog
// replaced LastCommentInLog: a stream-json JSONL box log collapses a
// multi-line block onto one physical line, so an exact-line marker scan
// never finds it (issue #1921's dogfood failure).
//
// See lastVerifiedSignalInLog for the verify-then-prefer selection semantics,
// shared with LastCommentLineInLog.
//
// The decoded payload is the same "title\n\nbody" shape the retired block
// held: the first line is the PR title and the remainder, after a blank
// line, is the PR body; splitting title from body remains the caller's
// concern.
//
// Returns ("", false, 0, nil) when no line carries the token at all, or the
// file does not exist — there was never a PR-intent to relay. Returns ("",
// false, rejectedCount, err) only when every token-bearing line fails to
// verify — a spoof attempt or a corrupted line, for the caller to log;
// never conflated with no-PR-intent-found. rejectedCount is how many
// token-bearing lines failed to verify. Returns (payload, true,
// rejectedCount, nil) from the last line that verifies, even if a later,
// non-verifying line also carries the token.
func LastPRIntentInLog(path, expectedNonce string) (string, bool, int, error) {
	return lastVerifiedSignalInLog(path, PRIntentToken, expectedNonce,
		"PR-intent line found but did not verify: nonce mismatch or malformed payload")
}

// AllIssueIntentLinesInLog scans the file at path for every line carrying
// the SPINDRIFT_ISSUE_INTENT token and decodes each verifying line's
// single-line grammar: SPINDRIFT_ISSUE_INTENT <nonce> <base64-payload>
// (issue #2018) — a read-only Box's file-an-issue request, host-mediated the
// same way LastCommentLineInLog/LastPRIntentInLog relay a comment or
// draft-PR intent. Unlike those two singleton "last verifying line wins"
// scanners, issue filing is 1-to-many — a run may want to file several
// issues — so every verifying line's decoded payload is collected, in the
// order encountered, rather than only the last surviving. Payloads are
// deduped by their decoded byte identity (issue #2068): a Filer subagent
// echoes its one intent line twice into the raw stream-json log — once as its
// own `assistant` event, once in the parent's `tool_result` event — and the
// two decode identically, so the second is dropped rather than filed as a
// duplicate issue. A line carrying the token that fails to verify (wrong
// nonce, malformed base64) is dropped from the collected payloads, exactly as
// a non-verifying PR-intent/comment line is dropped from those scanners'
// single result — an untrusted issue/comment author's echo of the token must
// never be mistaken for a genuine filed-issue request — but, unlike the
// silent drop this function used to apply, it is now counted via the
// returned rejectedCount (issue #2976), so a caller can settle-log a warning
// instead of the drop staying entirely invisible. Unlike the deduped payloads
// slice, rejectedCount has no equivalent dedup, so the same #2068 double-echo
// can double-count a single failed relay attempt.
//
// Returns (nil, 0, nil) when no line carries the token at all, or the file
// does not exist — there was never an issue to file. Returns (nil, 0, err)
// only on a genuine I/O error other than file-not-found or an oversized
// skipped line; a token-bearing line that fails to verify is dropped from
// the payloads and counted in rejectedCount, never itself surfaced as err,
// since a caller has no single result slot to attach a per-line warning to
// the way the singleton scanners' notVerifiedErr does.
func AllIssueIntentLinesInLog(path, expectedNonce string) ([]string, int, error) {
	return scanSignalLines(path, IssueIntentToken, expectedNonce, true)
}

// lastVerifiedSignalInLog is the shared "last verifying signal wins" scanner
// backing both LastCommentLineInLog and LastPRIntentInLog: among lines
// carrying token, the last one that actually verifies (right nonce, valid
// strict base64, via parseSignalLine) wins over a later line that merely
// carries the token without verifying — an untrusted issue/comment author's
// echo of either channel's token, since they wrote their text before this
// run's nonce was minted, must not be able to shadow an earlier genuine
// line. notVerifiedErr is the per-channel error text returned when at least
// one token-bearing line was found but none verified. The returned int is
// the count of token-bearing lines that failed to verify (rejectedCount),
// letting a caller distinguish a single spoof/echo attempt from many.
func lastVerifiedSignalInLog(path, token, expectedNonce, notVerifiedErr string) (string, bool, int, error) {
	matches, rejectedCount, err := scanSignalLines(path, token, expectedNonce, false)
	if err != nil {
		return "", false, 0, err
	}
	if len(matches) > 0 {
		return matches[len(matches)-1], true, rejectedCount, nil
	}
	if rejectedCount > 0 {
		return "", false, rejectedCount, errors.New(notVerifiedErr)
	}
	return "", false, 0, nil
}

// scanSignalLines is the one shared scanning skeleton backing all three
// public signal scanners (LastCommentLineInLog, LastPRIntentInLog,
// AllIssueIntentLinesInLog, issue #2976): a single logscan.ForEachLine pass
// that, for every token-bearing line, calls parseSignalLine once to verify
// nonce+base64 and looksLikeSignalAttempt once to decide whether a
// non-verifying line is a genuine (if malformed or spoofed) attempt worth
// counting, versus a bare prose mention or one-field doc example that isn't.
//
// collectAll switches between the two selection modes the three callers
// need: false is "last verifying line wins" (LastCommentLineInLog,
// LastPRIntentInLog via lastVerifiedSignalInLog, which takes matches'
// final element), true is "collect every verifying line, deduped by decoded
// payload identity, in encounter order" (AllIssueIntentLinesInLog's 1-to-many
// contract, issue #2018/#2068). Both modes share the identical verify/count
// decision per line; only what happens to a verifying payload differs.
//
// Returns (nil, 0, nil) when path does not exist. Returns (matches, count,
// err) only on a genuine I/O error other than file-not-found or an oversized
// skipped line — a non-verifying line is never itself an error here; that
// distinction (found vs never-verified) is a caller's job, since lastwins and
// collect-all callers react to rejectedCount differently.
func scanSignalLines(path, token, expectedNonce string, collectAll bool) (matches []string, rejectedCount int, err error) {
	// seen dedups collectAll's collected payloads by decoded byte identity —
	// see AllIssueIntentLinesInLog's doc comment for why the subagent Filer
	// echoes each intent line twice (issue #2068). Left nil (and unused) in
	// last-wins mode, where every caller only ever wants the final match.
	var seen map[string]bool
	if collectAll {
		seen = make(map[string]bool)
	}
	scanErr := logscan.ForEachLine(path, logscan.SkipOversized, func(line string) {
		if !containsToken(line, token) {
			return
		}
		if body, ok := parseSignalLine(line, token, expectedNonce); ok {
			if collectAll {
				if seen[body] {
					return
				}
				seen[body] = true
			}
			matches = append(matches, body)
			return
		}
		if looksLikeSignalAttempt(line, token) {
			rejectedCount++
		}
	})
	if scanErr != nil {
		if errors.Is(scanErr, os.ErrNotExist) {
			return nil, 0, nil
		}
		return nil, 0, scanErr
	}
	return matches, rejectedCount, nil
}

// looksLikeSignalAttempt reports whether line is a genuine (if malformed or
// spoofed) attempt at the "<token> <nonce> <base64-payload>" grammar rather
// than prose that merely names the token or a one-field doc example: the token
// must lead the line (nothing but whitespace, or a stream-json-escaped newline,
// before it) and be followed by at least the two fields a real signal carries.
// Only such a line, when it fails to verify, is the echo/spoof case worth
// warning about (issue #2089).
func looksLikeSignalAttempt(line, token string) bool {
	idx := tokenIndex(line, token)
	if idx < 0 {
		return false
	}
	prefix := strings.TrimSpace(line[:idx])
	if prefix != "" && !strings.HasSuffix(prefix, "\\n") {
		return false
	}
	return len(strings.Fields(line[idx+len(token):])) >= 2
}

// parseSignalLine extracts and strictly decodes the payload of a
// single-line "<token> <nonce> <base64-payload>" control signal — the
// shared grammar lastVerifiedSignalInLog pins to one token per call, on
// behalf of both LastCommentLineInLog and LastPRIntentInLog. line must
// carry expectedNonce as the field structurally following
// the token (word-bounded via strings.Fields, so an empty expectedNonce can
// never match), and the base64 payload — the field after that — is decoded
// with the standard strict decoder, rejecting any decode error outright
// rather than stripping whitespace or best-effort decoding.
func parseSignalLine(line, token, expectedNonce string) (string, bool) {
	idx := tokenIndex(line, token)
	if idx < 0 {
		return "", false
	}
	// fields[0] must equal expectedNonce exactly: strings.Fields already
	// splits on whitespace, so this is itself a word-bounded check, and an
	// empty expectedNonce can never match since Fields never yields an
	// empty token -- no separate LineHasNonce gate needed.
	fields := strings.Fields(line[idx+len(token):])
	if len(fields) < 2 || fields[0] != expectedNonce {
		return "", false
	}
	payload := base64AlphabetPrefix(fields[1])
	decoded, err := base64.StdEncoding.Strict().DecodeString(payload)
	if err != nil {
		return "", false
	}
	return string(decoded), true
}

// LineHasNonce reports whether line carries expected as a standalone token
// (issue #1937) — the shared check a caller uses to tell a genuine
// control-signal line, produced by this run's own Box, from one an
// untrusted issue/comment author echoed into the log verbatim: the author
// writes their text before the per-run nonce is minted, so they cannot know
// its value. Word-bounded via containsToken, so a longer token that merely
// contains expected as a substring does not false-positive. An empty
// expected never matches.
func LineHasNonce(line, expected string) bool {
	if expected == "" {
		return false
	}
	return containsToken(line, expected)
}

// containsToken reports whether line contains token as a standalone word,
// not merely as a substring of a longer identifier (e.g. "SPINDRIFT_OUTCOMES"
// or "MY_SPINDRIFT_OUTCOME_THING" must not match).
func containsToken(line, token string) bool {
	return tokenIndex(line, token) >= 0
}

// tokenIndex returns the index of token's first standalone-word occurrence
// in line, or -1 if none exists. Standalone means not preceded or followed
// by an identifier character (see isTokenChar), so a longer identifier that
// merely contains token as a substring never matches. A literal `\n`
// (backslash then 'n') immediately before the token counts as a left
// boundary too, alongside a genuine non-token-char: it's JSON's escaping of
// a real newline the Box's own text wrote right before the token — e.g. a
// line of narration flowing straight into a control-signal line within the
// same stream-json text field — and a real newline is unambiguously a
// boundary, so its escaped form must be too. Without this, the escaped
// sequence's trailing 'n' (itself a token char) would look like it extends
// the token into a longer identifier and reject a placement no different
// from the token simply starting its own physical line.
func tokenIndex(line, token string) int {
	for start := 0; ; {
		i := strings.Index(line[start:], token)
		if i < 0 {
			return -1
		}
		begin := start + i
		end := begin + len(token)
		leftOK := begin == 0 || !isTokenChar(line[begin-1]) ||
			(line[begin-1] == 'n' && begin >= 2 && line[begin-2] == '\\')
		rightOK := end == len(line) || !isTokenChar(line[end])
		if leftOK && rightOK {
			return begin
		}
		start = begin + 1
	}
}

func isTokenChar(b byte) bool {
	return b == '_' || ('a' <= b && b <= 'z') || ('A' <= b && b <= 'Z') || ('0' <= b && b <= '9')
}

// stripToken reports whether line begins with token followed by a space or a
// colon (the tolerated delimiters), and returns the remainder after the
// delimiter for field extraction.
func stripToken(line, token string) (string, bool) {
	if rest, ok := strings.CutPrefix(line, token+" "); ok {
		return rest, true
	}
	if rest, ok := strings.CutPrefix(line, token+":"); ok {
		return rest, true
	}
	return "", false
}

// tokenField extracts the value of key=<val> from a space-delimited line.
// val ends at the next space; use tailField for the note field.
func tokenField(line, key string) string {
	prefix := key + "="
	for _, tok := range strings.Fields(line) {
		if strings.HasPrefix(tok, prefix) {
			return tok[len(prefix):]
		}
	}
	return ""
}

// tailField returns everything after the first " key=" in line, allowing the
// value to contain spaces and '=' (used for the note field).
func tailField(line, key string) string {
	marker := " " + key + "="
	if idx := strings.Index(line, marker); idx >= 0 {
		return line[idx+len(marker):]
	}
	return ""
}

// noteField is tailField("note") with the trailing " nonce=<value>" field
// (issue #1939) stripped back off, so it never ends up inside Note: the
// grammar places nonce last, after note's own greedy tail, and a run's note
// gets posted as a public comment on status=blocked (settle.postBlockedNoteComment)
// — leaking the nonce there would let a comment author replay it against a
// later retry of the same Dispatch, which reuses one nonce across all its
// attempts. A trailing "nonce=<value>" only counts as the field, not as note
// text that happens to contain it, when <value> itself has no spaces —
// exactly the shape a genuine, single-token nonce always has.
func noteField(line string) string {
	v := tailField(line, "note")
	const marker = " nonce="
	if idx := strings.LastIndex(v, marker); idx >= 0 {
		if nonce := v[idx+len(marker):]; nonce != "" && !strings.Contains(nonce, " ") {
			return v[:idx]
		}
	}
	return v
}
