// Package outcome owns the SPINDRIFT_OUTCOME grammar, parsing, and log scan.
// It is the single source of truth for the per-Box result contract between
// the Agent and the Harness (see CONTEXT.md — Outcome line).
package outcome

import (
	"encoding/base64"
	"errors"
	"fmt"
	"os"
	"strings"

	"spindrift.dev/launcher/internal/logscan"
)

// Token is the exact SPINDRIFT_OUTCOME marker literal. ADR 0035: the
// orchestrator's scanPassLog greps a rendered pass log for this literal via
// ParseAnywhere, and issue-prompt.md's OUTCOME contract must keep emitting it
// verbatim -- rewording either side without the other silently collapses the
// multi-pass loop to single-pass on ORCHESTRATOR_ENABLED runs. Exported so
// that guard (cmd/launcher/orchestrator's TestPromptMarkersMatchScanner) and
// this package's own Parse/ParseAnywhere/lastInLog share one literal instead
// of each redeclaring it. The literal itself comes from the generated
// markerChannelOutcomeToken (markerchannels_gen.go, issue #2974), the single
// source of truth lib/prompt-contract.nix's markerChannels registry renders.
const Token = markerChannelOutcomeToken

// PRIntentToken is the exact SPINDRIFT_PR_INTENT marker literal (issue
// #2045, the #2036 fix): a read-only Box's draft-PR title/body hand-off,
// scanned host-side by LastPRIntentInLog below and, in-box, by
// entrypoint.sh's own required-marker-gate row that resumes the session
// once when this marker never showed up on a status=ready run. Exported so
// the marker-contract parity guard (cmd/launcher/orchestrator's
// TestPromptMarkersMatchScanner) can pin the two PR-intent-emitting
// fragments (open-pr-create-outbox.md, if-blocked-pr-outbox.md) against
// this one literal instead of a hardcoded string of its own. The literal
// itself comes from the generated markerChannelPRIntentToken
// (markerchannels_gen.go, issue #2974).
const PRIntentToken = markerChannelPRIntentToken

// CommentToken is the exact SPINDRIFT_COMMENT marker literal (issue #1940):
// the mid-run comment-relay channel LastCommentLineInLog below scans for.
// Newly exported (issue #2974) so a marker-contract parity guard can
// reference this generated-backed const instead of a hand-typed literal of
// its own; the literal itself comes from the generated
// markerChannelCommentToken (markerchannels_gen.go).
const CommentToken = markerChannelCommentToken

// IssueIntentToken is the exact SPINDRIFT_ISSUE_INTENT marker literal (issue
// #2018): the file-an-issue relay channel AllIssueIntentLinesInLog below
// scans for. Newly exported and promoted to package level (issue #2974, it
// was previously a function-local const) so a marker-contract parity guard
// can reference this generated-backed const instead of a hand-typed literal
// of its own; the literal itself comes from the generated
// markerChannelIssueIntentToken (markerchannels_gen.go).
const IssueIntentToken = markerChannelIssueIntentToken

// ReviewVerdictToken is the bare SPINDRIFT review-verdict channel token
// (issue #2974) -- distinct from the two full field-shape values
// orchestrator's VerdictApprove/VerdictBlock compose from it ("VERDICT:
// APPROVE" / "VERDICT: BLOCK"). Exported so orchestrator, a different
// package that cannot see the generated markerChannelReviewVerdictToken
// const (unexported, package outcome), can still compose its own verdict
// literals from the one generated-backed source instead of redeclaring the
// bare token itself.
const ReviewVerdictToken = markerChannelReviewVerdictToken

// Outcome is the machine-readable result written by a Box as its final line.
// Grammar: SPINDRIFT_OUTCOME issue=<num> landing=<landing-ref> status=<status> note=<text>
// Note may contain spaces and '='; all other fields are space-delimited tokens.
type Outcome struct {
	Issue string
	// Landing is the landing reference: a PR URL under CODE_FORGE=github, a
	// branch ref (e.g. "agent/issue-42") under the push-only CODE_FORGE=git,
	// or a verdict-comment URL for the research dispatch kind.
	Landing string
	Status  string // ready | blocked | failed | merged | …
	// Synthetic flags a line generated by the outcome backstop (ADR 0036)
	// rather than authored by the driver — set only on the synthetic
	// backstop line (issue #2223).
	Synthetic bool
	Note      string // free text; may contain spaces and '='
}

// ErrNearMiss marks a Parse error where the SPINDRIFT_OUTCOME token is
// present in the line but the line still fails to parse — required fields
// missing or malformed, or the token embedded mid-sentence rather than
// leading a standalone line. Separable from the token being entirely absent
// so callers (e.g. a resume nudge) can react to "almost got it" differently
// from "never tried".
var ErrNearMiss = errors.New("outcome: near-miss")

// IsNearMiss reports whether err was returned because a SPINDRIFT_OUTCOME
// token was present but the line did not parse, as opposed to the token
// being entirely absent.
func IsNearMiss(err error) bool {
	return errors.Is(err, ErrNearMiss)
}

// Parse parses a single SPINDRIFT_OUTCOME line.
// Returns an error if the line lacks the required prefix or is missing the
// landing or status fields. The latter case, and a line where the token
// appears but not as a standalone-line prefix, are wrapped in ErrNearMiss
// (see IsNearMiss). That leading-token requirement belongs to lastInLog,
// which scans whole logs and only ever treats a leading-token line as a
// candidate, so a bare mention in prose never reaches Parse from that path;
// a caller handing Parse a single already-selected line makes that
// leading-token decision itself.
func Parse(line string) (Outcome, error) {
	line = strings.TrimSpace(line)
	rest, ok := stripToken(line, Token)
	if !ok {
		if containsToken(line, Token) {
			return Outcome{}, fmt.Errorf("%w: line contains %q but does not match the standalone-line grammar", ErrNearMiss, Token)
		}
		return Outcome{}, fmt.Errorf("outcome: line missing %q prefix", Token+" ")
	}
	o := Outcome{
		Issue:     tokenField(rest, "issue"),
		Landing:   tokenField(rest, "landing"),
		Status:    tokenField(rest, "status"),
		Synthetic: tokenField(rest, "synthetic") == "true",
		Note:      noteField(rest),
	}
	if o.Landing == "" {
		return Outcome{}, fmt.Errorf("%w: missing landing field", ErrNearMiss)
	}
	if o.Status == "" {
		return Outcome{}, fmt.Errorf("%w: missing or empty status field", ErrNearMiss)
	}
	return o, nil
}

// Line returns the canonical SPINDRIFT_OUTCOME representation of o.
// Parse(o.Line()) == o for all valid Outcomes.
func (o Outcome) Line() string {
	if o.Synthetic {
		return fmt.Sprintf("%s issue=%s landing=%s status=%s synthetic=true note=%s",
			Token, o.Issue, o.Landing, o.Status, o.Note)
	}
	return fmt.Sprintf("%s issue=%s landing=%s status=%s note=%s",
		Token, o.Issue, o.Landing, o.Status, o.Note)
}

// ParseAnywhere finds the SPINDRIFT_OUTCOME token anywhere in line -- not
// only as a leading prefix, per Parse's own stricter grammar -- and parses
// the outcome starting there. For a caller scanning already-rendered
// transcript text rather than a raw box log (issue #1998's orchestrator,
// reading a pass's own log through the claude Driver's RenderTranscript,
// which prefixes every line with a "[role] " tag): the token is genuinely
// present but never leads the line the way a Box's own bare final-message
// line does, so Parse alone would always report ErrNearMiss. Returns
// (Outcome{}, false) when the token is absent, or the text from that point
// on fails to parse.
func ParseAnywhere(line string) (Outcome, bool) {
	idx := tokenIndex(line, Token)
	if idx < 0 {
		return Outcome{}, false
	}
	o, err := Parse(line[idx:])
	if err != nil {
		return Outcome{}, false
	}
	return o, true
}

// lastInLog scans the file at path for the SPINDRIFT_OUTCOME token and
// parses the result via Parse, so the same colon/whitespace tolerance and
// near-miss classification apply. Only the last line that leads with the
// token (a genuine attempt at the grammar, however it fares in Parse) is a
// candidate; a line that merely carries the token mid-sentence or mid-JSON
// — e.g. a tool_result echo of issue/comment text — is not, no matter how
// many field markers (issue=/landing=/status=/note=) it happens to carry.
// Lines larger than the 4 MiB scan buffer are skipped rather than aborting
// the scan.
//
// Returns (Outcome{}, false, nil) when no leading-token line is present, or
// the file does not exist. Returns (Outcome{}, false, err) when the chosen
// candidate line fails to parse — err satisfies IsNearMiss in that case —
// or on an I/O error other than file-not-found or oversized lines.
//
// lastInLog applies no nonce gate (ADR 0039, issue #2274): unlike the
// mid-run signal channels (SPINDRIFT_COMMENT, SPINDRIFT_PR_INTENT,
// SPINDRIFT_ISSUE_INTENT), the outcome line is a single, final,
// end-of-Box-lifetime signal the launcher reads only after the Box has
// exited, so there is no later mid-run window left for an untrusted
// issue/comment author's echoed line to race ahead of. A leading-token line
// is a candidate regardless of any nonce= field it may or may not carry.
func lastInLog(path string) (o Outcome, found bool, err error) {
	var lastLeading string
	scanErr := logscan.ForEachLine(path, logscan.SkipOversized, func(line string) {
		if _, ok := stripToken(strings.TrimSpace(line), Token); ok {
			lastLeading = line
		}
	})
	if scanErr != nil {
		if errors.Is(scanErr, os.ErrNotExist) {
			return Outcome{}, false, nil
		}
		return Outcome{}, false, scanErr
	}

	if lastLeading == "" {
		return Outcome{}, false, nil
	}
	o, err = Parse(lastLeading)
	if err != nil {
		return Outcome{}, false, err
	}
	return o, true, nil
}

// SelfReport is the driver's own last genuine (non-synthetic) leading-token
// SPINDRIFT_OUTCOME self-report, surfaced distinctly from the authoritative
// parsed outcome so a synthetic backstop line (ADR 0036) can never shadow it
// via last-line-wins (issue #2223). This is the read-only signal the
// automatic-adoption and manual-recover tickets consume; it changes no
// dispatch, PR, or label behaviour on its own.
//
// Status is the driver's self-reported status: the status= field's value when
// the line parses the full grammar, otherwise the bare word immediately
// following the token delimiter for a leading-token near-miss like
// `SPINDRIFT_OUTCOME: success` a model emits when it paraphrases the grammar.
// Outcome and Parsed are set only when the line parsed the full grammar.
//
// lastSelfReportInLog is unauthenticated and advisory: the motivating
// near-miss carries no nonce at all (the paraphrasing model dropped every
// field), and the outcome path itself no longer gates on a nonce either (ADR
// 0039, issue #2274). A consumer that acts on the self-report owns weighing
// that trust, exactly as the prefactor framing intends.
type SelfReport struct {
	Raw     string  // the raw driver-authored leading-token line
	Status  string  // best-effort self-reported status (field value or bare word)
	Outcome Outcome // populated only when Parsed
	Parsed  bool    // whether Raw parsed the full SPINDRIFT_OUTCOME grammar
}

// lastSelfReportInLog returns the driver's last genuine (non-synthetic)
// leading-token SPINDRIFT_OUTCOME self-report from the log at path. It scans
// for the last line that leads with the token (stripToken tolerance: `TOKEN `
// or `TOKEN:`) and is NOT flagged synthetic=true, so the backstop's own
// appended synthetic line — which wins lastInLog's last-line-wins — is
// skipped here and the driver's real signal survives. See SelfReport for the
// trust caveat.
//
// Returns (SelfReport{}, false, nil) when no non-synthetic leading-token line
// exists, or the file does not exist. Returns (SelfReport{}, false, err) only
// on an I/O error other than file-not-found or an oversized skipped line.
func lastSelfReportInLog(path string) (report SelfReport, found bool, err error) {
	var last string
	scanErr := logscan.ForEachLine(path, logscan.SkipOversized, func(line string) {
		trimmed := strings.TrimSpace(line)
		if _, ok := stripToken(trimmed, Token); !ok {
			return
		}
		if tokenField(trimmed, "synthetic") == "true" {
			return
		}
		last = trimmed
	})
	if scanErr != nil {
		if errors.Is(scanErr, os.ErrNotExist) {
			return SelfReport{}, false, nil
		}
		return SelfReport{}, false, scanErr
	}
	if last == "" {
		return SelfReport{}, false, nil
	}
	return selfReportFromLine(last), true, nil
}

// LastSelfReport returns the driver's last genuine (non-synthetic)
// leading-token SPINDRIFT_OUTCOME self-report from the log at path -- the
// same self-report tier lastSelfReportInLog backs, kept reachable from
// outside this package under its own name because a caller legitimately
// wants this signal unconditionally, alongside a possibly-also-present
// genuine outcome, rather than only as Resolve's own last-resort fallback
// when the genuine tier comes up empty (Resolve's self-report tier is only
// reachable when the genuine tier found nothing at all). dispatch's
// Result.SelfReport (retry.go's outcomeResult, one log) and `spindrift
// recover`'s ResolveFromLogs (multiple logs, its own last-pass-wins
// walk) are exactly this: an independent signal read alongside
// Result.Outcome, never an either/or against it. Exposing this single tier
// on its own does not let a caller reimplement, or diverge from, the
// genuine-vs-synthetic-vs-self-report PRECEDENCE Resolve exists to guard --
// this always returns the self-report signal, full stop, never adjudicating
// it against a genuine or synthetic outcome the way Resolve's tier walk
// does.
//
// Returns (SelfReport{}, false, nil) when no non-synthetic leading-token line
// exists, or the file does not exist. Returns (SelfReport{}, false, err) only
// on an I/O error other than file-not-found or an oversized skipped line.
func LastSelfReport(path string) (report SelfReport, found bool, err error) {
	return lastSelfReportInLog(path)
}

// selfReportFromLine builds a SelfReport from a leading-token line: a full
// parse when the grammar holds, otherwise a best-effort bare status word
// (the first whitespace-delimited field after the token delimiter that is
// not itself a key=value field).
func selfReportFromLine(line string) SelfReport {
	r := SelfReport{Raw: line}
	if o, perr := Parse(line); perr == nil {
		r.Outcome = o
		r.Parsed = true
		r.Status = o.Status
		return r
	}
	if rest, ok := stripToken(line, Token); ok {
		fields := strings.Fields(rest)
		if len(fields) > 0 && !strings.Contains(fields[0], "=") {
			r.Status = fields[0]
		}
	}
	return r
}

// Provenance identifies which tier of the SPINDRIFT_OUTCOME selection policy
// produced a Resolved value: an authored line the driver itself emitted
// (ProvenanceGenuine), the outcome backstop's own appended line when the
// driver never emitted one (ProvenanceSynthetic, ADR 0036), or the driver's
// unauthenticated self-report fallback (ProvenanceSelfReport) — the last
// resort Resolve falls back to only when no nonce-gated outcome line was
// found at all.
type Provenance string

const (
	// ProvenanceGenuine is a driver-authored, non-synthetic outcome line.
	ProvenanceGenuine Provenance = "genuine"
	// ProvenanceSynthetic is the outcome backstop's appended line (ADR 0036,
	// issue #2223) — the driver itself never emitted an outcome.
	ProvenanceSynthetic Provenance = "synthetic"
	// ProvenanceSelfReport is the driver's unauthenticated self-report
	// fallback (see SelfReport) — not yet produced by Resolve.
	ProvenanceSelfReport Provenance = "self-report"
)

// PassLog names one pass's log file for Resolve to scan, in the order the
// passes ran. It mirrors dispatch.PassLog's {Label, Path} shape: outcome
// cannot import dispatch (that would cycle back through outcome), so this is
// its own copy of that shape and a dispatch caller converts its own
// []dispatch.PassLog to []outcome.PassLog, field for field, at the call
// site.
type PassLog struct {
	Label string
	Path  string
}

// Resolved is the result of Resolve: the outcome Resolve selected, which
// tier of the selection policy produced it, and the normalized dispatch
// kind the caller asked about.
type Resolved struct {
	Outcome    Outcome
	Provenance Provenance
	// Kind is the normalized dispatch kind ("" input becomes "work"). It is
	// carried through unchanged and does not affect selection: ADR 0022
	// rejected a kind-specific outcome grammar, so Resolve is kind-agnostic
	// by design.
	Kind  string
	Found bool
	// SelfReport and SelfReportFound carry the driver's unauthenticated
	// self-report signal alongside whichever tier actually won the outcome
	// above. They are populated on every Resolved with Found true —
	// including when Provenance is ProvenanceGenuine or ProvenanceSynthetic
	// and the self-report tier was never consulted for Outcome/Provenance
	// itself — not only when the self-report tier is Resolve's own
	// last-resort fallback (Provenance == ProvenanceSelfReport). This lets a
	// caller see both signals at once: e.g. a later synthetic backstop line
	// can win the Outcome/Provenance above while an earlier driver-authored
	// self-report line (parsed or not) is still available via SelfReport for
	// adoption logic that weighs the two against each other. SelfReportFound
	// is false, and SelfReport is its zero value, when no self-report line
	// was found in any log, and both stay zero-valued on a Resolved with
	// Found false (neither tier found anything).
	SelfReport      SelfReport
	SelfReportFound bool
	// SelfReportError carries the last I/O error lastSelfReportAcrossLogs hit
	// while scanning logs for the self-report tier (issue #2343 slice 1). It
	// is distinct from Resolve's own returned error, which reflects only the
	// genuine/synthetic tier's near-miss/error -- the self-report walk still
	// never aborts on this error and keeps trying later logs (see
	// lastSelfReportAcrossLogs), so this field is purely observability: it
	// does not change which report, if any, ends up on SelfReport above. Nil
	// when no I/O error occurred while scanning for a self-report.
	SelfReportError error
}

// Resolve is the single seam that picks among the tiers of the
// SPINDRIFT_OUTCOME selection policy — a genuine driver-authored line, the
// outcome backstop's synthetic line, and, as a last resort, the driver's
// unauthenticated self-report fallback — and returns which tier won as
// Resolved.Provenance. It exists so no caller has to reimplement, or
// accidentally diverge from, that precedence by calling the underlying
// per-log scanners directly.
//
// Resolve walks logs in order calling lastInLog(log.Path), keeping
// the last log that reports a match ("last pass wins", the same precedence
// ResolveFromLogs already applies across passes). A parse error on
// the chosen candidate line (lastInLog's own near-miss contract) propagates
// as Resolve's error. If a match was found, Resolved.Provenance is
// ProvenanceSynthetic when the winning line's Outcome.Synthetic is true,
// otherwise ProvenanceGenuine. The outcome path applies no nonce gate (ADR
// 0039, issue #2274): its freshness boundary is structural, so every
// leading-token line is a candidate regardless of any nonce= field it
// carries.
//
// Regardless of whether the genuine/synthetic tier found a winner, Resolve
// also always walks logs calling lastSelfReportInLog(log.Path) — the
// self-report tier is likewise ungated (see SelfReport) — keeping the last
// log with a report ("last pass wins", same precedence as the
// genuine/synthetic walk). That report is populated on Resolved.SelfReport /
// Resolved.SelfReportFound on every Found-true return, whether or not it also
// drove Resolved.Outcome/Provenance below.
//
// If the genuine/synthetic tier found no leading-token line at all (neither a
// clean match nor a near-miss), Resolve does not give up: the self-report
// walk above becomes Resolve's own last-resort tier too. When a report was
// found and report.Parsed is true, Resolved.Outcome is report.Outcome in
// full and Provenance is ProvenanceSelfReport. When one is found but NOT
// Parsed, Resolved.Outcome only has Status populated from report.Status —
// Issue, Landing, and Note stay zero. A caller reading Resolved.Outcome.Status
// after a ProvenanceSelfReport result must not assume the rest of Outcome is
// meaningful. Note that with the nonce gate retired (ADR 0039, issue #2274) a
// bare-word leading line like "SPINDRIFT_OUTCOME: success" is now
// lastInLog's own near-miss, so it surfaces as Resolve's near-miss error
// above rather than reaching this self-report fallback.
//
// Only when neither tier yields anything does Resolve return
// Resolved{Found: false} with no error — matching this package's existing
// not-found-is-not-an-error convention throughout.
//
// kind is normalized ("" becomes "work") and stored on Resolved.Kind
// regardless of which tier won; it never changes selection.
func Resolve(logs []PassLog, kind string) (Resolved, error) {
	if kind == "" {
		kind = "work"
	}

	var (
		winner  Outcome
		found   bool
		lastErr error
	)
	for _, log := range logs {
		o, ok, err := lastInLog(log.Path)
		switch {
		case err != nil:
			// A later log's near-miss candidate (issue-shaped line present,
			// but unparseable) overrides an earlier log's successful match,
			// same as a later log's successful match would — last pass wins
			// applies to a failed attempt too, not only a clean one.
			lastErr = err
			found = false
		case ok:
			winner = o
			found = true
			lastErr = nil
		}
		// Neither case: this log had no candidate at all, so it leaves the
		// running state from prior logs untouched.
	}
	// The self-report walk runs unconditionally, regardless of whether the
	// genuine/synthetic tier above found a winner or errored on a near-miss,
	// so Resolved always carries the driver's self-report signal alongside
	// whichever tier won -- not only as this function's own last-resort
	// fallback tier (issue #2268 slice 1). A caller that only cares about the
	// self-report signal (e.g. `spindrift recover`'s relayed-branch adopt
	// arm) can read Resolved.SelfReport/SelfReportFound off the zero-Outcome
	// Resolved this function returns alongside a near-miss error, rather than
	// losing that signal entirely just because the authoritative tier
	// couldn't settle on a clean winner.
	report, reportFound, reportErr := lastSelfReportAcrossLogs(logs)

	if lastErr != nil {
		return Resolved{Kind: kind, SelfReport: report, SelfReportFound: reportFound, SelfReportError: reportErr}, lastErr
	}

	if found {
		provenance := ProvenanceGenuine
		if winner.Synthetic {
			provenance = ProvenanceSynthetic
		}
		return Resolved{
			Outcome:         winner,
			Provenance:      provenance,
			Kind:            kind,
			Found:           true,
			SelfReport:      report,
			SelfReportFound: reportFound,
			SelfReportError: reportErr,
		}, nil
	}

	if !reportFound {
		return Resolved{Kind: kind, SelfReportError: reportErr}, nil
	}
	if report.Parsed {
		return Resolved{
			Outcome:         report.Outcome,
			Provenance:      ProvenanceSelfReport,
			Kind:            kind,
			Found:           true,
			SelfReport:      report,
			SelfReportFound: true,
			SelfReportError: reportErr,
		}, nil
	}
	return Resolved{
		Outcome:         Outcome{Status: report.Status},
		Provenance:      ProvenanceSelfReport,
		Kind:            kind,
		Found:           true,
		SelfReport:      report,
		SelfReportFound: true,
		SelfReportError: reportErr,
	}, nil
}

// lastSelfReportAcrossLogs walks logs in order calling
// lastSelfReportInLog(log.Path) for each, keeping the last one that reports a
// match — the same "last pass wins" precedence Resolve's genuine/synthetic
// walk and dispatch.ResolveFromLogs both apply. lastSelfReportInLog only
// errors on a genuine I/O failure (never a parse failure — a self-report has
// no near-miss shape to fail), and this is already the last-resort fallback
// tier, so a single unreadable log is still silently skipped here rather than
// aborting the whole selection — the walk keeps trying later logs exactly as
// before. The one change is that the error is no longer discarded outright:
// the last I/O error seen anywhere in the walk (independent of which log,
// if any, ultimately wins) is now returned to the caller instead, so it's
// observable rather than lost.
func lastSelfReportAcrossLogs(logs []PassLog) (SelfReport, bool, error) {
	var (
		winner  SelfReport
		found   bool
		lastErr error
	)
	for _, log := range logs {
		report, ok, err := lastSelfReportInLog(log.Path)
		if err != nil {
			lastErr = err
		}
		if err != nil || !ok {
			continue
		}
		winner = report
		found = true
	}
	return winner, found, lastErr
}

// LastCommentLineInLog scans the file at path for the last line carrying the
// SPINDRIFT_COMMENT token and decodes its single-line grammar: SPINDRIFT_COMMENT
// <nonce> <base64-encoded-body> (issue #1940). See lastVerifiedSignalInLog for
// the verify-then-prefer selection semantics, which differ from lastInLog's
// always-take-the-last-line behavior for SPINDRIFT_OUTCOME.
//
// A stream-json JSONL box log collapses a printed line's trailing newline
// into a literal `\n` escape butted directly against the base64 payload with
// no whitespace in between; the payload is taken as the longest run of valid
// base64 characters after the nonce field, so that trailing JSON escaping
// never reaches the decoder.
//
// Returns ("", false, 0, nil) when no line carries the token at all, or the
// file does not exist — there was never a comment to relay. Returns ("",
// false, rejectedCount, err) only when every token-bearing line fails to
// verify — a spoof attempt or a corrupted line, for the caller to log;
// never treated as no-comment. rejectedCount is how many token-bearing
// lines failed to verify. Returns (body, true, rejectedCount, nil) from the
// last line that verifies, even if earlier or later non-verifying lines
// also carry the token — rejectedCount still reflects those, but they are
// otherwise dropped silently rather than reported, since the one-result
// return contract can't carry both a successful relay and a warning at
// once, and the successful relay is what matters.
func LastCommentLineInLog(path, expectedNonce string) (string, bool, int, error) {
	return lastVerifiedSignalInLog(path, CommentToken, expectedNonce,
		"comment line found but did not verify: nonce mismatch or malformed payload")
}

// base64AlphabetPrefix returns the longest prefix of s consisting solely of
// standard-base64 alphabet characters (A-Z, a-z, 0-9, '+', '/', '=') — the
// boundary a JSON-escaped trailing `\n` (a literal backslash followed by
// 'n', neither a base64 character) or other JSON syntax never crosses.
func base64AlphabetPrefix(s string) string {
	for i := 0; i < len(s); i++ {
		if !isBase64Char(s[i]) {
			return s[:i]
		}
	}
	return s
}

func isBase64Char(b byte) bool {
	return ('A' <= b && b <= 'Z') || ('a' <= b && b <= 'z') || ('0' <= b && b <= '9') || b == '+' || b == '/' || b == '='
}

// LastPRIntentInLog scans the file at path for the last line carrying the
// SPINDRIFT_PR_INTENT token and decodes its single-line grammar:
// SPINDRIFT_PR_INTENT <nonce> <base64-payload> (issue #1938) — the draft-PR
// title and body a read-only Box hands the launcher in place of its own
// `gh pr create` (issue #1919), replacing the retired
// SPINDRIFT_PR_INTENT_BEGIN/END block the same way LastCommentLineInLog
// replaced LastCommentInLog: a stream-json JSONL box log collapses a
// multi-line block onto one physical line, so an exact-line marker scan
// never finds it (issue #1921's dogfood failure).
//
// See lastVerifiedSignalInLog for the verify-then-prefer selection semantics,
// shared with LastCommentLineInLog.
//
// The decoded payload is the same "title\n\nbody" shape the retired block
// held: the first line is the PR title and the remainder, after a blank
// line, is the PR body; splitting title from body remains the caller's
// concern.
//
// Returns ("", false, 0, nil) when no line carries the token at all, or the
// file does not exist — there was never a PR-intent to relay. Returns ("",
// false, rejectedCount, err) only when every token-bearing line fails to
// verify — a spoof attempt or a corrupted line, for the caller to log;
// never conflated with no-PR-intent-found. rejectedCount is how many
// token-bearing lines failed to verify. Returns (payload, true,
// rejectedCount, nil) from the last line that verifies, even if a later,
// non-verifying line also carries the token.
func LastPRIntentInLog(path, expectedNonce string) (string, bool, int, error) {
	return lastVerifiedSignalInLog(path, PRIntentToken, expectedNonce,
		"PR-intent line found but did not verify: nonce mismatch or malformed payload")
}

// AllIssueIntentLinesInLog scans the file at path for every line carrying
// the SPINDRIFT_ISSUE_INTENT token and decodes each verifying line's
// single-line grammar: SPINDRIFT_ISSUE_INTENT <nonce> <base64-payload>
// (issue #2018) — a read-only Box's file-an-issue request, host-mediated the
// same way LastCommentLineInLog/LastPRIntentInLog relay a comment or
// draft-PR intent. Unlike those two singleton "last verifying line wins"
// scanners, issue filing is 1-to-many — a run may want to file several
// issues — so every verifying line's decoded payload is collected, in the
// order encountered, rather than only the last surviving. Payloads are
// deduped by their decoded byte identity (issue #2068): a Filer subagent
// echoes its one intent line twice into the raw stream-json log — once as its
// own `assistant` event, once in the parent's `tool_result` event — and the
// two decode identically, so the second is dropped rather than filed as a
// duplicate issue. A line carrying the token that fails to verify (wrong
// nonce, malformed base64) is dropped from the collected payloads, exactly as
// a non-verifying PR-intent/comment line is dropped from those scanners'
// single result — an untrusted issue/comment author's echo of the token must
// never be mistaken for a genuine filed-issue request — but, unlike the
// silent drop this function used to apply, it is now counted via the
// returned rejectedCount (issue #2976), so a caller can settle-log a warning
// instead of the drop staying entirely invisible. Unlike the deduped payloads
// slice, rejectedCount has no equivalent dedup, so the same #2068 double-echo
// can double-count a single failed relay attempt.
//
// Returns (nil, 0, nil) when no line carries the token at all, or the file
// does not exist — there was never an issue to file. Returns (nil, 0, err)
// only on a genuine I/O error other than file-not-found or an oversized
// skipped line; a token-bearing line that fails to verify is dropped from
// the payloads and counted in rejectedCount, never itself surfaced as err,
// since a caller has no single result slot to attach a per-line warning to
// the way the singleton scanners' notVerifiedErr does.
func AllIssueIntentLinesInLog(path, expectedNonce string) ([]string, int, error) {
	return scanSignalLines(path, IssueIntentToken, expectedNonce, true)
}

// lastVerifiedSignalInLog is the shared "last verifying signal wins" scanner
// backing both LastCommentLineInLog and LastPRIntentInLog: among lines
// carrying token, the last one that actually verifies (right nonce, valid
// strict base64, via parseSignalLine) wins over a later line that merely
// carries the token without verifying — an untrusted issue/comment author's
// echo of either channel's token, since they wrote their text before this
// run's nonce was minted, must not be able to shadow an earlier genuine
// line. notVerifiedErr is the per-channel error text returned when at least
// one token-bearing line was found but none verified. The returned int is
// the count of token-bearing lines that failed to verify (rejectedCount),
// letting a caller distinguish a single spoof/echo attempt from many.
func lastVerifiedSignalInLog(path, token, expectedNonce, notVerifiedErr string) (string, bool, int, error) {
	matches, rejectedCount, err := scanSignalLines(path, token, expectedNonce, false)
	if err != nil {
		return "", false, 0, err
	}
	if len(matches) > 0 {
		return matches[len(matches)-1], true, rejectedCount, nil
	}
	if rejectedCount > 0 {
		return "", false, rejectedCount, errors.New(notVerifiedErr)
	}
	return "", false, 0, nil
}

// scanSignalLines is the one shared scanning skeleton backing all three
// public signal scanners (LastCommentLineInLog, LastPRIntentInLog,
// AllIssueIntentLinesInLog, issue #2976): a single logscan.ForEachLine pass
// that, for every token-bearing line, calls parseSignalLine once to verify
// nonce+base64 and looksLikeSignalAttempt once to decide whether a
// non-verifying line is a genuine (if malformed or spoofed) attempt worth
// counting, versus a bare prose mention or one-field doc example that isn't.
//
// collectAll switches between the two selection modes the three callers
// need: false is "last verifying line wins" (LastCommentLineInLog,
// LastPRIntentInLog via lastVerifiedSignalInLog, which takes matches'
// final element), true is "collect every verifying line, deduped by decoded
// payload identity, in encounter order" (AllIssueIntentLinesInLog's 1-to-many
// contract, issue #2018/#2068). Both modes share the identical verify/count
// decision per line; only what happens to a verifying payload differs.
//
// Returns (nil, 0, nil) when path does not exist. Returns (matches, count,
// err) only on a genuine I/O error other than file-not-found or an oversized
// skipped line — a non-verifying line is never itself an error here; that
// distinction (found vs never-verified) is a caller's job, since lastwins and
// collect-all callers react to rejectedCount differently.
func scanSignalLines(path, token, expectedNonce string, collectAll bool) (matches []string, rejectedCount int, err error) {
	// seen dedups collectAll's collected payloads by decoded byte identity —
	// see AllIssueIntentLinesInLog's doc comment for why the subagent Filer
	// echoes each intent line twice (issue #2068). Left nil (and unused) in
	// last-wins mode, where every caller only ever wants the final match.
	var seen map[string]bool
	if collectAll {
		seen = make(map[string]bool)
	}
	scanErr := logscan.ForEachLine(path, logscan.SkipOversized, func(line string) {
		if !containsToken(line, token) {
			return
		}
		if body, ok := parseSignalLine(line, token, expectedNonce); ok {
			if collectAll {
				if seen[body] {
					return
				}
				seen[body] = true
			}
			matches = append(matches, body)
			return
		}
		if looksLikeSignalAttempt(line, token) {
			rejectedCount++
		}
	})
	if scanErr != nil {
		if errors.Is(scanErr, os.ErrNotExist) {
			return nil, 0, nil
		}
		return nil, 0, scanErr
	}
	return matches, rejectedCount, nil
}

// looksLikeSignalAttempt reports whether line is a genuine (if malformed or
// spoofed) attempt at the "<token> <nonce> <base64-payload>" grammar rather
// than prose that merely names the token or a one-field doc example: the token
// must lead the line (nothing but whitespace, or a stream-json-escaped newline,
// before it) and be followed by at least the two fields a real signal carries.
// Only such a line, when it fails to verify, is the echo/spoof case worth
// warning about (issue #2089).
func looksLikeSignalAttempt(line, token string) bool {
	idx := tokenIndex(line, token)
	if idx < 0 {
		return false
	}
	prefix := strings.TrimSpace(line[:idx])
	if prefix != "" && !strings.HasSuffix(prefix, "\\n") {
		return false
	}
	return len(strings.Fields(line[idx+len(token):])) >= 2
}

// parseSignalLine extracts and strictly decodes the payload of a
// single-line "<token> <nonce> <base64-payload>" control signal — the
// shared grammar lastVerifiedSignalInLog pins to one token per call, on
// behalf of both LastCommentLineInLog and LastPRIntentInLog. line must
// carry expectedNonce as the field structurally following
// the token (word-bounded via strings.Fields, so an empty expectedNonce can
// never match), and the base64 payload — the field after that — is decoded
// with the standard strict decoder, rejecting any decode error outright
// rather than stripping whitespace or best-effort decoding.
func parseSignalLine(line, token, expectedNonce string) (string, bool) {
	idx := tokenIndex(line, token)
	if idx < 0 {
		return "", false
	}
	// fields[0] must equal expectedNonce exactly: strings.Fields already
	// splits on whitespace, so this is itself a word-bounded check, and an
	// empty expectedNonce can never match since Fields never yields an
	// empty token -- no separate LineHasNonce gate needed.
	fields := strings.Fields(line[idx+len(token):])
	if len(fields) < 2 || fields[0] != expectedNonce {
		return "", false
	}
	payload := base64AlphabetPrefix(fields[1])
	decoded, err := base64.StdEncoding.Strict().DecodeString(payload)
	if err != nil {
		return "", false
	}
	return string(decoded), true
}

// LineHasNonce reports whether line carries expected as a standalone token
// (issue #1937) — the shared check a caller uses to tell a genuine
// control-signal line, produced by this run's own Box, from one an
// untrusted issue/comment author echoed into the log verbatim: the author
// writes their text before the per-run nonce is minted, so they cannot know
// its value. Word-bounded via containsToken, so a longer token that merely
// contains expected as a substring does not false-positive. An empty
// expected never matches.
func LineHasNonce(line, expected string) bool {
	if expected == "" {
		return false
	}
	return containsToken(line, expected)
}

// containsToken reports whether line contains token as a standalone word,
// not merely as a substring of a longer identifier (e.g. "SPINDRIFT_OUTCOMES"
// or "MY_SPINDRIFT_OUTCOME_THING" must not match).
func containsToken(line, token string) bool {
	return tokenIndex(line, token) >= 0
}

// tokenIndex returns the index of token's first standalone-word occurrence
// in line, or -1 if none exists. Standalone means not preceded or followed
// by an identifier character (see isTokenChar), so a longer identifier that
// merely contains token as a substring never matches. A literal `\n`
// (backslash then 'n') immediately before the token counts as a left
// boundary too, alongside a genuine non-token-char: it's JSON's escaping of
// a real newline the Box's own text wrote right before the token — e.g. a
// line of narration flowing straight into a control-signal line within the
// same stream-json text field — and a real newline is unambiguously a
// boundary, so its escaped form must be too. Without this, the escaped
// sequence's trailing 'n' (itself a token char) would look like it extends
// the token into a longer identifier and reject a placement no different
// from the token simply starting its own physical line.
func tokenIndex(line, token string) int {
	for start := 0; ; {
		i := strings.Index(line[start:], token)
		if i < 0 {
			return -1
		}
		begin := start + i
		end := begin + len(token)
		leftOK := begin == 0 || !isTokenChar(line[begin-1]) ||
			(line[begin-1] == 'n' && begin >= 2 && line[begin-2] == '\\')
		rightOK := end == len(line) || !isTokenChar(line[end])
		if leftOK && rightOK {
			return begin
		}
		start = begin + 1
	}
}

func isTokenChar(b byte) bool {
	return b == '_' || ('a' <= b && b <= 'z') || ('A' <= b && b <= 'Z') || ('0' <= b && b <= '9')
}

// stripToken reports whether line begins with token followed by a space or a
// colon (the tolerated delimiters), and returns the remainder after the
// delimiter for field extraction.
func stripToken(line, token string) (string, bool) {
	if rest, ok := strings.CutPrefix(line, token+" "); ok {
		return rest, true
	}
	if rest, ok := strings.CutPrefix(line, token+":"); ok {
		return rest, true
	}
	return "", false
}

// tokenField extracts the value of key=<val> from a space-delimited line.
// val ends at the next space; use tailField for the note field.
func tokenField(line, key string) string {
	prefix := key + "="
	for _, tok := range strings.Fields(line) {
		if strings.HasPrefix(tok, prefix) {
			return tok[len(prefix):]
		}
	}
	return ""
}

// tailField returns everything after the first " key=" in line, allowing the
// value to contain spaces and '=' (used for the note field).
func tailField(line, key string) string {
	marker := " " + key + "="
	if idx := strings.Index(line, marker); idx >= 0 {
		return line[idx+len(marker):]
	}
	return ""
}

// noteField is tailField("note") with the trailing " nonce=<value>" field
// (issue #1939) stripped back off, so it never ends up inside Note: the
// grammar places nonce last, after note's own greedy tail, and a run's note
// gets posted as a public comment on status=blocked (settle.postBlockedNoteComment)
// — leaking the nonce there would let a comment author replay it against a
// later retry of the same Dispatch, which reuses one nonce across all its
// attempts. A trailing "nonce=<value>" only counts as the field, not as note
// text that happens to contain it, when <value> itself has no spaces —
// exactly the shape a genuine, single-token nonce always has.
func noteField(line string) string {
	v := tailField(line, "note")
	const marker = " nonce="
	if idx := strings.LastIndex(v, marker); idx >= 0 {
		if nonce := v[idx+len(marker):]; nonce != "" && !strings.Contains(nonce, " ") {
			return v[:idx]
		}
	}
	return v
}
