// Code generated by nix/regen.nix from lib/prompt-contract.nix. DO NOT EDIT.
package outcome

// Regenerate with `nix run .#regen` after editing lib/prompt-contract.nix's
// outcomeStatusSets.

// Agent-emittable SPINDRIFT_OUTCOME status words (issue #2504). Host-side
// dispositions (failed, merge verification) are a separate typed family
// (ADR 0039) and are not represented here; `merged` is a tolerated
// off-script arm (cmd/launcher/internal/settle/gate.go) and is
// deliberately absent too. ResearchStatuses is the compiled-default
// research verdict vocabulary (see forge.ResearchVerdictLabels); the
// research vocabulary is operator-configurable via RESEARCH_VERDICTS.
const (
	StatusReady     = "ready"
	StatusBlocked   = "blocked"
	StatusAmbiguous = "ambiguous"
	StatusRecommend = "recommend"
	StatusReject    = "reject"
	StatusUnclear   = "unclear"
)

// WorkStatuses is the ordered work-kind agent-emittable status set.
var WorkStatuses = []string{StatusReady, StatusBlocked, StatusAmbiguous}

// ResearchStatuses is the ordered research-kind agent-emittable status set.
var ResearchStatuses = []string{StatusRecommend, StatusReject, StatusUnclear, StatusBlocked}
