// Code generated by nix/regen.nix from lib/quickstart-path-table.nix. DO NOT EDIT.
package main

// Regenerate with `nix run .#regen` after editing lib/env-schema.nix or
// lib/quickstart-path-table.nix.
//
// The nix option path for each quickstart wizard knob (lib/nixpath.nix's
// domain-tree resolution over lib/env-schema.nix's group/nixSubPath),
// single-sourced here so the wizard's rendered flake.nix literals can't
// drift from the schema's own group/nixSubPath taxonomy (issue #2556).

// pathCodeForge is the nix option path for the quickstart wizard's codeForge knob.
const pathCodeForge = "forge.backend"

// pathForgejoBaseURL is the nix option path for the quickstart wizard's forgejoBaseURL knob.
const pathForgejoBaseURL = "issues.forgejo.baseURL"

// pathGitUserEmail is the nix option path for the quickstart wizard's gitUserEmail knob.
const pathGitUserEmail = "git.user.email"

// pathGitUserName is the nix option path for the quickstart wizard's gitUserName knob.
const pathGitUserName = "git.user.name"

// pathIssueTracker is the nix option path for the quickstart wizard's issueTracker knob.
const pathIssueTracker = "issues.tracker"

// pathRepoSlug is the nix option path for the quickstart wizard's repoSlug knob.
const pathRepoSlug = "forge.repoSlug"

// pathRuntime is the nix option path for the quickstart wizard's runtime knob.
const pathRuntime = "infra.runtime"
