// Code generated by nix/regen.nix from lib/runtime-values.nix. DO NOT EDIT.
package main

// validRuntimeChoices are the operator-facing runtime values the wizard
// accepts (lib/runtime-values.nix), the same list lib/flakeModule.nix's
// `runtime` option enum uses.
// Regenerate with `nix run .#regen` after editing lib/runtime-values.nix.
var validRuntimeChoices = []string{"podman", "docker", "rancher", "bwrap"}
