// Code generated by nix/regen.nix from lib/quickstart-path-table.nix. DO NOT EDIT.
package main

// Regenerate with `nix run .#regen` after editing lib/env-schema.nix or
// lib/quickstart-path-table.nix.
//
// The nix option path for each quickstart wizard knob (lib/nixpath.nix's
// domain-tree resolution over lib/env-schema.nix's group/nixSubPath),
// single-sourced here so the wizard's rendered flake.nix literals can't
// drift from the schema's own group/nixSubPath taxonomy (issue #2556).

// PathCodeForge is the nix option path for the quickstart wizard's codeForge knob.
const PathCodeForge = "forge.backend"

// PathForgejoBaseURL is the nix option path for the quickstart wizard's forgejoBaseURL knob.
const PathForgejoBaseURL = "issues.forgejo.baseURL"

// PathGitUserEmail is the nix option path for the quickstart wizard's gitUserEmail knob.
const PathGitUserEmail = "git.user.email"

// PathGitUserName is the nix option path for the quickstart wizard's gitUserName knob.
const PathGitUserName = "git.user.name"

// PathIssueTracker is the nix option path for the quickstart wizard's issueTracker knob.
const PathIssueTracker = "issues.tracker"

// PathRepoSlug is the nix option path for the quickstart wizard's repoSlug knob.
const PathRepoSlug = "forge.repoSlug"

// PathRuntime is the nix option path for the quickstart wizard's runtime knob.
const PathRuntime = "infra.runtime"
