// Code generated by nix/regen.nix from lib/labels.nix. DO NOT EDIT.
package doctor

var MetaDispatchable = LabelMeta{Description: "Fully specified; ready for an AFK agent", Color: "0075ca"}
var MetaInProgress = LabelMeta{Description: "An AFK agent is actively working this issue", Color: "e4e669"}
var MetaFailed = LabelMeta{Description: "Box exited non-zero; needs human triage", Color: "d93f0b"}
var MetaComplete = LabelMeta{Description: "Agent work merged and green", Color: "0e8a16"}

// TriageLabelMeta is the single source of truth for default triage/
// research/priority label colors and descriptions, keyed by the canonical
// label name (lib/labels.nix, issue #2528).
var TriageLabelMeta = map[string]LabelMeta{
	"ready-for-agent":   MetaDispatchable,
	"agent-in-progress": MetaInProgress,
	"agent-failed":      MetaFailed,
	"agent-complete":    MetaComplete,

	"agent-research":             LabelMeta{Description: "Apply to fire a research dispatch", Color: "fbca04"},
	"agent-research-in-progress": LabelMeta{Description: "A Box is reviewing this issue", Color: "bfd4f2"},
	"agent-research-failed":      LabelMeta{Description: "Box crashed or produced no verdict; needs human triage", Color: "b60205"},

	"agent-research-recommend": LabelMeta{Description: "Relevant and enriched — promote it", Color: "2cbe4e"},
	"agent-research-reject":    LabelMeta{Description: "False positive, not worth it, or a duplicate — close it", Color: "e11d21"},
	"agent-research-unclear":   LabelMeta{Description: "Needs a human answer — answer, then re-apply agent-research", Color: "d4c5f9"},

	"agent-priority-critical": LabelMeta{Description: "Drop everything — highest dispatch priority", Color: "d73a4a"},
	"agent-priority-high":     LabelMeta{Description: "Dispatch ahead of normal-priority issues", Color: "ff8c00"},
	"agent-priority-low":      LabelMeta{Description: "Dispatch behind normal-priority issues", Color: "8a9ba8"},

	"agent-ambiguous-spec": LabelMeta{Description: "An internally-contradictory issue; needs a human decision — not a crash", Color: "e0cffc"},

	"agent-research-finding": LabelMeta{Description: "Filed from a research finding", Color: "c5def5"},
}

// FindingTypeLabels is the closed bug/enhancement/chore issue-intent
// type->label vocabulary (lib/labels.nix's findingType family, issue
// #2594 / ADR 0041), kept separate from TriageLabelMeta on purpose -- see
// lib/labels.nix's findingType doc comment.
var FindingTypeLabels = map[string]LabelMeta{
	"bug":         LabelMeta{Description: "Filed as a bug finding", Color: "ee0701"},
	"enhancement": LabelMeta{Description: "Filed as an enhancement finding", Color: "a2eeef"},
	"chore":       LabelMeta{Description: "Filed as a chore finding", Color: "fef2c0"},
}
