// Code generated by nix/checks.nix from lib/drivers/default.nix. DO NOT EDIT.
package driver

// nixDriverNames is the key list of the Nix Driver registry (lib/drivers/default.nix).
// Regenerate with `nix run .#regen` after editing lib/drivers/default.nix.
var nixDriverNames = []string{"claude"}
